#!/bin/sh
. /usr/local/sbin/e
export PROJECT_NAME=libidn
[ -z "$SANITIZER" ] && export SANITIZER='none'
cd $SRC

#apt-get update && apt-get install -y pkg-config autopoint autoconf autoconf-archive automake libtool gettext gengetopt curl gperf wget

mkdir /src/tmp
cp -f /src/libidn/fuzz/*.c /src/tmp
rm -rf /src/$PROJECT_NAME

git clone https://git.savannah.gnu.org/git/libidn.git
mv -f /src/tmp/* /src/libidn/fuzz
rmdir /src/tmp

cp /opt/oss-fuzz/projects/$PROJECT_NAME/build.sh $SRC/

cd $SRC/$PROJECT_NAME
if [ ! -d "/home/hacker/$PROJECT_NAME" ]; then
   mkdir ~/$PROJECT_NAME
   cp $SRC/$PROJECT_NAME/yyyyyyyyyyyy/zzzzzzzzzzzzzzzzz.c $SRC/$PROJECT_NAME/yyyyyyyyyyyy/newfuzzer.c
   cp $SRC/$PROJECT_NAME/yyyyyyyyyyyy/*.c ~/$PROJECT_NAME
else
   cp ~/$PROJECT_NAME/*.c $SRC/$PROJECT_NAME/yyyyyyyyyyyy
fi
#patch -tuN /src/build.sh -i /challenge/build.patch -r -
compile