#!/bin/sh
. /usr/local/sbin/e.sh
export PROJECT_NAME=libidn
[ -z "$SANITIZER" ] && export SANITIZER='none'
cd $SRC

apt-get update && apt-get install -y \
 pkg-config \
 autopoint \
 autoconf \
 autoconf-archive \
 automake \
 libtool \
 gettext gengetopt curl gperf wget

git clone https://git.savannah.gnu.org/git/libidn.git

cp /opt/oss-fuzz/projects/$PROJECT_NAME/build.sh $SRC/

cd $SRC/$PROJECT_NAME
compile