#!/opt/pwn.college/bash 
INITIAL=80
TARGET=85
sudo -H -u hacker bash -c /usr/local/sbin/loc_count $1
/usr/local/sbin/announce $INITIAL $? 
if [ "$?" -gt "$TARGET" ]; then
    echo
    echo Congratulations!  But make sure you also submit your improvements to Google!
    cat /flag
fi
if compgen -G "/out/crash*" > /dev/null; then
    echo
    echo "Crashes detected within the /out directory!"
    echo
fi
