#!/opt/pwn.college/bash
export PROJECT_NAME=libvpx
/challenge/.loc_count
cd /src

cp -r /opt/fuzz-targets/libvpx /src
cp -r /opt/fuzz-targets/vpx_fuzzer_seed_corpus.zip /src

cp /opt/oss-fuzz/projects/$PROJECT_NAME/build.sh /src/
cp /opt/oss-fuzz/projects/$PROJECT_NAME/vpx_dec_fuzzer.dict /src/

patch -tuN /src/build.sh -i /challenge/.build.patch -r -
cd /src/$PROJECT_NAME

cp /home/hacker/$PROJECT_NAME/*.c /src/$PROJECT_NAME/examples
cp /home/hacker/$PROJECT_NAME/build.sh /src
/challenge/.fi $PROJECT_NAME
