#!/opt/pwn.college/bash
. /usr/local/sbin/eafl
export PROJECT_NAME=openssl
export SANITIZER=$1
[ -z "$SANITIZER" ] && export SANITIZER='none'

mkdir $SRC/fuzz
mv $SRC/$PROJECT_NAME/fuzz/*.c $SRC/fuzz
rm -rf $SRC/$PROJECT_NAME

#apt-get install -y make
#git clone --depth 1 https://github.com/openssl/openssl.git $SRC/openssl
#cd $SRC/openssl/ && git submodule update --init fuzz/corpora
#cd $SRC
#git clone --depth 1 --branch OpenSSL_1_1_1-stable https://github.com/openssl/openssl.git openssl111
#git clone --depth 1 --branch openssl-3.0 https://github.com/openssl/openssl.git openssl30

cp -r /opt/fuzz-targets/openssl /src/openssl
cp -r /opt/fuzz-targets/openssl111 /src/openssl111
cp -r /opt/fuzz-targets/openssl30 /src/openssl30
cp -r /opt/fuzz-targets/openssl31 /src/openssl31
cp -r /opt/fuzz-targets/openssl32 /src/openssl32

export AFL_SKIP_OSSFUZZ=1
export AFL_LLVM_MODE_WORKAROUND=0
cp /opt/oss-fuzz/projects/openssl/build.sh $SRC/
cp /opt/oss-fuzz/projects/openssl/*.options $SRC/

cp -f $SRC/fuzz/* $SRC/$PROJECT_NAME/fuzz 
rm -rf $SRC/fuzz/

cd $SRC/openssl

sudo --preserve-env compile
drivers
