#!/opt/pwn.college/bash
. /usr/local/sbin/e
if [ "$?" -gt 0 ]; then
    exit 1
fi
export LABEL=$1
export PROJECT_NAME=solidity
export SANITIZER=$1
if [ -z "$SANITIZER" ]; then
    export SANITIZER='none'
    export LABEL='none'$LABEL
fi

if [ ! -d "/src-orig" ]; then
#----------------------------------------------------------------------
: <<'END_COMMENT'
# ! This project was pinned after a clang bump. Please remove the pin, Try to fix any build warnings and errors, as well as runtime errors
RUN apt-get update && apt-get install -y make autoconf automake libtool \
    build-essential libbz2-dev ninja-build zlib1g-dev wget python python-dev \
    liblzma-dev uuid-dev pkg-config openjdk-8-jdk unzip mlton bison texinfo

RUN git clone --recursive -b develop https://github.com/ethereum/solidity.git solidity
RUN git clone --depth 1 https://github.com/ethereum/solidity-fuzzing-corpus.git
RUN git clone https://github.com/google/libprotobuf-mutator.git
RUN git clone --branch="v0.11.0" --recurse-submodules \
    https://github.com/ethereum/evmone.git

# Install statically built dependencies in "/usr" directory
# Install boost
RUN cd $SRC && \
    wget -q 'https://archives.boost.io/release/1.83.0/source/boost_1_83_0.tar.bz2' -O boost.tar.bz2 && \
    test "$(sha256sum boost.tar.bz2)" = "6478edfe2f3305127cffe8caf73ea0176c53769f4bf1585be237eb30798c3b8e  boost.tar.bz2" && \
    tar -xf boost.tar.bz2 && \
    rm boost.tar.bz2 && \
    cd boost_1_83_0 && \
    CXXFLAGS="-stdlib=libc++ -pthread" LDFLAGS="-stdlib=libc++" ./bootstrap.sh --with-toolset=clang --prefix=/usr && \
    ./b2 toolset=clang cxxflags="-stdlib=libc++ -pthread" linkflags="-stdlib=libc++ -pthread" headers && \
    ./b2 toolset=clang cxxflags="-stdlib=libc++ -pthread" linkflags="-stdlib=libc++ -pthread" \
        link=static variant=release runtime-link=static \
        system filesystem unit_test_framework program_options \
        install -j $(($(nproc)/2)) && \
    rm -rf $SRC/boost_1_83_0

# Install libprotobuf-mutator
# Use commit prior to libprotobuf upgrade that broke solidity build
# See https://github.com/google/oss-fuzz/issues/10237
RUN cd $SRC/libprotobuf-mutator; \
    git reset --hard 212a7be1eb08e7f9c79732d2aab9b2097085d936; \
    mkdir $SRC/LPM; \
    cd $SRC/LPM; \
    cmake $SRC/libprotobuf-mutator -GNinja \
    -DLIB_PROTO_MUTATOR_DOWNLOAD_PROTOBUF=ON -DLIB_PROTO_MUTATOR_TESTING=OFF \
    -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX="/usr"; \
    ninja; \
    ninja install; \
    cd external.protobuf; \
    cp -Rf bin lib include /usr;

# Install evmone
RUN cd $SRC/evmone; \
    mkdir -p build; \
    cd build; \
    cmake .. -G Ninja -DBUILD_SHARED_LIBS=OFF -DCMAKE_INSTALL_PREFIX="/usr"; \
    ninja; \
    ninja install/strip;

# gmp
RUN cd $SRC; \
    # Replace system installed libgmp static library
    # with sanitized version
    git clone --depth 1 --branch gmp-6.2.1 https://github.com/gmp-mirror/gmp-6.2 gmp/; \
    rm -r gmp/.git/; \
    test \
        "$(tar --create gmp/ --sort=name --mtime=1970-01-01Z --owner=0 --group=0 --numeric-owner | sha256sum)" = \
        "d606ff6a4ce98692f9920031e85ea8fcf4a65ce1426f6f0048b8794aefed174b  -"; \
    # NOTE: This removes also libgmp.so, which git depends on
    rm -f /usr/lib/x86_64-linux-gnu/libgmp.*; \
    rm -f /usr/include/x86_64-linux-gnu/gmp.h; \
    cd gmp; \
    autoreconf -i; \
    ./configure --prefix=/usr --enable-static=yes --enable-maintainer-mode; \
    make -j; \
    make check; \
    make install; \
    rm -rf $SRC/gmp;

# libabicoder
RUN set -ex; \
    cd /usr/src; \
    git clone https://github.com/ekpyron/Yul-Isabelle; \
    cd Yul-Isabelle; \
    cd libabicoder; \
    CXX=clang++ CXXFLAGS="-stdlib=libc++ -pthread" make; \
    cp libabicoder.a /usr/lib; \
    cp abicoder.hpp /usr/include; \
    rm -rf /usr/src/Yul-Isabelle

COPY build.sh $SRC/
END_COMMENT
#-----------------

    echo Please wait, initial copy of solidity
    cp -r /downloads/solidity $SRC
    echo Please wait, initial copy of solidity corpus
    cp -r /downloads/solidity-fuzzing-corpus $SRC
    echo Please wait, initial copy of libprotobuf
    cp -r /downloads/libprotobuf-mutator $SRC
    echo Please wait, initial copy of evmone
    cp -r /downloads/evmone $SRC
                
# Install statically built dependencies in "/usr" directory
# Install boost
cd $SRC && \
    cp -r /downloads/boost.tar.bz2 $SRC && \
    test "$(sha256sum boost.tar.bz2)" = "6478edfe2f3305127cffe8caf73ea0176c53769f4bf1585be237eb30798c3b8e  boost.tar.bz2" && \
    tar -xf boost.tar.bz2 && \
    rm boost.tar.bz2 && \
    cd boost_1_83_0 && \
    CXXFLAGS="-stdlib=libc++ -pthread" LDFLAGS="-stdlib=libc++" ./bootstrap.sh --with-toolset=clang --prefix=/usr && \
    ./b2 toolset=clang cxxflags="-stdlib=libc++ -pthread" linkflags="-stdlib=libc++ -pthread" headers && \
    ./b2 toolset=clang cxxflags="-stdlib=libc++ -pthread" linkflags="-stdlib=libc++ -pthread" \
        link=static variant=release runtime-link=static \
        system filesystem unit_test_framework program_options \
        install -j $(($(nproc)/2)) && \
    rm -rf $SRC/boost_1_83_0

# Install libprotobuf-mutator
# Use commit prior to libprotobuf upgrade that broke solidity build
# See https://github.com/google/oss-fuzz/issues/10237
cd $SRC/libprotobuf-mutator; \
    mkdir $SRC/LPM; \
    cd $SRC/LPM; \
    cmake $SRC/libprotobuf-mutator -GNinja \
    -DLIB_PROTO_MUTATOR_DOWNLOAD_PROTOBUF=ON -DLIB_PROTO_MUTATOR_TESTING=OFF \
    -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX="/usr"; \
    ninja; \
    ninja install; \
    cd external.protobuf; \
    cp -Rf bin lib include /usr;

# Install evmone
cd "$SRC/evmone"; \
    rm -rf build; \
    mkdir -p build; \
    cd build; \
    EVMONE_CFLAGS="$(printf '%s' "${CFLAGS:-}" | sed 's/-stdlib=libc++//g')" ; \
    EVMONE_CXXFLAGS="$(printf '%s' "${CXXFLAGS:-}" | sed 's/-stdlib=libc++/-stdlib=libstdc++/g')" ; \
    CC=clang CXX=clang++ \
    CFLAGS="$EVMONE_CFLAGS" \
    CXXFLAGS="$EVMONE_CXXFLAGS" \
    cmake .. -G Ninja \
      -DBUILD_SHARED_LIBS=OFF \
      -DCMAKE_INSTALL_PREFIX="/usr" \
      -DCMAKE_C_COMPILER=clang \
      -DCMAKE_CXX_COMPILER=clang++ \
      -DCMAKE_CXX_FLAGS="$EVMONE_CXXFLAGS" ; \
    ninja; \
    ninja install/strip;

# gmp
cd $SRC; \
    # Replace system installed libgmp static library
    # with sanitized version
    cp -r /downloads/gmp $SRC; \
    rm -r gmp/.git/; \
    test \
        "$(tar --create gmp/ --sort=name --mtime=1970-01-01Z --owner=0 --group=0 --numeric-owner | sha256sum)" = \
        "d606ff6a4ce98692f9920031e85ea8fcf4a65ce1426f6f0048b8794aefed174b  -"; \
    # NOTE: This removes also libgmp.so, which git depends on
    rm -f /usr/lib/x86_64-linux-gnu/libgmp.*; \
    rm -f /usr/include/x86_64-linux-gnu/gmp.h; \
    cd gmp; \
    autoreconf -i; \
    ./configure --prefix=/usr --enable-static=yes --enable-maintainer-mode; \
    make -j; \
    make check; \
    make install; \
    rm -rf $SRC/gmp;

# libabicoder
set -ex; \
    cd /usr/src; \
    cp -r /downloads/Yul-Isabelle /usr/src; \
    cd Yul-Isabelle; \
    cd libabicoder; \
    CXX=clang++ CXXFLAGS="-stdlib=libc++ -pthread" make; \
    cp libabicoder.a /usr/lib; \
    cp abicoder.hpp /usr/include; \
    rm -rf /usr/src/Yul-Isabelle


    #cp /downloads/aspell*.bz2 /tmp

    cp /opt/oss-fuzz/projects/solidity/build.sh $SRC/
    #cp /challenge/.fuzz-packet_seed_corpus.zip $OUT/fuzz-packet_seed_corpus.zip
    #patch -tuN $SRC/$PROJECT_NAME/ossfuzz.sh -i /challenge/.ossfuzz.patch -r -
    #patch -tuN $SRC/$PROJECT_NAME/Makefile.am -i /challenge/.Makefile.patch -r -
        
    #cp $SRC/$PROJECT_NAME/aspell_fuzzer.cpp $SRC/$PROJECT_NAME/new_fuzzer.cpp
#----------------------------------------------------------------------
    build-cleanup
fi
build-srcfolders
mv /src-$LABEL /src

cd $SRC/$PROJECT_NAME
#----------------------------------------------------------------------
if [ ! -d "/home/hacker/fuzz-dojo/$PROJECT_NAME" ]; then
   mkdir -p /home/hacker/fuzz-dojo/$PROJECT_NAME
   cp $SRC/$PROJECT_NAME/*.cpp /home/hacker/fuzz-dojo/$PROJECT_NAME
   cp $SRC/build.sh /home/hacker/fuzz-dojo/$PROJECT_NAME
else
   cp /home/hacker/fuzz-dojo/$PROJECT_NAME/*.cpp $SRC/$PROJECT_NAME
   cp /home/hacker/fuzz-dojo/$PROJECT_NAME/build.sh $SRC
fi
#----------------------------------------------------------------------
if [ "$4" = "understanding" ]; then
    understanding $2 $3
elif [ "$4" = "planning" ]; then
    planning $2 $3
else
    fuzzlog
    compile
    drivers
fi
mv /src /src-$LABEL
