#!/opt/pwn.college/bash
echo 999 > /tmp/initial
echo 999 > /tmp/target
if [ "$1" = "afl" ]; then
    . /usr/local/sbin/eafl
    shift
else
    . /usr/local/sbin/e
fiafl
export PROJECT_NAME=lua
export SANITIZER=$1
[ -z "$SANITIZER" ] && export SANITIZER='none'
cd $SRC

rm -rf $SRC/testdir
git clone https://github.com/ligurio/lua-c-api-tests testdir
cd $SRC/testdir
git clone --depth 1 --jobs $(nproc) https://github.com/ligurio/lua-c-api-corpus corpus_dir
cp /opt/oss-fuzz/projects/$PROJECT_NAME/build.sh $SRC
cp /opt/oss-fuzz/projects/$PROJECT_NAME/build.sh $SRC/testdir
cp /opt/oss-fuzz/projects/$PROJECT_NAME/fuzz_lua.c $SRC

patch -tuN $SRC/build.sh -i /challenge/.build.patch -r -
patch -tuN $SRC/testdir/build/tests/CTestTestfile.cmake -i /challenge/.CTest.patch -r -
patch -tuN $SRC/testdir/tests/CMakeLists.txt -i /challenge/.CMakeLists.patch -r -
cd $SRC
if [ ! -d "/home/hacker/$PROJECT_NAME" ]; then
   mkdir /home/hacker/$PROJECT_NAME
   cp $SRC/testdir/tests/luaL_loadbuffer_test.c $SRC/testdir/tests/newfuzzer.c
   cp $SRC/testdir/tests/*.c /home/hacker/$PROJECT_NAME
   cp $SRC/testdir/tests/*.cc /home/hacker/$PROJECT_NAME
   cp $SRC/testdir/build/tests/CTestTestfile.cmake /home/hacker/$PROJECT_NAME/
   cp $SRC/testdir/tests/CMakeLists.txt /home/hacker/$PROJECT_NAME
   cp $SRC/build.sh /home/hacker/$PROJECT_NAME
   chown -R hacker /home/hacker/$PROJECT_NAME
else
   cp /home/hacker/$PROJECT_NAME/*.c $SRC/testdir/tests
   cp /home/hacker/$PROJECT_NAME/*.cc $SRC/testdir/tests
   cp /home/hacker/$PROJECT_NAME/CTestTestfile.cmake $SRC/testdir/build/tests
   cp /home/hacker/$PROJECT_NAME/CMakeLists.txt $SRC/testdir/tests
   cp /home/hacker/$PROJECT_NAME/build.sh $SRC
fi
mkdir -p /home/hacker/.log
[ ! "$SANITIZER" = "introspector" ] && [ ! "$SANITIZER" = "coverage" ] && zip -ry /home/hacker/.log/$(TZ=US/Arizona date +"%F--%H-%M-%S")-$PROJECT_NAME /home/hacker/$PROJECT_NAME
compile
drivers
