#!/bin/sh
. /usr/local/sbin/e.sh
export PROJECT_NAME=opensips
[ -z "$SANITIZER" ] && export SANITIZER='none'
cd $SRC

apt-get update && apt-get install -y bison flex libssl-dev pkg-config
git clone https://github.com/OpenSIPS/opensips

cp /opt/oss-fuzz/projects/$PROJECT_NAME/build.sh $SRC/
cd $SRC/$PROJECT_NAME
compile
