#!/bin/bash
export DRIVERS=('fuzz_core_funcs' 'fuzz_csv_parser' 'fuzz_msg_parser' 'fuzz_uri_parser')
export PROJECT_NAME=opensips
/usr/local/sbin/loc_count.sh $PROJECT_NAME "${DRIVERS[@]}"
cd /src/$PROJECT_NAME
/usr/local/sbin/fi.sh $PROJECT_NAME "${DRIVERS[@]}"
