#!/opt/pwn.college/bash
export PROJECT_NAME=uriparser
sudo cp /usr/local/sbin/loc_count /usr/local/sbin/fi /challenge
sudo chmod 4755 /challenge/loc_count /challenge/fi
/challenge/loc_count
cd /src
rm -rf uriparser
#apt-get update && apt-get install -y make autoconf automake wget sudo libtool cmake
#git clone --depth 1 https://github.com/uriparser/uriparser uriparser
cp -r /opt/fuzz-targets/uriparser /src/uriparser

cd $SRC/$PROJECT_NAME
/challenge/fi $PROJECT_NAME
