#!/opt/pwn.college/bash
export PROJECT_NAME=uriparser
/challenge/.loc_count
cd /src
rm -rf uriparser
#apt-get update && apt-get install -y make autoconf automake wget sudo libtool cmake
#git clone --depth 1 https://github.com/uriparser/uriparser uriparser
cp -r /opt/fuzz-targets/uriparser /src/uriparser

cd /src/$PROJECT_NAME
/challenge/.fi $PROJECT_NAME
