#!/bin/bash
export PROJECT_NAME=uriparser
/usr/local/sbin/loc_count
cd /src
rm -rf uriparser
#apt-get update && apt-get install -y make autoconf automake wget sudo libtool cmake
git clone --depth 1 https://github.com/uriparser/uriparser uriparser
cd $SRC/$PROJECT_NAME
/usr/local/sbin/fi $PROJECT_NAME
