#!/bin/sh
. /usr/local/sbin/e
export PROJECT_NAME=miniz
[ -z "$SANITIZER" ] && export SANITIZER='none'
cd $SRC

rm -rf $SRC/$PROJECT_NAME/build
git clone --depth 1 https://github.com/richgel999/miniz.git

cp /opt/oss-fuzz/projects/$PROJECT_NAME/build.sh $SRC/
cd $SRC/$PROJECT_NAME
if [ ! -d "/home/hacker/$PROJECT_NAME" ]; then
   mkdir ~/$PROJECT_NAME
   cp $SRC/$PROJECT_NAME/tests/compress_fuzzer.c $SRC/$PROJECT_NAME/tests/new_fuzzer.c
   cp $SRC/$PROJECT_NAME/tests/*.c ~/$PROJECT_NAME
else
   cp ~/$PROJECT_NAME/*.c $SRC/$PROJECT_NAME/tests
fi
#patch -tuN /src/build.sh -i /challenge/build.patch -r -
compile
