#!/opt/pwn.college/bash 
INITIAL=43
TARGET=48
sudo -H -u hacker bash -c /usr/local/sbin/loc_count
/usr/local/sbin/announce $INITIAL $? 
if [ "$?" -gt "$TARGET" ]; then
    echo
    echo Congratulations!  But make sure you also submit your improvements to Google!
    cat /flag
fi
