#!/opt/pwn.college/bash
if [ "$?" -gt 0 ]; then
    exit 1
fi
export LABEL=$1
export PROJECT_NAME=exiv2
export SANITIZER=$1
. /usr/local/sbin/e
if [ -z "$SANITIZER" ]; then
    export SANITIZER='none'
    export LABEL='none'$LABEL
fi

if [ ! -d "/src-orig" ]; then
#----------------------------------------------------------------------
    rm -rf $SRC/$PROJECT_NAME
    #git clone https://github.com/Exiv2/exiv2 exiv2
    #./exiv2/ci/install_dependencies.sh
    #apt-get install -y cmake ninja-build g++ ---clang--- libexpat1-dev zlib1g-dev libbrotli-dev libssh-dev libcurl4-openssl-dev libgmock-dev libxml2-utils libinih-dev
    cp -r /downloads/exiv2 $SRC

    cp /opt/oss-fuzz/projects/$PROJECT_NAME/build.sh $SRC/
#----------------------------------------------------------------------
    build-cleanup-oss
fi
build-srcfolders
if [ "$4" == "skip" ]; then
    chown -hR hacker:hacker /src-$LABEL /out
    rm -rf /tmp/build.lck
else
    mv /src-$LABEL /src

    cd $SRC/$PROJECT_NAME
    if [ "$4" = "understanding" ]; then
        understanding $2 $3
    elif [ "$4" = "planning" ]; then
        planning $2 $3
    else
        if [ $(echo -n "$2" | sha256sum | cut -d' ' -f1) != "2ed73ee0d7ad2fd8b8e57fc154cfc26f3948ed32b2844b34479333e5b07712a5" ]; then
            oss_help
            rm -rf /tmp/build.lck
            exit 1
        elif [ "$3" != "$PROJECT_NAME" ]; then
            echo "[ERROR] Project $3 not available in this challenge"
            rm -rf /tmp/build.lck
            exit 1
        fi
        fuzzlog_oss $SRC/$PROJECT_NAME/fuzz/*.cpp
        compile
        drivers > /dev/null
    fi
    mv /src /src-$LABEL
fi
