#!/opt/pwn.college/bash 
INITIAL=1
TARGET=45
sudo -H -u hacker bash -c /usr/local/sbin/loc_count2
echo
echo newfuzzer
/usr/local/sbin/loc newfuzzer
/usr/local/sbin/announce $INITIAL $? 
if [ "$?" -gt "$TARGET" ]; then
    echo
    echo Congratulations!
    cat /flag
fi
if compgen -G "/out/crash*" > /dev/null; then
    echo
    echo "Crashes detected within the /out directory!"
    echo
fi
