#!/opt/pwn.college/bash 
INITIAL=1
TARGET=45
time sudo -H -u hacker bash -c "/usr/local/sbin/loc_count2 undefined"
echo
echo newfuzzer
/usr/local/sbin/loc-calc newfuzzer
/usr/local/sbin/announce $INITIAL $? 
if [ "$?" -ge "$TARGET" ]; then
    echo
    echo Congratulations!
    cat /flag
fi
if compgen -G "/out/crash*" > /dev/null; then
    echo
    echo "Crashes detected within the /out directory!"
    echo
fi
