#!/bin/sh
. /usr/local/sbin/e.sh
[ -z "$SANITIZER" ] && export SANITIZER='none'
cd $SRC

apt-get update && apt-get install -y make autoconf automake libtool
RUN git clone --depth 1 https://github.com/c-ares/c-ares.git

cp /opt/oss-fuzz/projects/c-ares/build.sh $SRC/
cd $SRC/c-ares
export OLD_LLVMPASS=1
compile