#!/bin/bash
export PROJECT_NAME=c-ares
INITIAL=34
TARGET=39
/usr/local/sbin/loc_count $PROJECT_NAME
/usr/local/sbin/announce $INITIAL $? 
if [ "$?" -gt "$TARGET" ]; then
    echo
    echo Congratulations!  But make sure you also submit your improvements to Google!
    cat /flag
fi
