#!/opt/pwn.college/bash
export PROJECT_NAME=json
/challenge/.loc_count
cd /src
rm -rf $PROJECT_NAME
#git clone --depth 1 -b develop https://github.com/nlohmann/json.git
cp -r /opt/fuzz-targets/json /src/json

# This is to fix Fuzz Introspector build by using LLVM old pass manager
# re https://github.com/ossf/fuzz-introspector/issues/305
export OLD_LLVMPASS=1

cd /src/$PROJECT_NAME
cp /home/hacker/$PROJECT_NAME/*.cpp /src/$PROJECT_NAME/tests/src
cp /home/hacker/$PROJECT_NAME/Makefile /src/$PROJECT_NAME/tests
/challenge/.fi $PROJECT_NAME
