#!/opt/pwn.college/bash
echo 39 > /tmp/initial
echo 44 > /tmp/target
if [ "$1" = "afl" ]; then
    . /usr/local/sbin/eafl
    shift
else
    . /usr/local/sbin/e
fi
export PROJECT_NAME=libtiff
export SANITIZER=$1
[ -z "$SANITIZER" ] && export SANITIZER='none'
cd $SRC

#apt-get update && apt-get install -y make autoconf automake libtool cmake nasm
#git clone --depth 1 https://gitlab.com/libtiff/libtiff
#git clone --depth 1 https://github.com/madler/zlib
#git clone --depth 1 https://github.com/libjpeg-turbo/libjpeg-turbo
#git clone https://www.cl.cam.ac.uk/~mgk25/git/jbigkit

#wget https://lcamtuf.coredump.cx/afl/demo/afl_testcases.tgz
#wget https://raw.githubusercontent.com/google/AFL/debe27037b9444bbf090a0ffbd5d24889bb887ae/dictionaries/tiff.dict


cp -r /downloads/libtiff $SRC
cp -r /downloads/zlib $SRC
cp -r /downloads/libjpeg-turbo $SRC
cp -r /downloads/jbigkit $SRC
cp -r /downloads/afl-testcases $SRC
cp -r /downloads/tiff.dict $SRC

cp /opt/oss-fuzz/projects/$PROJECT_NAME/build.sh $SRC/

cd $SRC/$PROJECT_NAME
mkdir -p /home/hacker/.log
[ ! "$SANITIZER" = "introspector" ] && [ ! "$SANITIZER" = "coverage" ] && zip -ry /home/hacker/.log/$(TZ=US/Arizona date +"%F--%H-%M-%S")-$PROJECT_NAME /home/hacker/$PROJECT_NAME
compile
drivers
