#!/bin/bash
DRIVERS=('opj_decompress_fuzzer_J2K' 'opj_decompress_fuzzer_JP2')
export PROJECT_NAME='openjpeg' 

. /usr/local/sbin/e.sh
export SANITIZER='none'
/challenge/build-image

parallel run_fuzzer ::: ${DRIVERS[@]} ::: -max_total_time=10

cd $SRC
rm -rf /src/openjpeg
git clone --depth 1 https://github.com/uclouvain/openjpeg $SRC/openjpeg
cp /opt/oss-fuzz/projects/openjpeg/build.sh $SRC/
cd $SRC/openjpeg
export SANITIZER='coverage'
compile

for driver in "${DRIVERS[@]}"
do
    rm -rf /corpus/$driver
    mv /tmp/${driver}_corpus /corpus/$driver
done

coverage
echo
for driver in "${DRIVERS[@]}"
do
    echo $driver
    /usr/local/sbin/loc.py $PROJECT_NAME $driver
    echo
done
