#!/opt/pwn.college/bash
echo 25 > /tmp/initial
echo 30 > /tmp/target
if [ "$1" = "afl" ]; then
    . /usr/local/sbin/eafl
    shift
else
    . /usr/local/sbin/e
fi
export PROJECT_NAME=mosquitto
export SANITIZER=$1
[ -z "$SANITIZER" ] && export SANITIZER='none'
cd $SRC

rm -rf $SRC/$PROJECT_NAME
git clone --depth 1 -b develop https://github.com/eclipse/mosquitto $SRC/mosquitto

# Get dependencies
#$SRC/mosquitto/fuzzing/scripts/oss-fuzz-dependencies.sh
#apt-get update && apt-get install -y libtool-bin make libsqlite3-dev
git clone https://github.com/DaveGamble/cJSON $SRC/cJSON


cp /opt/oss-fuzz/projects/$PROJECT_NAME/build.sh $SRC/

patch -tuN $SRC/mosquitto/fuzzing/broker/Makefile -i /challenge/.Makefile.patch -r -
cd $SRC/$PROJECT_NAME
if [ ! -d "/home/hacker/$PROJECT_NAME" ]; then
   mkdir /home/hacker/$PROJECT_NAME
   cp $SRC/$PROJECT_NAME/fuzzing/broker/broker_fuzz_read_handle.cpp $SRC/$PROJECT_NAME/fuzzing/broker/new_fuzzer.cpp
   cp $SRC/$PROJECT_NAME/fuzzing/broker/*.cpp /home/hacker/$PROJECT_NAME
   cp $SRC/$PROJECT_NAME/fuzzing/broker/*.h /home/hacker/$PROJECT_NAME
   cp $SRC/$PROJECT_NAME/fuzzing/broker/Makefile /home/hacker/$PROJECT_NAME
   cp $SRC/build.sh /home/hacker/$PROJECT_NAME
   chown -R hacker /home/hacker/$PROJECT_NAME
else
   cp /home/hacker/$PROJECT_NAME/*.cpp $SRC/$PROJECT_NAME/fuzzing/broker
   cp /home/hacker/$PROJECT_NAME/*.h $SRC/$PROJECT_NAME/fuzzing/broker
   cp /home/hacker/$PROJECT_NAME/Makefile $SRC/$PROJECT_NAME/fuzzing/broker
   cp /home/hacker/$PROJECT_NAME/build.sh $SRC
fi
mkdir -p /home/hacker/.log
[ ! "$SANITIZER" = "introspector" ] && [ ! "$SANITIZER" = "coverage" ] && zip -ry /home/hacker/.log/$(TZ=US/Arizona date +"%F--%H-%M-%S")-$PROJECT_NAME /home/hacker/$PROJECT_NAME
sudo --preserve-env compile
drivers
