#!/opt/pwn.college/bash
if [ "$1" = "afl" ]; then
    . /usr/local/sbin/eafl
    shift
else
    . /usr/local/sbin/e
fi
export PROJECT_NAME=mupdf
export SANITIZER=$1
[ -z "$SANITIZER" ] && export SANITIZER='none'

if [ ! -d "/src-orig" ]; then
    rm -rf $SRC/$PROJECT_NAME
    #apt-get update && apt-get install -y make libtool pkg-config

    #git clone --recursive --depth 1 git://git.ghostscript.com/mupdf.git mupdf
    #git clone --depth 1 https://github.com/mozilla/pdf.js pdf.js 
    cp -r /opt/fuzz-targets/mupdf $SRC
    cp -r /opt/fuzz-targets/pdf.js $SRC

    zip -q $SRC/pdf_fuzzer_seed_corpus.zip pdf.js/test/pdfs/*.pdf
    zip -q $SRC/new_fuzzer_seed_corpus.zip pdf.js/test/pdfs/*.pdf && rm -rf pdf.js
        
    #wget https://raw.githubusercontent.com/rc0r/afl-fuzz/master/dictionaries/pdf.dict
    cp /opt/fuzz-targets/pdf.dict $SRC
    cp pdf.dict new_fuzzer.dict
    mv pdf.dict pdf_fuzzer.dict

    cp /opt/oss-fuzz-new/projects/$PROJECT_NAME/build.sh $SRC/
    cp /opt/oss-fuzz-new/projects/$PROJECT_NAME/*.cc $SRC/
    cp /opt/oss-fuzz-new/projects/$PROJECT_NAME/pdf_fuzzer.options $SRC/
    cp /opt/oss-fuzz-new/projects/$PROJECT_NAME/pdf_fuzzer.options $SRC/new_fuzzer.options

    rm -rf /out$SRC
    cp -r $SRC /out
    patch -tuN $SRC/build.sh -i /challenge/.build.patch -r -
    echo Please wait, initial filecopy
    chown -hR hacker:hacker $SRC/$PROJECT_NAME
    mv /src /src-orig
fi
if [ ! -d "/src-$SANITIZER" ]; then
    echo Please wait, initial filecopy
    cp -r /src-orig /src-$SANITIZER
fi
mv /src-$SANITIZER /src

cd $SRC/$PROJECT_NAME
if [ ! -d "/home/hacker/fuzz-dojo/$PROJECT_NAME" ]; then
   mkdir -p /home/hacker/fuzz-dojo/$PROJECT_NAME
   cp $SRC/pdf_fuzzer.cc $SRC/new_fuzzer.cc
   cp $SRC/*.cc /home/hacker/fuzz-dojo/$PROJECT_NAME
   cp $SRC/build.sh /home/hacker/fuzz-dojo/$PROJECT_NAME
   chown -R hacker /home/hacker/fuzz-dojo/$PROJECT_NAME
else
   cp /home/hacker/fuzz-dojo/$PROJECT_NAME/*.cc $SRC
   cp /home/hacker/fuzz-dojo/$PROJECT_NAME/build.sh $SRC
fi
mkdir -p /home/hacker/.log
[ ! "$SANITIZER" = "introspector" ] && [ ! "$SANITIZER" = "coverage" ] && zip -ry /home/hacker/.log/$(TZ=US/Arizona date +"%F--%H-%M-%S")-$PROJECT_NAME /home/hacker/fuzz-dojo/$PROJECT_NAME
sudo --preserve-env compile
drivers
chown -hR hacker:hacker $SRC/$PROJECT_NAME
mv /src /src-$SANITIZER
