#!/opt/pwn.college/bash 
INITIAL=27
TARGET=31
sudo -H -u hacker bash -c /usr/local/sbin/loc_count
echo
echo Checking bzip2_decompress_target coverage: 
/usr/local/sbin/loc bzip2_decompress_target
/usr/local/sbin/announce $INITIAL $? 
if [ "$?" -gt "$TARGET" ]; then
    echo
    echo Congratulations!
    cat /flag
fi
