#!/opt/pwn.college/bash 
INITIAL=74
TARGET=79
time sudo -H -u hacker bash -c "/usr/local/sbin/loc_count $*"
/usr/local/sbin/announce $INITIAL $? 
if [ "$?" -gt "$TARGET" ]; then
    echo
    echo Congratulations!
    cat /flag
fi
if compgen -G "/out/crash*" > /dev/null; then
    echo
    echo "Crashes detected within the /out directory!"
    echo
fi
