#!/opt/pwn.college/bash
. /usr/local/sbin/e
export PROJECT_NAME=unrar
export SANITIZER=$1
[ -z "$SANITIZER" ] && export SANITIZER='none'
cd $SRC

#apt-get update && apt-get install -y make build-essential

#git clone -b oss_fuzz --depth 1 https://github.com/aawc/unrar.git
rm -rf  /src/unrar
cp -r /opt/fuzz-targets/unrar /src/

cp /opt/oss-fuzz/projects/$PROJECT_NAME/unrar_fuzzer.cc $SRC/$PROJECT_NAME 
cp /opt/oss-fuzz/projects/$PROJECT_NAME/build.sh $SRC/

chmod 755 /src/build.sh
patch -tuN /src/build.sh -i /challenge/.build.patch -r -
cd $SRC/$PROJECT_NAME
if [ ! -d "/home/hacker/$PROJECT_NAME" ]; then
   mkdir /home/hacker/$PROJECT_NAME
   cp $SRC/$PROJECT_NAME/unrar_fuzzer.cc $SRC/$PROJECT_NAME/new_fuzzer.cc
   cp $SRC/$PROJECT_NAME/*.cc /home/hacker/$PROJECT_NAME
   cp /src/build.sh /home/hacker/$PROJECT_NAME
   chown -R hacker /home/hacker/$PROJECT_NAME
else
   cp /home/hacker/$PROJECT_NAME/* $SRC/$PROJECT_NAME
   cp /home/hacker/$PROJECT_NAME/build.sh $SRC
fi
sudo --preserve-env compile
drivers