#!/opt/pwn.college/bash
export PROJECT_NAME=lua
sudo cp /usr/local/sbin/loc_count /usr/local/sbin/fi /challenge
sudo chmod 4755 /challenge/loc_count /challenge/fi
/challenge/loc_count
cd /src
rm -rf /src/testdir
git clone https://github.com/ligurio/lua-c-api-tests testdir
cd /src/testdir
git clone --depth 1 --jobs $(nproc) https://github.com/ligurio/lua-c-api-corpus corpus_dir
cp /opt/oss-fuzz/projects/testdir/build.sh /src
cp /opt/oss-fuzz/projects/testdir/build.sh /src/testdir
cp /opt/oss-fuzz/projects/testdir/fuzz_lua.c /src

patch -tuN /src/build.sh -i /challenge/build.patch -r -
patch -tuN /src/testdir/build/tests/CTestTestfile.cmake -i /challenge/CTest.patch -r -
patch -tuN /src/testdir/tests/CMakeLists.txt -i /challenge/CMakeLists.patch -r -

cd /src
/challenge/fi $PROJECT_NAME
