#!/bin/sh
. /usr/local/sbin/e
export PROJECT_NAME=php
export SANITIZER=$1
[ -z "$SANITIZER" ] && export SANITIZER='none'
cd $SRC
rm -rf php-src
# The current clang revision is broken, pin to older one.
#FROM gcr.io/oss-fuzz-base/base-builder@sha256:111d6b9d3a52bd3392602c71dc8936c628607a7a9bc86d381db7586f9b1e840f
#RUN apt-get update && apt-get install -y autoconf automake libtool bison re2c pkg-config
git clone --depth 1 --branch master https://github.com/php/php-src.git php-src

cp /opt/oss-fuzz/projects/$PROJECT_NAME/build.sh $SRC/

cd $SRC/php-src
if [ ! -d "/home/hacker/$PROJECT_NAME" ]; then
   mkdir /home/hacker/$PROJECT_NAME
   cp $SRC/php-src/sapi/fuzzer/fuzzer-execute.c $SRC/php-src/sapi/fuzzer/fuzzer-new.c
   cp $SRC/*.c /home/hacker/$PROJECT_NAME
   cp $SRC/*.php /home/hacker/$PROJECT_NAME
   cp $SRC/*.dict /home/hacker/$PROJECT_NAME
   cp /opt/oss-fuzz/projects/$PROJECT_NAME/build.sh /home/hacker/$PROJECT_NAME
else
   cp /home/hacker/$PROJECT_NAME/* $SRC
fi
#patch -tuN /src/build.sh -i /challenge/build.patch -r -
compile