#!/bin/sh
. /usr/local/sbin/e
export PROJECT_NAME=xvid
export SANITIZER=$1
[ -z "$SANITIZER" ] && export SANITIZER='none'
cd $SRC

rm -rf xvidcore-install
#apt-get update && apt-get install -y make autoconf automake libtool subversion
svn checkout http://svn.xvid.org/trunk --username anonymous --password "" --non-interactive --no-auth-cache
git clone --depth 1 https://github.com/guidovranken/fuzzing-headers.git
git clone --depth 1 https://github.com/guidovranken/oss-fuzz-fuzzers.git

cp /opt/oss-fuzz/projects/$PROJECT_NAME/build.sh $SRC/

cd $SRC
if [ ! -d "/home/hacker/$PROJECT_NAME" ]; then
   mkdir /home/hacker/$PROJECT_NAME
   cp $SRC/oss-fuzz-fuzzers/xvid/fuzzer.cpp $SRC/oss-fuzz-fuzzers/newfuzzer.cpp
   cp $SRC/*.c /home/hacker/$PROJECT_NAME
   cp $SRC/*.cc /home/hacker/$PROJECT_NAME
   cp /opt/oss-fuzz/projects/$PROJECT_NAME/build.sh /home/hacker/$PROJECT_NAME
else
   cp /home/hacker/$PROJECT_NAME/*.c $SRC
   cp /home/hacker/$PROJECT_NAME/*.cc $SRC
   cp /home/hacker/$PROJECT_NAME/build.sh $SRC
fi
#patch -tuN /src/build.sh -i /challenge/build.patch -r -
compile