#!/opt/pwn.college/bash
export PROJECT_NAME=xvid
sudo cp /usr/local/sbin/loc_count /usr/local/sbin/fi /challenge
sudo chmod 4755 /challenge/loc_count /challenge/fi
/challenge/loc_count
cd /src

rm -rf xvidcore-install
#apt-get update && apt-get install -y make autoconf automake libtool subversion
#svn checkout http://svn.xvid.org/trunk --username anonymous --password "" --non-interactive --no-auth-cache
#git clone --depth 1 https://github.com/guidovranken/fuzzing-headers.git
#git clone --depth 1 https://github.com/guidovranken/oss-fuzz-fuzzers.git

cp -r /opt/fuzz-targets/trunk /src/trunk
cp -r /opt/fuzz-targets/fuzzing-headers /src/fuzzing-headers
cp -r /opt/fuzz-targets/oss-fuzz-fuzzers /src/oss-fuzz-fuzzers

/challenge/fi $PROJECT_NAME
