#!/opt/pwn.college/bash
. /usr/local/sbin/eafl
export PROJECT_NAME=libdwarf
export SANITIZER=$1
[ -z "$SANITIZER" ] && export SANITIZER='none'
cd $SRC

apt-get -qq update && apt-get install -qq -y cmake make zlib1g-dev
git clone --depth=1 https://github.com/davea42/libdwarf-code $SRC/libdwarf
git clone --depth=1 https://github.com/davea42/libdwarf-binary-samples $SRC/libdwarf-binary-samples
 

cp /opt/oss-fuzz/projects/$PROJECT_NAME/build.sh $SRC/

#patch -tuN /src/build.sh -i /challenge/.build.patch -r -
cd $SRC/libdwarf

sudo --preserve-env compile
drivers
