#!/bin/sh
. /usr/local/sbin/e
export PROJECT_NAME=mruby
export SANITIZER=$1
[ -z "$SANITIZER" ] && export SANITIZER='none'
cd $SRC

rm -rf $SRC/mruby
rm -rf $SRC/mruby_seeds
rm -rf $SRC/libprotobuf-mutator
#apt-get update && apt-get install -y build-essential ruby bison ninja-build cmake zlib1g-dev libbz2-dev liblzma-dev
git clone --depth 1 https://github.com/mruby/mruby mruby
git clone --depth 1 https://github.com/bshastry/mruby_seeds.git mruby_seeds
git clone --depth 1 https://github.com/google/libprotobuf-mutator.git
mkdir LPM; \
  cd LPM; \
  cmake $SRC/libprotobuf-mutator -GNinja -DLIB_PROTO_MUTATOR_DOWNLOAD_PROTOBUF=ON -DLIB_PROTO_MUTATOR_TESTING=OFF -DCMAKE_BUILD_TYPE=Release; \
  ninja

cp /opt/oss-fuzz/projects/$PROJECT_NAME/build.sh $SRC/

cd $SRC
if [ ! -d "/home/hacker/$PROJECT_NAME" ]; then
   mkdir /home/hacker/$PROJECT_NAME
   cp $SRC/mruby/oss-fuzz/mruby_fuzzer.c $SRC/mruby/oss-fuzz/new_fuzzer.c
   cp $SRC/mruby/oss-fuzz/*.c /home/hacker/$PROJECT_NAME
   cp $SRC/mruby/oss-fuzz/*.cpp /home/hacker/$PROJECT_NAME
   cp $SRC/mruby/oss-fuzz/*.h /home/hacker/$PROJECT_NAME
   cp $SRC/mruby/oss-fuzz/*.proto /home/hacker/$PROJECT_NAME
   cp /opt/oss-fuzz/projects/$PROJECT_NAME/build.sh /home/hacker/$PROJECT_NAME
else
   cp /home/hacker/$PROJECT_NAME/* $SRC
fi
#patch -tuN /src/build.sh -i /challenge/build.patch -r -
compile