#!/opt/pwn.college/bash
export PROJECT_NAME=mruby
sudo cp /usr/local/sbin/loc_count /usr/local/sbin/fi /challenge
sudo chmod 4755 /challenge/loc_count /challenge/fi
/challenge/loc_count
cd /src
rm -rf /src/mruby
rm -rf /src/mruby_seeds
rm -rf /src/libprotobuf-mutator
#apt-get update && apt-get install -y build-essential ruby bison ninja-build cmake zlib1g-dev libbz2-dev liblzma-dev
#git clone --depth 1 https://github.com/mruby/mruby mruby
#git clone --depth 1 https://github.com/bshastry/mruby_seeds.git mruby_seeds
#git clone --depth 1 https://github.com/google/libprotobuf-mutator.git

cp -r /opt/fuzz-targets/mruby /src/mruby
cp -r /opt/fuzz-targets/mruby_seeds /src/mruby_seeds
cp -r /opt/fuzz-targets/libprotobuf-mutator /src/libprotobuf-mutator

mkdir LPM; \
  cd LPM; \
  cmake /src/libprotobuf-mutator -GNinja -DLIB_PROTO_MUTATOR_DOWNLOAD_PROTOBUF=ON -DLIB_PROTO_MUTATOR_TESTING=OFF -DCMAKE_BUILD_TYPE=Release; \
  ninja

cd /src

cp /src/mruby/oss-fuzz/config/mruby.dict /src/mruby/oss-fuzz/config/new.dict
cp /src/mruby/oss-fuzz/config/mruby_fuzzer.options /src/mruby/oss-fuzz/config/new_fuzzer.options
   
cp /home/hacker/$PROJECT_NAME/*.c /src/mruby/oss-fuzz
cp /home/hacker/$PROJECT_NAME/*.cpp /src/mruby/oss-fuzz
cp /home/hacker/$PROJECT_NAME/*.h /src/mruby/oss-fuzz
cp /home/hacker/$PROJECT_NAME/*.proto /src/mruby/oss-fuzz
/challenge/fi $PROJECT_NAME
