#!/bin/sh
. /usr/local/sbin/e
export PROJECT_NAME=CMake
export SANITIZER=$1
[ -z "$SANITIZER" ] && export SANITIZER='none'
cd $SRC

#apt-get update && apt-get install -y make autoconf automake libtool pkg-config libssl-dev
git clone --depth 1 https://gitlab.kitware.com/cmake/cmake.git $PROJECT_NAME
git clone --depth 1 https://github.com/strongcourage/fuzzing-corpus

# This is to fix Fuzz Introspector build by using LLVM old pass manager
# re https://github.com/ossf/fuzz-introspector/issues/305
export OLD_LLVMPASS=1

cp /opt/oss-fuzz/projects/cmake/build.sh $SRC/

cd $SRC/$PROJECT_NAME
if [ ! -d "/home/hacker/$PROJECT_NAME" ]; then
   mkdir /home/hacker/$PROJECT_NAME
   cp $SRC/$PROJECT_NAME/Tests/Fuzzing/xml_parser_fuzzer.cc $SRC/$PROJECT_NAME/Tests/Fuzzing/newfuzzer.c
   cp $SRC/$PROJECT_NAME/Tests/Fuzzing/*.cc /home/hacker/$PROJECT_NAME
   cp /opt/oss-fuzz/projects/cmake/build.sh /home/hacker/$PROJECT_NAME
else
   cp /home/hacker/$PROJECT_NAME/*.cc $SRC/$PROJECT_NAME/Tests/Fuzzing
   cp /home/hacker/$PROJECT_NAME/build.sh $SRC
fi
#patch -tuN /src/build.sh -i /challenge/build.patch -r -
compile