#!/bin/bash
export PROJECT_NAME=CMake
/usr/local/sbin/loc_count
cd /src
rm -rf $PROJECT_NAME
#apt-get update && apt-get install -y make autoconf automake libtool pkg-config libssl-dev
git clone --depth 1 https://gitlab.kitware.com/cmake/cmake.git $PROJECT_NAME
cd /src/$PROJECT_NAME
/usr/local/sbin/fi $PROJECT_NAME
