#!/bin/bash
export PROJECT_NAME=file
sudo cp /usr/local/sbin/loc_count /usr/local/sbin/fi /challenge
sudo chmod 4755 /challenge/loc_count /challenge/fi
/challenge/loc_count
cd /src

rm -rf $PROJECT_NAME
rm -rf binary-samples
rm -rf pocs

git clone --depth 1 https://github.com/file/file.git

# Supplement file's existing test files
git clone --depth 1 https://github.com/DavidKorczynski/binary-samples.git
git clone --depth 1 https://github.com/corkami/pocs


cd /src/$PROJECT_NAME
/challenge/fi $PROJECT_NAME
