#!/bin/bash
export PROJECT_NAME=sqlite3
sudo cp /usr/local/sbin/loc_count /usr/local/sbin/fi /challenge
sudo chmod 4755 /challenge/loc_count /challenge/fi
/challenge/loc_count
cd /src
rm -rf $PROJECT_NAME
#apt-get update && apt-get install -y make autoconf automake libtool curl tcl zlib1g-dev

# We won't be able to poll fossil for changes, so this will build
# only once a day.
mkdir /src/sqlite3 && \
    cd /src/sqlite3 && \
    curl 'https://www.sqlite.org/src/tarball?uuid=trunk' -o sqlite3.tar.gz && \
    tar xzf sqlite3.tar.gz

cd /src
find /src/sqlite3 -name "*.test" | xargs zip /src/ossfuzz_seed_corpus.zip

cd /src/$PROJECT_NAME
/challenge/fi $PROJECT_NAME
