#!/opt/pwn.college/bash
if [ "$1" = "afl" ]; then
    . /usr/local/sbin/eafl
    shift
    export LABEL=$1$FUZZING_ENGINE
else
    . /usr/local/sbin/e
    export LABEL=$1
fi
export PROJECT_NAME=minizip
export SANITIZER=$1
if [ -z "$SANITIZER" ]; then
    export SANITIZER='none'
    export LABEL='none'$LABEL
fi

if [ ! -d "/src-orig" ]; then
    #apt-get update && apt-get install -y make cmake pkg-config libssl-dev:i386
    #git clone -b develop https://github.com/zlib-ng/minizip-ng minizip
    cp -r /downloads/minizip $SRC

    cp /opt/oss-fuzz/projects/$PROJECT_NAME/build.sh $SRC/
    build-cleanup
fi
build-srcfolders
mv /src-$LABEL /src

cd $SRC/$PROJECT_NAME
if [ ! -d "/home/hacker/fuzz-dojo/training-change" ]; then
   mkdir -p /home/hacker/fuzz-dojo/training-change
   cp $SRC/$PROJECT_NAME/test/fuzz/unzip_fuzzer.c $SRC/$PROJECT_NAME/test/fuzz/new_fuzzer.c
   cp $SRC/$PROJECT_NAME/test/fuzz/*.c /home/hacker/fuzz-dojo/training-change
   cp /opt/oss-fuzz/projects/$PROJECT_NAME/build.sh /home/hacker/fuzz-dojo/training-change
   chown -R hacker /home/hacker/fuzz-dojo/training-change
else
   cp /home/hacker/fuzz-dojo/training-change/*.c $SRC/$PROJECT_NAME/test/fuzz
   cp /home/hacker/fuzz-dojo/training-change/build.sh $SRC
fi
patch -tuN $SRC/minizip/CMakeLists.txt -i /challenge/.CMakeLists.patch -r -
mkdir -p /home/hacker/.log
[ ! "$SANITIZER" = "introspector" ] && [ ! "$SANITIZER" = "coverage" ] && zip -ry /home/hacker/.log/$(TZ=US/Arizona date +"%F--%H-%M-%S")-training-change /home/hacker/fuzz-dojo/training-change
compile
drivers
find $SRC -not -user hacker -print | xargs -n 100 -P 8 chown hacker:hacker /home/hacker/fuzz-dojo /home/hacker/.log /out
mv /src /src-$LABEL
