#!/opt/pwn.college/bash
if [ "$1" = "afl" ]; then
    . /usr/local/sbin/eafl
    shift
else
    . /usr/local/sbin/e
fi
export PROJECT_NAME=valijson
export SANITIZER=$1
[ -z "$SANITIZER" ] && export SANITIZER='none'

if [ ! -d "/src-orig" ]; then
    #apt-get update && apt-get install -y make autoconf automake libtool pkg-config cmake libcurlpp-dev libcurl4-openssl-dev

    rm -rf $PROJECT_NAME
    #git clone --depth 1 https://github.com/tristanpenman/valijson
    cp -r /opt/fuzz-targets/valijson $SRC

    cp $SRC/$PROJECT_NAME/tests/fuzzing/oss-fuzz-build.sh $SRC/build.sh
    # This is to fix Fuzz Introspector build by using LLVM old pass manager
    # re https://github.com/ossf/fuzz-introspector/issues/305
    export OLD_LLVMPASS=1

    patch -tuN $SRC/build.sh -i /challenge/.build.patch -r -
    patch -tuN $SRC/build.sh -i /challenge/.build2.patch -r -
    echo Please wait, initial setup
    chown -hR hacker:hacker $SRC/$PROJECT_NAME
    mv /src /src-orig
fi
if [ ! -d "/src-$SANITIZER" ]; then
    echo Please wait, initial setup
    cp -r /src-orig /src-$SANITIZER
fi
mv /src-$SANITIZER /src

cd $SRC/$PROJECT_NAME
if [ ! -d "/home/hacker/fuzz-dojo/$PROJECT_NAME" ]; then
   mkdir -p /home/hacker/fuzz-dojo/$PROJECT_NAME
   cp $SRC/$PROJECT_NAME/tests/fuzzing/fuzzer.cpp $SRC/$PROJECT_NAME/tests/fuzzing/newfuzzer.cpp
   cp $SRC/$PROJECT_NAME/tests/fuzzing/*.cpp /home/hacker/fuzz-dojo/$PROJECT_NAME
   cp $SRC/$PROJECT_NAME/tests/fuzzing/*.sh /home/hacker/fuzz-dojo/$PROJECT_NAME
   cp $SRC/build.sh /home/hacker/fuzz-dojo/$PROJECT_NAME
   chown -R hacker /home/hacker/fuzz-dojo/$PROJECT_NAME
else
   cp /home/hacker/fuzz-dojo/$PROJECT_NAME/* $SRC/$PROJECT_NAME/tests/fuzzing
   cp /home/hacker/fuzz-dojo/$PROJECT_NAME/build.sh $SRC
fi
mkdir -p /home/hacker/.log
[ ! "$SANITIZER" = "introspector" ] && [ ! "$SANITIZER" = "coverage" ] && zip -ry /home/hacker/.log/$(TZ=US/Arizona date +"%F--%H-%M-%S")-$PROJECT_NAME /home/hacker/fuzz-dojo/$PROJECT_NAME
sudo --preserve-env compile
drivers
chown -hR hacker:hacker $SRC/$PROJECT_NAME
mv /src /src-$SANITIZER