#!/opt/pwn.college/bash
. /usr/local/sbin/eafl
export PROJECT_NAME=libxml2
export SANITIZER=$1
[ -z "$SANITIZER" ] && export SANITIZER='none'
cd $SRC

apt-get update && \
    apt-get install -y --no-install-recommends \
        make autoconf libtool pkg-config \
        zlib1g-dev zlib1g-dev:i386 liblzma-dev liblzma-dev:i386
# Build requires automake 1.16.3
curl -LO http://mirrors.kernel.org/ubuntu/pool/main/a/automake-1.16/automake_1.16.5-1.3_all.deb && \
    apt install ./automake_1.16.5-1.3_all.deb
git clone --depth 1 https://gitlab.gnome.org/GNOME/libxml2.git


cp /opt/oss-fuzz/projects/$PROJECT_NAME/build.sh $SRC/

cd $SRC/libxml2
sudo --preserve-env compile
drivers
