#!/opt/pwn.college/bash
echo 49 > /tmp/initial
echo 54 > /tmp/target
if [ "$1" = "afl" ]; then
    . /usr/local/sbin/eafl
    shift
else
    . /usr/local/sbin/e
fi
export PROJECT_NAME=yara
export SANITIZER=$1
[ -z "$SANITIZER" ] && export SANITIZER='none'
cd $SRC

#apt-get update && apt-get install -y \
#  automake \
#  autoconf \
#  make \
#  libtool \
#  pkg-config \
#  bison \
#  flex

#git clone --depth 1 https://github.com/VirusTotal/yara.git
cp -r /opt/fuzz-targets/yara $SRC

cp /opt/oss-fuzz/projects/$PROJECT_NAME/build.sh $SRC/

#patch -tuN $SRC/build.sh -i /challenge/.build.patch -r -
cd $SRC/$PROJECT_NAME
if [ ! -d "/home/hacker/$PROJECT_NAME" ]; then
   mkdir /home/hacker/$PROJECT_NAME
   cp $SRC/$PROJECT_NAME/tests/oss-fuzz/rules_fuzzer.cc $SRC/$PROJECT_NAME/tests/oss-fuzz/newfuzzer.cc
   cp $SRC/$PROJECT_NAME/tests/oss-fuzz/*.cc /home/hacker/$PROJECT_NAME
   cp $SRC/build.sh /home/hacker/$PROJECT_NAME
   chown -R hacker /home/hacker/$PROJECT_NAME
else
   cp /home/hacker/$PROJECT_NAME/*.cc $SRC/$PROJECT_NAME/tests/oss-fuzz
   cp /home/hacker/$PROJECT_NAME/build.sh $SRC
fi

mkdir -p /home/hacker/.log
[ ! "$SANITIZER" = "introspector" ] && [ ! "$SANITIZER" = "coverage" ] && zip -ry /home/hacker/.log/$(TZ=US/Arizona date +"%F--%H-%M-%S")-$PROJECT_NAME /home/hacker/$PROJECT_NAME
sudo --preserve-env compile
drivers
