#!/opt/pwn.college/bash
. /usr/local/sbin/e
export PROJECT_NAME=cppcheck
export SANITIZER=$1
[ -z "$SANITIZER" ] && export SANITIZER='none'
cd $SRC

rm -rf $SRC/$PROJECT_NAME
#git clone https://github.com/danmar/cppcheck.git
cp -r /opt/fuzz-targets/cppcheck /src/cppcheck

# This is to fix Fuzz Introspector build by using LLVM old pass manager
# re https://github.com/ossf/fuzz-introspector/issues/305
export OLD_LLVMPASS=1

cp /opt/oss-fuzz/projects/$PROJECT_NAME/build.sh $SRC

patch -tuN $SRC/build.sh -i /challenge/build.patch -r -
patch -tuN $SRC/$PROJECT_NAME/oss-fuzz/Makefile -i /challenge/Makefile.patch -r -

cd $SRC/$PROJECT_NAME
if [ ! -d "/home/hacker/$PROJECT_NAME" ]; then
   mkdir /home/hacker/$PROJECT_NAME
   cp $SRC/$PROJECT_NAME/oss-fuzz/main.cpp $SRC/$PROJECT_NAME/oss-fuzz/newfuzzer.cpp
   cp $SRC/$PROJECT_NAME/oss-fuzz/*.cpp /home/hacker/$PROJECT_NAME
   cp $SRC/$PROJECT_NAME/oss-fuzz/*.h /home/hacker/$PROJECT_NAME
   cp $SRC/$PROJECT_NAME/oss-fuzz/Makefile /home/hacker/$PROJECT_NAME
   cp $SRC/build.sh /home/hacker/$PROJECT_NAME
   chown -R hacker /home/hacker/$PROJECT_NAME
else
   cp /home/hacker/$PROJECT_NAME/*.cpp $SRC/$PROJECT_NAME/oss-fuzz
   cp /home/hacker/$PROJECT_NAME/*.h $SRC/$PROJECT_NAME/oss-fuzz
   cp /home/hacker/$PROJECT_NAME/Makefile $SRC/$PROJECT_NAME/oss-fuzz
   cp /home/hacker/$PROJECT_NAME/build.sh $SRC
fi
sudo --preserve-env compile
