#!/opt/pwn.college/bash
export PROJECT_NAME=exiv2
/challenge/.loc_count
cd /src

cp -r /opt/fuzz-targets/exiv2 /src

cp /opt/oss-fuzz/projects/$PROJECT_NAME/build.sh /src/

patch -tuN /src/$PROJECT_NAME/fuzz/build.sh -i /challenge/.build.patch -r -
patch -tuN /src/$PROJECT_NAME/fuzz/CMakeLists.txt -i /challenge/.CMakeLists.patch -r -

cd /src/$PROJECT_NAME
cp /home/hacker/$PROJECT_NAME/*.cpp /src/$PROJECT_NAME/fuzz
cp /home/hacker/$PROJECT_NAME/build.sh /src
/challenge/.fi $PROJECT_NAME
