#!/opt/pwn.college/bash
export PROJECT_NAME=exiv2
/challenge/.loc_count
cd /src

rm -rf /src/$PROJECT_NAME
cp -r /opt/fuzz-targets/exiv2 /src

patch -tuN /src/$PROJECT_NAME/fuzz/CMakeLists.txt -i /challenge/.CMakeLists.patch -r -
cp /home/hacker/$PROJECT_NAME/*.cpp /src/$PROJECT_NAME/fuzz

cd /src/$PROJECT_NAME
/challenge/.fi $PROJECT_NAME
