#!/opt/pwn.college/bash
export PROJECT_NAME=example
/challenge/.loc_count
cd /src/$PROJECT_NAME
cp /home/hacker/$PROJECT_NAME/* /src/$PROJECT_NAME/projects/example/my-api-repo
/challenge/.fi $PROJECT_NAME
