#!/opt/pwn.college/bash
. /usr/local/sbin/eafl
export PROJECT_NAME=lame
export SANITIZER=$1
[ -z "$SANITIZER" ] && export SANITIZER='none'
cd $SRC

#apt-get update && apt-get install -y make autoconf automake libtool subversion pkg-config wget

rm -rf lame
rm -rf LAME-fuzzers
rm -rf mpg123

# ubuntu apt has not recent enough mpg123
#wget https://www.mpg123.de/snapshot
cp /opt/fuzz-targets/snapshot/* /src
tar -xvf snapshot
mv mpg123* mpg123

#git clone --depth 1 https://github.com/guidovranken/LAME-fuzzers
cp -r /opt/fuzz-targets/LAME-fuzzers /src/LAME-fuzzers

#svn checkout https://svn.code.sf.net/p/lame/svn/trunk/lame $SRC/lame
cp -r /opt/fuzz-targets/lame /src/lame

# This is to fix Fuzz Introspector build by using LLVM old pass manager
# re https://github.com/ossf/fuzz-introspector/issues/305
export OLD_LLVMPASS=1

cp /opt/oss-fuzz/projects/$PROJECT_NAME/build.sh $SRC/

patch -tuN /src/build.sh -i /challenge/.build.patch -r -
cd $SRC/
if [ ! -d "/home/hacker/$PROJECT_NAME" ]; then
   mkdir /home/hacker/$PROJECT_NAME
   cp $SRC/LAME-fuzzers/fuzzer-encoder.cpp $SRC/LAME-fuzzers/fuzzer-new.cpp
   cp $SRC/LAME-fuzzers/fuzzer-encoder.dict $SRC/LAME-fuzzers/fuzzer-new.dict
   cp $SRC/LAME-fuzzers/fuzzer-encoder_seed_corpus.zip $SRC/LAME-fuzzers/fuzzer-new_seed_corpus.zip
   cp $SRC/LAME-fuzzers/* /home/hacker/$PROJECT_NAME
   cp /src/build.sh /home/hacker/$PROJECT_NAME
   chown -R hacker /home/hacker/$PROJECT_NAME
else
   cp /home/hacker/$PROJECT_NAME/*.cpp $SRC/LAME-fuzzers
   cp /home/hacker/$PROJECT_NAME/*.dict $SRC/LAME-fuzzers
   cp /home/hacker/$PROJECT_NAME/*.zip $SRC/LAME-fuzzers
   cp /home/hacker/$PROJECT_NAME/build.sh $SRC
fi
sudo --preserve-env compile