#!/opt/pwn.college/bash 
export PROJECT_NAME=avahi
/challenge/.loc_count
cd /src/$PROJECT_NAME
cp /home/hacker/$PROJECT_NAME/*.c /src/$PROJECT_NAME/fuzz
patch -tuN /src/avahi/fuzz/oss-fuzz.sh -i /challenge/.oss-fuzz.patch -r -
/challenge/.fi $PROJECT_NAME
