#!/opt/pwn.college/bash
. /usr/local/sbin/e
export LABEL=$1
export PROJECT_NAME=zopfli
export SANITIZER=$1
if [ -z "$SANITIZER" ]; then
    export SANITIZER='none'
    export LABEL='none'$LABEL
fi

if [ ! -d "/src-orig" ]; then
    rm -rf $SRC/zopfli
    #apt-get update && apt-get install -y make autoconf automake libtool
    #git clone --depth 1 https://github.com/google/zopfli
    cp -r /downloads/zopfli $SRC

    cp /opt/oss-fuzz-new/projects/$PROJECT_NAME/*.cc $SRC/

    cp $SRC/zopfli_compress_fuzzer.cc $SRC/new_fuzzer.cc
    #patch -tuN $SRC/build.sh -i /challenge/.build.patch -r -
    cp /opt/oss-fuzz-new/projects/$PROJECT_NAME/build.sh $SRC/
    echo Please wait, creating /src-orig
    find $SRC -not -user hacker -print | sudo xargs -n 100 -P 8 chown hacker:hacker
    mv /src /src-orig
fi
if [ ! -d "/src-$LABEL" ]; then
    echo Please wait, creating /src-$LABEL
    cp -r /src-orig /src-$LABEL
fi
mv /src-$LABEL /src

cd $SRC/$PROJECT_NAME
if [ ! -d "/home/hacker/fuzz-dojo/$PROJECT_NAME" ]; then
   mkdir -p /home/hacker/fuzz-dojo/$PROJECT_NAME
   cp $SRC/*.cc /home/hacker/fuzz-dojo/$PROJECT_NAME
   cp $SRC/build.sh /home/hacker/fuzz-dojo/$PROJECT_NAME
   chown -R hacker /home/hacker/fuzz-dojo/$PROJECT_NAME
else
   cp /home/hacker/fuzz-dojo/$PROJECT_NAME/*.cc $SRC
   cp /home/hacker/fuzz-dojo/$PROJECT_NAME/build.sh $SRC
fi
fuzzlog
compile
drivers
mv /src /src-$LABEL
