#!/opt/pwn.college/bash
. /usr/local/sbin/e
if [ "$?" -gt 0 ]; then
    exit 1
fi
export LABEL=$1
export PROJECT_NAME=apache-httpd
export SANITIZER=$1
if [ -z "$SANITIZER" ]; then
    export SANITIZER='none'
    export LABEL='none'$LABEL
fi

if [ ! -d "/src-orig" ]; then
#----------------------------------------------------------------------
    #apt-get update && apt-get install -y make autoconf automake libtool wget uuid-dev pkg-config libtool-bin libbsd-dev

    #git clone https://github.com/PCRE2Project/pcre2 pcre2 && \
        #cd pcre2 && ./autogen.sh && ./configure && make && make install

    #git clone https://github.com/AdaLogics/fuzz-headers
    cp -r /downloads/fuzz-headers $SRC
    cp -r /downloads/pcre2 $SRC/pcre2
    cd $SRC/pcre2
        ./autogen.sh 
        ./configure
        make
        make install 
    cd $SRC

    #wget https://github.com/libexpat/libexpat/releases/download/R_2_4_1/expat-2.4.1.tar.gz && \
    # tar -xf expat-2.4.1.tar.gz && cd expat-2.4.1 && ./configure && make && make install
        
    rm -rf $SRC/httpd
    #git clone --depth=1 https://github.com/apache/httpd
    cp -r /downloads/httpd $SRC

    cp /opt/oss-fuzz/projects/$PROJECT_NAME/fuzz_*.c $SRC/
    cp /opt/oss-fuzz/projects/$PROJECT_NAME/build.sh $SRC/

    cd /
    cp $SRC/fuzz_preq.c $SRC/fuzz_new.c
    patch -tuN $SRC/build.sh -i /challenge/.build.patch -r -
#----------------------------------------------------------------------
    build-cleanup
fi
build-srcfolders
mv /src-$LABEL /src

cd $SRC/httpd
#----------------------------------------------------------------------
if [ ! -d "/home/hacker/fuzz-dojo/$PROJECT_NAME" ]; then
   mkdir -p /home/hacker/fuzz-dojo/$PROJECT_NAME
   cp $SRC/*.c /home/hacker/fuzz-dojo/$PROJECT_NAME
   cp $SRC/build.sh /home/hacker/fuzz-dojo/$PROJECT_NAME
else
   cp /home/hacker/fuzz-dojo/$PROJECT_NAME/*.c $SRC
   cp /home/hacker/fuzz-dojo/$PROJECT_NAME/build.sh $SRC
fi
#----------------------------------------------------------------------
if [ "$4" = "understanding" ]; then
    understanding $2 $3
elif [ "$4" = "planning" ]; then
    planning $2 $3
else
    fuzzlog
    compile
    drivers
fi
mv /src /src-$LABEL
