#!/bin/sh
. /usr/local/sbin/e
export PROJECT_NAME=lua
export SANITIZER=$1
[ -z "$SANITIZER" ] && export SANITIZER='none'
cd $SRC

rm -rf $SRC/testdir
git clone https://github.com/ligurio/lua-c-api-tests testdir
cd $SRC/testdir
git clone --depth 1 --jobs $(nproc) https://github.com/ligurio/lua-c-api-corpus corpus_dir
cp /opt/oss-fuzz/projects/$PROJECT_NAME/build.sh $SRC
cp /opt/oss-fuzz/projects/$PROJECT_NAME/build.sh $SRC/testdir
cp /opt/oss-fuzz/projects/$PROJECT_NAME/fuzz_lua.c $SRC

patch -tuN $SRC/build.sh -i /challenge/build.patch -r -
patch -tuN /src/testdir/tests/fuzz -i /challenge/fuzz.patch -r -
cd $SRC
if [ ! -d "/home/hacker/$PROJECT_NAME" ]; then
   mkdir /home/hacker/$PROJECT_NAME
   cp $SRC/testdir/tests/luaL_loadbuffer_test.c $SRC/testdir/tests/newfuzzer.c
   cp $SRC/testdir/tests/*.c /home/hacker/$PROJECT_NAME
   cp $SRC/testdir/tests/*.cc /home/hacker/$PROJECT_NAME
   cp $SRC/testdir/tests/CMakeLists.txt /home/hacker/$PROJECT_NAME
   cp /src/testdir/tests/fuzz /home/hacker/$PROJECT_NAME
   cp /src/build.sh /home/hacker/$PROJECT_NAME
else
   cp /home/hacker/$PROJECT_NAME/*.c $SRC/testdir/tests
   cp /home/hacker/$PROJECT_NAME/*.cc $SRC/testdir/tests
   cp /home/hacker/$PROJECT_NAME/fuzz $SRC/testdir/tests
   cp /home/hacker/$PROJECT_NAME/CMakeLists.txt $SRC/testdir/tests
   cp /home/hacker/$PROJECT_NAME/build.sh $SRC
fi
compile
