#!/opt/pwn.college/bash
set -x
. /usr/local/sbin/e
export LABEL=$1
export PROJECT_NAME=avahi
export SANITIZER=$1
if [ -z "$SANITIZER" ]; then
    SANITIZER='none'
    LABEL='none'
fi

export SRC='/src-$LABEL'

cp /home/hacker/fuzz-dojo/$PROJECT_NAME/*.c $SRC/$PROJECT_NAME/fuzz
cp /home/hacker/fuzz-dojo/$PROJECT_NAME/build.sh $SRC

cd $SRC/$PROJECT_NAME/fuzz

clang++ -O1 -fno-omit-frame-pointer -gline-tables-only -DFUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION -fsanitize=fuzzer-no-link -stdlib=libc++ fuzz-newfuzzer.o -o /out/fuzz-newfuzzer -fsanitize=fuzzer avahi-core/.libs/libavahi-core.a avahi-common/.libs/libavahi-common.a

chown -hR hacker:hacker $SRC /home/hacker/fuzz-dojo /home/hacker/.log /out
