#!/opt/pwn.college/bash
if [ "$1" = "afl" ]; then
    . /usr/local/sbin/eafl
    shift
    export LABEL=$1$FUZZING_ENGINE
else
    . /usr/local/sbin/e
    export LABEL=$1
fi
export PROJECT_NAME=lame
export SANITIZER=$1
if [ -z "$SANITIZER" ]; then
    export SANITIZER='none'
    export LABEL='none'$LABEL
fi

if [ ! -d "/src-orig" ]; then
    #apt-get update && apt-get install -y make autoconf automake libtool subversion pkg-config wget
    cd $SRC
    rm -rf lame
    rm -rf LAME-fuzzers
    rm -rf mpg123

    # ubuntu apt has not recent enough mpg123
    #wget https://www.mpg123.de/snapshot
    cp /opt/fuzz-targets/snapshot/* $SRC
    tar -xvf snapshot
    mv mpg123* mpg123

    #git clone --depth 1 https://github.com/guidovranken/LAME-fuzzers
    cp -r /opt/fuzz-targets/LAME-fuzzers $SRC

    #svn checkout https://svn.code.sf.net/p/lame/svn/trunk/lame $SRC/lame
    cp -r /opt/fuzz-targets/lame $SRC

    # This is to fix Fuzz Introspector build by using LLVM old pass manager
    # re https://github.com/ossf/fuzz-introspector/issues/305
    export OLD_LLVMPASS=1

    cp /opt/oss-fuzz-new/projects/$PROJECT_NAME/build.sh $SRC/

    cp $SRC/LAME-fuzzers/fuzzer-encoder.cpp $SRC/LAME-fuzzers/fuzzer-new.cpp
    cp $SRC/LAME-fuzzers/fuzzer-encoder.dict $SRC/LAME-fuzzers/fuzzer-new.dict
    cp $SRC/LAME-fuzzers/fuzzer-encoder_seed_corpus.zip $SRC/LAME-fuzzers/fuzzer-new_seed_corpus.zip
    patch -tuN $SRC/build.sh -i /challenge/.build.patch -r -
    echo Please wait, creating /src-orig
    chown -hR hacker:hacker $SRC
    mv /src /src-orig
fi
if [ ! -d "/src-$LABEL" ]; then
    echo Please wait, creating /src-$LABEL
    cp -r /src-orig /src-$LABEL
fi
mv /src-$LABEL /src

cd $SRC/
if [ ! -d "/home/hacker/fuzz-dojo/$PROJECT_NAME" ]; then
   mkdir -p /home/hacker/fuzz-dojo/$PROJECT_NAME
   cp -r $SRC/LAME-fuzzers/* /home/hacker/fuzz-dojo/$PROJECT_NAME
   cp $SRC/build.sh /home/hacker/fuzz-dojo/$PROJECT_NAME
   chown -R hacker /home/hacker/fuzz-dojo/$PROJECT_NAME
else
   cp /home/hacker/fuzz-dojo/$PROJECT_NAME/*.cpp $SRC/LAME-fuzzers
   cp /home/hacker/fuzz-dojo/$PROJECT_NAME/*.dict $SRC/LAME-fuzzers
   cp /home/hacker/fuzz-dojo/$PROJECT_NAME/*.zip $SRC/LAME-fuzzers
   cp /home/hacker/fuzz-dojo/$PROJECT_NAME/build.sh $SRC
fi
mkdir -p /home/hacker/.log
[ ! "$SANITIZER" = "introspector" ] && [ ! "$SANITIZER" = "coverage" ] && zip -ry /home/hacker/.log/$(TZ=US/Arizona date +"%F--%H-%M-%S")-$PROJECT_NAME /home/hacker/fuzz-dojo/$PROJECT_NAME
compile
drivers
chown -hR hacker:hacker $SRC /home/hacker/fuzz-dojo /home/hacker/.log /out
mv /src /src-$LABEL