#!/opt/pwn.college/bash
export PROJECT_NAME=wasm3
sudo cp /usr/local/sbin/loc_count /usr/local/sbin/fi /challenge
sudo chmod 4755 /challenge/loc_count /challenge/fi
/challenge/loc_count
cd /src

rm -rf $PROJECT_NAME
#apt-get update && apt-get install -y make
#git clone --depth 1 https://github.com/wasm3/wasm3
cp -r /opt/fuzz-targets/wasm3 /src/wasm3

cd $SRC/$PROJECT_NAME
/challenge/fi $PROJECT_NAME
