#!/bin/bash
export PROJECT_NAME=boost
/usr/local/sbin/loc_count
cd /src
rm -rf /src/$PROJECT_NAME
#apt-get update && apt-get install -y g++ python
git clone --recursive https://github.com/boostorg/boost.git
# This is to fix Fuzz Introspector build by using LLVM old pass manager
# re https://github.com/ossf/fuzz-introspector/issues/305
export OLD_LLVMPASS=1

cd /src/$PROJECT_NAME
/usr/local/sbin/fi $PROJECT_NAME
