#!/bin/sh
. /usr/local/sbin/e
export PROJECT_NAME=mosquitto
export SANITIZER=$1
[ -z "$SANITIZER" ] && export SANITIZER='none'
cd $SRC

rm -rf $SRC/$PROJECT_NAME
git clone --depth 1 -b develop https://github.com/eclipse/mosquitto $SRC/mosquitto

# Get dependencies
#$SRC/mosquitto/fuzzing/scripts/oss-fuzz-dependencies.sh
#apt-get update && apt-get install -y libtool-bin make libsqlite3-dev
git clone https://github.com/DaveGamble/cJSON $SRC/cJSON


cp /opt/oss-fuzz/projects/$PROJECT_NAME/build.sh $SRC/

#patch -tuN /src/snappy/CMakeLists.txt -i /challenge/CMakeLists.patch -r -
cd $SRC/$PROJECT_NAME
if [ ! -d "/home/hacker/$PROJECT_NAME" ]; then
   mkdir /home/hacker/$PROJECT_NAME
   cp $SRC/$PROJECT_NAME/snappy_compress_fuzzer.cc $SRC/$PROJECT_NAME/new_fuzzer.cc
   cp $SRC/$PROJECT_NAME/*.cc /home/hacker/$PROJECT_NAME
   cp /src/build.sh /home/hacker/$PROJECT_NAME
else
   cp /home/hacker/$PROJECT_NAME/*.cc $SRC/$PROJECT_NAME
   cp /home/hacker/$PROJECT_NAME/build.sh $SRC
fi
compile
