#!/opt/pwn.college/bash
. /usr/local/sbin/eafl
export PROJECT_NAME=cyclonedds
export SANITIZER=$1
[ -z "$SANITIZER" ] && export SANITIZER='none'
cd $SRC

apt-get update && apt install -y \
    autoconf \
    automake \
    libssl-dev \
    libcunit1 \
    libcunit1-dev \
    bison \
    libbison-dev

git clone --depth 1 https://github.com/eclipse-cyclonedds/cyclonedds

# This is to fix Fuzz Introspector build by using LLVM old pass manager
# re https://github.com/ossf/fuzz-introspector/issues/305
export OLD_LLVMPASS=1

cp /opt/oss-fuzz/projects/$PROJECT_NAME/build.sh $SRC/

cd $SRC/cyclonedds
sudo --preserve-env compile
drivers
