#!/opt/pwn.college/bash
. /usr/local/sbin/e
LABEL=$1
PROJECT_NAME=casync
SANITIZER=$1
if [ -z "$SANITIZER" ]; then
    SANITIZER='none'
    LABEL='none'
fi

SRC=/src-$LABEL

if [ "$LABEL" = "none" ]; then
    FLAGS=""
elif [ "$LABEL" = "address" ]; then
    FLAGS=$SANITIZER_FLAGS_address
elif [ "$LABEL" = "memory" ]; then
    FLAGS=$SANITIZER_FLAGS_memory
elif [ "$LABEL" = "undefined" ]; then
    FLAGS=$SANITIZER_FLAGS_undefined
elif [ "$LABEL" = "thread" ]; then
    FLAGS=$SANITIZER_FLAGS_thread
fi
set -ex


cp /home/hacker/fuzz-dojo/$PROJECT_NAME/*.c $SRC/casync/test/fuzz
cp /home/hacker/fuzz-dojo/$PROJECT_NAME/*.h $SRC/casync/test/fuzz
cp /home/hacker/fuzz-dojo/$PROJECT_NAME/*.build $SRC/casync/test/fuzz

mv $SRC /src
cd /src/$PROJECT_NAME/

ninja -C /work/build fuzzers 
cd ~
mv /src $SRC

chown -hR hacker:hacker $SRC /home/hacker/fuzz-dojo /home/hacker/.log /out
