#!/opt/pwn.college/bash
echo 35 > /tmp/initial
echo 40 > /tmp/target
if [ "$1" = "afl" ]; then
    . /usr/local/sbin/eafl
    shift
else
    . /usr/local/sbin/e
fi
export PROJECT_NAME=janus-gateway
export SANITIZER=$1
[ -z "$SANITIZER" ] && export SANITIZER='none'
cd $SRC

#apt-get update && apt-get install -y autoconf autoconf-archive automake gengetopt gtk-doc-tools libconfig-dev libglib2.0-dev libgnutls28-dev libini-config-dev libjansson-dev libnice-dev libssl-dev libtool openssl pkg-config

# install libsrtp dep from source
#git clone --single-branch --branch 2_2_x_throttle https://github.com/cisco/libsrtp.git libsrtp
cp -r /opt/fuzz-targets/libsrtp /src/

cd libsrtp && ./configure --enable-openssl && make -j$(nproc) shared_library && make install
cd $SRC/
# fetch Janus code
# git clone --single-branch --branch master https://github.com/meetecho/janus-gateway.git
cp -r /opt/fuzz-targets/janus-gateway /src/

cp /opt/oss-fuzz/projects/$PROJECT_NAME/build.sh $SRC/

cd $SRC/
if [ ! -d "/home/hacker/$PROJECT_NAME" ]; then
   mkdir /home/hacker/$PROJECT_NAME
   cp $SRC/$PROJECT_NAME/fuzzers/rtcp_fuzzer.c $SRC/$PROJECT_NAME/fuzzers/newfuzzer.c
   cp $SRC/$PROJECT_NAME/fuzzers/*.c /home/hacker/$PROJECT_NAME
   cp /src/build.sh /home/hacker/$PROJECT_NAME
   chown -R hacker /home/hacker/$PROJECT_NAME
else
   cp /home/hacker/$PROJECT_NAME/*.c $SRC/$PROJECT_NAME/fuzzers
   cp /home/hacker/$PROJECT_NAME/build.sh $SRC
fi
sudo --preserve-env compile
drivers