#!/opt/pwn.college/bash
. /usr/local/sbin/e
if [ "$?" -gt 0 ]; then
    exit 1
fi
export LABEL=$1
export PROJECT_NAME=example
export SANITIZER=$1
if [ -z "$SANITIZER" ]; then
    export SANITIZER='none'
    export LABEL='none'$LABEL
fi

if [ ! -d "/src-orig" ]; then
#----------------------------------------------------------------------
    #apt-get update && apt-get install -y make cmake pkg-config libssl-dev:i386
    #git clone https://github.com/google/oss-fuzz.git example
    mkdir -p $SRC/projects
    cp -r /downloads/example/projects/example $SRC/projects
    cp /opt/oss-fuzz/projects/$PROJECT_NAME/build.sh $SRC/
    cp $SRC/projects/$PROJECT_NAME/my-api-repo/do_stuff_fuzzer.cpp $SRC/projects/$PROJECT_NAME/my-api-repo/new_fuzzer.cpp
    cp $SRC/projects/$PROJECT_NAME/my-api-repo/do_stuff_fuzzer.dict $SRC/projects/$PROJECT_NAME/my-api-repo/new_fuzzer.dict

    patch -tuN $SRC/projects/$PROJECT_NAME/my-api-repo/Makefile -i /challenge/.Makefile.patch -r -
#----------------------------------------------------------------------
    build-cleanup
fi
build-srcfolders
mv /src-$LABEL /src

cd $SRC
#----------------------------------------------------------------------
if [ ! -d "/home/hacker/fuzz-dojo/$PROJECT_NAME" ]; then
   mkdir -p /home/hacker/fuzz-dojo/$PROJECT_NAME

   cp -r $SRC/projects/$PROJECT_NAME/my-api-repo/* /home/hacker/fuzz-dojo/$PROJECT_NAME
   cp $SRC/build.sh /home/hacker/fuzz-dojo/$PROJECT_NAME
else
   cp /home/hacker/fuzz-dojo/$PROJECT_NAME/* $SRC/projects/$PROJECT_NAME/my-api-repo
   cp /home/hacker/fuzz-dojo/$PROJECT_NAME/build.sh $SRC
fi
#----------------------------------------------------------------------
if [ "$4" = "understanding" ]; then
    understanding $2 $3
elif [ "$4" = "planning" ]; then
    planning $2 $3
else
    fuzzlog
    compile
    drivers
fi
mv /src /src-$LABEL
