#!/opt/pwn.college/bash
. /usr/local/sbin/e
export PROJECT_NAME=flac
export SANITIZER=$1
[ -z "$SANITIZER" ] && export SANITIZER='none'
cd $SRC

#apt-get update && apt-get install -y make autoconf automake libtool libtool-bin pkg-config gettext sudo default-jdk
rm -rf flac
rm -rf ogg
rm -rf libogg-install
rm -rf ExoPlayer
git clone --depth 1 https://github.com/xiph/flac.git
git clone --depth 1 https://github.com/xiph/ogg.git
git clone --depth 1 https://github.com/google/ExoPlayer.git

cp /opt/oss-fuzz/projects/$PROJECT_NAME/fuzzer_exo.cpp $SRC/

cp /opt/oss-fuzz/projects/$PROJECT_NAME/build.sh $SRC/

#patch -tuN /src/build.sh -i /challenge/build.patch -r -
cd $SRC/
if [ ! -d "/home/hacker/$PROJECT_NAME" ]; then
   mkdir /home/hacker/$PROJECT_NAME
   cp $SRC/fuzzer_exo.cpp $SRC/newfuzzer_new.cpp
   cp $SRC/*.cpp /home/hacker/$PROJECT_NAME
   cp /src/build.sh /home/hacker/$PROJECT_NAME
else
   cp /home/hacker/$PROJECT_NAME/*.c $SRC
   cp /home/hacker/$PROJECT_NAME/*.cc $SRC
   cp /home/hacker/$PROJECT_NAME/build.sh $SRC
fi
sudo --preserve-env compile