#!/bin/sh
. /usr/local/sbin/e.sh
export PROJECT_NAME=miniz
[ -z "$SANITIZER" ] && export SANITIZER='none'
cd $SRC

git clone https://github.com/haproxy/haproxy
cp /opt/oss-fuzz/projects/$PROJECT_NAME/fuzz* $SRC/

cp /opt/oss-fuzz/projects/$PROJECT_NAME/build.sh $SRC/
cd $SRC
compile
