#!/bin/sh
. /usr/local/sbin/e
export PROJECT_NAME=haproxy
[ -z "$SANITIZER" ] && export SANITIZER='none'
cd $SRC

rm -rf $SRC/$PROJECT_NAME
git clone https://github.com/haproxy/haproxy
cp /opt/oss-fuzz/projects/$PROJECT_NAME/fuzz* $SRC/
cp /opt/oss-fuzz/projects/$PROJECT_NAME/build.sh $SRC/

if [ ! -d "/home/hacker/$PROJECT_NAME" ]; then
   mkdir ~/$PROJECT_NAME
   cp $SRC/fuzz_cfg_parser.c $SRC/fuzz_newfuzzer.c
   cp $SRC/*.c ~/$PROJECT_NAME
   cp $SRC/build.sh ~/$PROJECT_NAME
else
   cp ~/$PROJECT_NAME/*.c $SRC
   cp ~/$PROJECT_NAME/build.sh $SRC
fi
patch -tuN /src/build.sh -i /challenge/build.patch -r -
compile