#!/bin/bash
export PROJECT_NAME=haproxy
sudo cp /usr/local/sbin/loc_count /usr/local/sbin/fi /challenge
sudo chmod 4755 /challenge/loc_count /challenge/fi
/challenge/loc_count
cd /src

rm -rf /src/$PROJECT_NAME
git clone https://github.com/haproxy/haproxy

/challenge/fi $PROJECT_NAME