#!/opt/pwn.college/bash
export PROJECT_NAME=haproxy
/challenge/.loc_count
cd /src

rm -rf /src/$PROJECT_NAME
#git clone https://github.com/haproxy/haproxy
cp -r /opt/fuzz-targets/haproxy /src/haproxy

/challenge/.fi $PROJECT_NAME