#!/bin/bash
export PROJECT_NAME=haproxy
INITIAL=1
TARGET=6
/usr/local/sbin/loc_count2 $PROJECT_NAME
/usr/local/sbin/announce $INITIAL $? 
if [ "$?" -gt "$TARGET" ]; then
    echo
    echo Congratulations!  But make sure you also submit your improvements to Google!
    cat /flag
fi
