#!/opt/pwn.college/bash
export PROJECT_NAME=mupdf
/challenge/.loc_count
cd /src

#apt-get update && apt-get install -y make libtool pkg-config

rm -rf /src/$PROJECT_NAME
#git clone --recursive --depth 1 git://git.ghostscript.com/mupdf.git mupdf
#git clone --depth 1 https://github.com/mozilla/pdf.js pdf.js 
cp -r /opt/fuzz-targets/mupdf /src
cp -r /opt/fuzz-targets/pdf.js /src

zip -q /src/pdf_fuzzer_seed_corpus.zip pdf.js/test/pdfs/*.pdf && rm -rf pdf.js
    
#wget https://raw.githubusercontent.com/rc0r/afl-fuzz/master/dictionaries/pdf.dict
cp /opt/fuzz-targets/pdf.dict /src
cp pdf.dict new_fuzzer.dict
mv pdf.dict pdf_fuzzer.dict

cp /opt/oss-fuzz/projects/$PROJECT_NAME/build.sh /src/
cp /opt/oss-fuzz/projects/$PROJECT_NAME/*.cc /src/
cp /opt/oss-fuzz/projects/$PROJECT_NAME/*.options /src/

cd /src/$PROJECT_NAME
patch -tuN /src/build.sh -i /challenge/.build.patch -r -

cp /home/hacker/$PROJECT_NAME/*.cc /src
cp /home/hacker/$PROJECT_NAME/build.sh /src
/challenge/.fi $PROJECT_NAME
