#!/opt/pwn.college/bash
. /usr/local/sbin/e
if [ "$?" -gt 0 ]; then
    exit 1
fi
export LABEL=$1
export PROJECT_NAME=valijson
export SANITIZER=$1
if [ -z "$SANITIZER" ]; then
    export SANITIZER='none'
    export LABEL='none'$LABEL
fi

if [ ! -d "/src-orig" ]; then
#----------------------------------------------------------------------
    #apt-get update && apt-get install -y make autoconf automake libtool pkg-config cmake libcurlpp-dev libcurl4-openssl-dev

    #rm -rf $SRC/$PROJECT_NAME
    #git clone --depth 1 https://github.com/tristanpenman/valijson
    cp -r /downloads/valijson $SRC

    cp $SRC/$PROJECT_NAME/tests/fuzzing/oss-fuzz-build.sh $SRC/build.sh
    # This is to fix Fuzz Introspector build by using LLVM old pass manager
    # re https://github.com/ossf/fuzz-introspector/issues/305
    export OLD_LLVMPASS=1
    cp $SRC/$PROJECT_NAME/tests/fuzzing/fuzzer.cpp $SRC/$PROJECT_NAME/tests/fuzzing/newfuzzer.cpp
    patch -tuN $SRC/build.sh -i /challenge/.build.patch -r -
    patch -tuN $SRC/build.sh -i /challenge/.build2.patch -r -

#----------------------------------------------------------------------
    build-cleanup
fi
build-srcfolders
mv /src-$LABEL /src
rm -rf $SRC/$PROJECT_NAME/build
rm -rf $SRC/$PROJECT_NAME/tests/fuzzing/seed_corpus

cd $SRC/$PROJECT_NAME
#----------------------------------------------------------------------
if [ ! -d "/home/hacker/fuzz-dojo/$PROJECT_NAME" ]; then
   mkdir -p /home/hacker/fuzz-dojo/$PROJECT_NAME
   cp $SRC/$PROJECT_NAME/tests/fuzzing/*.cpp /home/hacker/fuzz-dojo/$PROJECT_NAME
   cp $SRC/$PROJECT_NAME/tests/fuzzing/*.sh /home/hacker/fuzz-dojo/$PROJECT_NAME
   cp $SRC/build.sh /home/hacker/fuzz-dojo/$PROJECT_NAME
else
   cp /home/hacker/fuzz-dojo/$PROJECT_NAME/* $SRC/$PROJECT_NAME/tests/fuzzing
   cp /home/hacker/fuzz-dojo/$PROJECT_NAME/build.sh $SRC
fi
#----------------------------------------------------------------------
if [ "$4" = "understanding" ]; then
    understanding $2 $3
elif [ "$4" = "planning" ]; then
    planning $2 $3
else
    fuzzlog
    compile
    drivers
fi
mv /src /src-$LABEL