#!/opt/pwn.college/bash
if [ "$1" = "afl" ]; then
    . /usr/local/sbin/eafl
    shift
else
    . /usr/local/sbin/e
fiafl
export PROJECT_NAME=imagemagick
export SANITIZER=$1
[ -z "$SANITIZER" ] && export SANITIZER='none'
cd $SRC

apt-get update && \
    apt-get install -y make autoconf automake groff libtool pkg-config cmake nasm autopoint
git clone --depth 1 https://github.com/imagemagick/imagemagick
git clone --depth 1 https://gitlab.com/libtiff/libtiff
git clone --depth 1 https://github.com/strukturag/libde265
git clone --depth 1 https://github.com/strukturag/libheif
git clone --depth 1 https://github.com/uclouvain/openjpeg
git clone --depth 1 https://github.com/webmproject/libwebp
git clone --depth 1 https://github.com/madler/zlib
git clone --depth 1 https://github.com/ebiggers/libdeflate
git clone --depth 1 https://github.com/libjpeg-turbo/libjpeg-turbo
git clone --depth 1 https://github.com/xz-mirror/xz
git clone --depth 1 https://github.com/libraw/libraw
git clone --depth 1 https://github.com/pnggroup/libpng
git clone --depth 1 https://github.com/mm2/Little-CMS
git clone --depth 1 https://github.com/freetype/freetype
git clone --depth 1 https://gitlab.com/federicomenaquintero/bzip2.git
git clone --depth 1 --recursive https://github.com/libjxl/libjxl
git clone https://www.cl.cam.ac.uk/~mgk25/git/jbigkit # does not support shallow
wget https://lcamtuf.coredump.cx/afl/demo/afl_testcases.tgz


cp /opt/oss-fuzz/projects/$PROJECT_NAME/build.sh $SRC/

cd $SRC/$PROJECT_NAME
sudo --preserve-env compile
drivers
