#!/opt/pwn.college/bash
. /usr/local/sbin/eafl
export PROJECT_NAME=e2fsprogs
export SANITIZER=$1
[ -z "$SANITIZER" ] && export SANITIZER='none'
cd $SRC

apt-get install -y --allow-downgrades --allow-remove-essential --allow-change-held-packages git make texinfo
git clone --depth 1 https://github.com/tytso/e2fsprogs


cp /opt/oss-fuzz/projects/$PROJECT_NAME/build.sh $SRC/
cp /opt/oss-fuzz/projects/$PROJECT_NAME/fuzz $SRC/fuzz

cd $SRC/$PROJECT_NAME

sudo --preserve-env compile
drivers
