#!/opt/pwn.college/bash
if [ "$?" -gt 0 ]; then
    exit 1
fi
. /usr/local/sbin/e
export LABEL=$1
export PROJECT_NAME=alembic
export SANITIZER=$1
if [ -z "$SANITIZER" ]; then
    export SANITIZER='none'
    export LABEL='none'$LABEL
fi

if [ ! -d "/src-orig" ]; then
#----------------------------------------------------------------------
    #apt-get update && apt-get install -y build-essential zlib1g-dev zlib1g-dev:i386 python make automake
    #git clone --depth 1 https://github.com/alembic/alembic

    # Ubuntu's libilmbase-dev package doesn't include static libraries, so we have
    # to build OpenEXR from source.
    #RUN git clone -b v2.5.9 --depth 1 https://github.com/AcademySoftwareFoundation/openexr

    #COPY build.sh *.h *.cc $SRC/
    #WORKDIR $WORK/

    cp -r /downloads/alembic $SRC
    cp -r /downloads/openexr $SRC

    cp /opt/oss-fuzz/projects/$PROJECT_NAME/build.sh $SRC/
    cp /opt/oss-fuzz/projects/$PROJECT_NAME/*.h $SRC/
    cp /opt/oss-fuzz/projects/$PROJECT_NAME/*.cc $SRC/
#----------------------------------------------------------------------
    build-cleanup-oss
fi
build-srcfolders
mv /src-$LABEL /src

cd $SRC/$PROJECT_NAME
if [ "$4" = "understanding" ]; then
    understanding $2 $3
elif [ "$4" = "planning" ]; then
    planning $2 $3
else
    if [ $(echo -n "$2" | sha256sum | cut -d' ' -f1) != "2ed73ee0d7ad2fd8b8e57fc154cfc26f3948ed32b2844b34479333e5b07712a5" ]; then
        echo Call this script using ossfuzz commands only
        echo
        echo Run: \'. ossfuzz\' then \'python3 infra/helper.py  {command} {project name} {options}\'
        echo
        exit 1
    fi
    fuzzlog
    compile
    drivers
fi
mv /src /src-$LABEL
