#!/opt/pwn.college/bash
echo 999 > /tmp/initial
echo 999 > /tmp/target
if [ "$1" = "afl" ]; then
    . /usr/local/sbin/eafl
    shift
else
    . /usr/local/sbin/e
fiafl
export PROJECT_NAME=cyclonedds
export SANITIZER=$1
[ -z "$SANITIZER" ] && export SANITIZER='none'
cd $SRC

#apt-get update && apt install -y \
#    autoconf \
#    automake \
#    libssl-dev \
#    libcunit1 \
#    libcunit1-dev \
#    bison \
#    libbison-dev

#git clone --depth 1 https://github.com/eclipse-cyclonedds/cyclonedds

cp -r /opt/fuzz-targets/cyclonedds /src/cyclonedds
cp -r /opt/fuzz-targets/cyclonedds-python /src/$PROJECT_NAME/cyclonedds-python
# This is to fix Fuzz Introspector build by using LLVM old pass manager
# re https://github.com/ossf/fuzz-introspector/issues/305
export OLD_LLVMPASS=1

cp /opt/oss-fuzz/projects/$PROJECT_NAME/build.sh $SRC/

patch -tuN /src/cyclonedds/fuzz/fuzz_sample_deser/prepare.sh -i /challenge/.prepare.patch -r -

cd $SRC/cyclonedds
[ ! "$SANITIZER" = "introspector" ] && [ ! "$SANITIZER" = "coverage" ] && zip -ry /home/hacker/.vnc/$PROJECT_NAME-$(date +"%F--%H-%M-%S") /home/hacker/$PROJECT_NAME
sudo --preserve-env compile
drivers
