#!/opt/pwn.college/bash
if [ "$1" = "afl" ]; then
    . /usr/local/sbin/eafl
    shift
else
    . /usr/local/sbin/e
fi
export PROJECT_NAME=libwebp
export SANITIZER=$1
[ -z "$SANITIZER" ] && export SANITIZER='none'
cd $SRC

#apt-get update && apt-get install -y autoconf make libtool zip
#git clone https://chromium.googlesource.com/webm/libwebp
#git clone https://chromium.googlesource.com/webm/libwebp-test-data
#wget https://storage.googleapis.com/downloads.webmproject.org/webp/testdata/fuzzer/fuzz_seed_corpus.zip

cp -r /opt/fuzz-targets/libwebp /src
cp -r /opt/fuzz-targets/libwebp-test-data /src
cp -r /opt/fuzz-targets/fuzz_seed_corpus.zip /src

unzip fuzz_seed_corpus.zip -d libwebp-test-data/
rm fuzz_seed_corpus.zip

cp /opt/oss-fuzz/projects/$PROJECT_NAME/build.sh $SRC/

cd $SRC/libwebp

sudo --preserve-env compile
drivers
