#!/opt/pwn.college/bash
export PROJECT_NAME=libwebp
/challenge/.loc_count
cd /src

rm -rf /src/$PROJECT_NAME

#apt-get update && apt-get install -y autoconf make libtool zip
#git clone https://chromium.googlesource.com/webm/libwebp
#git clone https://chromium.googlesource.com/webm/libwebp-test-data
#wget https://storage.googleapis.com/downloads.webmproject.org/webp/testdata/fuzzer/fuzz_seed_corpus.zip

cp -r /opt/fuzz-targets/libwebp /src
cp -r /opt/fuzz-targets/libwebp-test-data /src
cp -r /opt/fuzz-targets/fuzz_seed_corpus.zip /src

unzip fuzz_seed_corpus.zip -d libwebp-test-data/
rm fuzz_seed_corpus.zip

cp /opt/oss-fuzz/projects/$PROJECT_NAME/build.sh /src/

patch -tuN /src/build.sh -i /challenge/.build.patch -r -
cd /src/$PROJECT_NAME
cp /home/hacker/$PROJECT_NAME/*.cc /src/$PROJECT_NAME/tests/fuzzer
cp /home/hacker/$PROJECT_NAME/build.sh /src
/challenge/.fi $PROJECT_NAME
