#!/opt/pwn.college/bash
. /usr/local/sbin/e
export LABEL=$1
export PROJECT_NAME=bzip2
export SANITIZER=$1
if [ -z "$SANITIZER" ]; then
    export SANITIZER='none'
    export LABEL='none'$LABEL
fi

if [ ! -d "/src-orig" ]; then
    rm -rf $SRC/$PROJECT_NAME
    rm -rf $SRC/$PROJECT_NAME-tests
    #apt-get update && apt-get install -y make autoconf automake libtool wget
    #git clone git://sourceware.org/git/bzip2.git
    #git clone git://sourceware.org/git/bzip2-tests.git
    cp -r /downloads/bzip2 $SRC
    cp -r /downloads/bzip2-tests $SRC

    cp /opt/oss-fuzz-new/projects/$PROJECT_NAME/build.sh $SRC/
    cp /opt/oss-fuzz-new/projects/$PROJECT_NAME/*.c $SRC/
    
    cp $SRC/bzip2_compress_target.c $SRC/newfuzzer.c
    echo Please wait, creating /src-orig
    chown -hR hacker:hacker $SRC
    mv /src /src-orig
fi
if [ ! -d "/src-$LABEL" ]; then
    echo Please wait, creating /src-$LABEL
    cp -r /src-orig /src-$LABEL
fi
mv /src-$LABEL /src

cd $SRC
if [ ! -d "/home/hacker/fuzz-dojo/$PROJECT_NAME" ]; then
   mkdir -p /home/hacker/fuzz-dojo/$PROJECT_NAME
   cp $SRC/*.c /home/hacker/fuzz-dojo/$PROJECT_NAME
   cp $SRC/build.sh /home/hacker/fuzz-dojo/$PROJECT_NAME
   chown -R hacker /home/hacker/fuzz-dojo/$PROJECT_NAME
else
   cp /home/hacker/fuzz-dojo/$PROJECT_NAME/*.c $SRC
   cp /home/hacker/fuzz-dojo/$PROJECT_NAME/build.sh $SRC
fi

fuzzlog
compile
drivers
mv /src /src-$LABEL
