#!/bin/sh
. /usr/local/sbin/e
export PROJECT_NAME=libtasn1
export SANITIZER=$1
[ -z "$SANITIZER" ] && export SANITIZER='none'
cd $SRC

#apt-get update && apt-get install -y make autoconf automake libtool bison
git clone git://git.savannah.gnu.org/gnulib.git
export GNULIB_TOOL=$SRC/gnulib/gnulib-tool
export GNULIB_SRCDIR=$SRC/gnulib
git clone https://gitlab.com/gnutls/libtasn1.git

cp /opt/oss-fuzz/projects/$PROJECT_NAME/build.sh $SRC/
cd $SRC/$PROJECT_NAME
if [ ! -d "/home/hacker/training-speedup" ]; then
   mkdir /home/hacker/training-speedup
   cp $SRC/$PROJECT_NAME/fuzz/libtasn1_gnutls_der_fuzzer.c  $SRC/$PROJECT_NAME/fuzz/new_fuzzer.c
   cp $SRC/$PROJECT_NAME/fuzz/*.c /home/hacker/training-speedup
   cp /opt/oss-fuzz/projects/$PROJECT_NAME/build.sh /home/hacker/training-speedup
else
   cp /home/hacker/training-speedup/*.c $SRC/$PROJECT_NAME/fuzz
   cp /home/hacker/training-speedup/build.sh $SRC
fi
#patch -tuN /src/build.sh -i /challenge/build.patch -r -
compile