#!/opt/pwn.college/bash 
INITIAL=31
TARGET=34
time sudo -H -u hacker bash -c "/usr/local/sbin/loc_count $*"
echo
echo Checking bzip2_decompress_target for improvements:
/usr/local/sbin/loc-calc bzip2_decompress_target
/usr/local/sbin/announce $INITIAL $? 
if [ "$?" -ge "$TARGET" ]; then
    echo
    echo Congratulations!
    cat /flag
fi
if compgen -G "/out/crash*" > /dev/null; then
    echo
    echo "Crashes detected within the /out directory!"
    echo
fi
