#!/opt/pwn.college/bash 
INITIAL=58
TARGET=63
time sudo -H -u hacker bash -c "/usr/local/sbin/loc_count $*"
echo
echo bzip2_compress_target
/usr/local/sbin/loc-calc bzip2_compress_target
/usr/local/sbin/announce $INITIAL $? 
if [ "$?" -ge "$TARGET" ]; then
    echo
    echo Congratulations!
    cat /flag
fi
if compgen -G "/out/crash*" > /dev/null; then
    echo
    echo "Crashes detected within the /out directory!"
    echo
fi
