#!/opt/pwn.college/bash
if [ "$1" = "afl" ]; then
    . /usr/local/sbin/eafl
    shift
else
    . /usr/local/sbin/e
fi
export PROJECT_NAME=janus-gateway
export SANITIZER=$1
[ -z "$SANITIZER" ] && export SANITIZER='none'

if [ ! -d "/src-orig" ]; then
    #apt-get update && apt-get install -y autoconf autoconf-archive automake gengetopt gtk-doc-tools libconfig-dev libglib2.0-dev libgnutls28-dev libini-config-dev libjansson-dev libnice-dev libssl-dev libtool openssl pkg-config

    # install libsrtp dep from source
    #git clone --single-branch --branch 2_2_x_throttle https://github.com/cisco/libsrtp.git libsrtp
    cp -r /opt/fuzz-targets/libsrtp $SRC

    cd libsrtp && ./configure --enable-openssl && make -j$(nproc) shared_library && make install
    cd $SRC/
    # fetch Janus code
    # git clone --single-branch https://github.com/swirsz/janus-gateway.git
    cp -r /opt/fuzz-targets/janus-gateway $SRC

    cp /opt/oss-fuzz-new/projects/$PROJECT_NAME/build.sh $SRC/

    echo Please wait, initial setup
    chown -hR hacker:hacker $SRC/$PROJECT_NAME
    mv /src /src-orig
fi
if [ ! -d "/src-$SANITIZER" ]; then
    echo Please wait, initial setup
    cp -r /src-orig /src-$SANITIZER
fi

cd $SRC/
if [ ! -d "/home/hacker/fuzz-dojo/training-split" ]; then
   mkdir /home/hacker/fuzz-dojo/training-split
   cp $SRC/$PROJECT_NAME/fuzzers/rtcp_fuzzer.c $SRC/$PROJECT_NAME/fuzzers/newfuzzer.c
   cp $SRC/$PROJECT_NAME/fuzzers/*.c /home/hacker/fuzz-dojo/training-split
   cp /opt/oss-fuzz-new/projects/$PROJECT_NAME/build.sh /home/hacker/fuzz-dojo/training-split
   chown -R hacker /home/hacker/fuzz-dojo/training-split
else
   cp /home/hacker/fuzz-dojo/training-split/*.c $SRC/$PROJECT_NAME/fuzzers
   cp /home/hacker/fuzz-dojo/training-split/build.sh $SRC
fi
mkdir -p /home/hacker/.log
[ ! "$SANITIZER" = "introspector" ] && [ ! "$SANITIZER" = "coverage" ] && zip -ry /home/hacker/.log/$(TZ=US/Arizona date +"%F--%H-%M-%S")-training-split /home/hacker/fuzz-dojo/training-split
sudo --preserve-env compile
drivers
chown -hR hacker:hacker $SRC/$PROJECT_NAME
mv /src /src-$SANITIZER