#!/opt/pwn.college/bash
. /usr/local/sbin/e
export LABEL=$1
export PROJECT_NAME=janus-gateway
export SANITIZER=$1
if [ -z "$SANITIZER" ]; then
    export SANITIZER='none'
    export LABEL='none'$LABEL
fi

if [ ! -d "/src-orig" ]; then
#----------------------------------------------------------------------
    #apt-get update && apt-get install -y autoconf autoconf-archive automake gengetopt gtk-doc-tools libconfig-dev libglib2.0-dev libgnutls28-dev libini-config-dev libjansson-dev libnice-dev libssl-dev libtool openssl pkg-config

    # install libsrtp dep from source
    #git clone --single-branch --branch 2_2_x_throttle https://github.com/cisco/libsrtp.git libsrtp
    cp -r /downloads/libsrtp $SRC

    cd libsrtp && ./configure --enable-openssl && make -j$(nproc) shared_library && make install
    cd $SRC/
    # fetch Janus code
    # git clone --single-branch https://github.com/swirsz/janus-gateway.git
    cp -r /downloads/janus-gateway $SRC

    cp /opt/oss-fuzz/projects/$PROJECT_NAME/build.sh $SRC/
    cp $SRC/$PROJECT_NAME/fuzzers/rtcp_fuzzer.c $SRC/$PROJECT_NAME/fuzzers/newfuzzer.c

#----------------------------------------------------------------------
    build-cleanup
fi
build-srcfolders
mv /src-$LABEL /src

cd $SRC/
#----------------------------------------------------------------------
if [ ! -d "/home/hacker/fuzz-dojo/training-split" ]; then
   mkdir -p /home/hacker/fuzz-dojo/training-split
   cp $SRC/$PROJECT_NAME/fuzzers/*.c /home/hacker/fuzz-dojo/training-split
   cp /opt/oss-fuzz/projects/$PROJECT_NAME/build.sh /home/hacker/fuzz-dojo/training-split
else
   cp /home/hacker/fuzz-dojo/training-split/*.c $SRC/$PROJECT_NAME/fuzzers
   cp /home/hacker/fuzz-dojo/training-split/build.sh $SRC
fi
export PROJECT_NAME=training-split
#----------------------------------------------------------------------
fuzzlog
compile
drivers
mv /src /src-$LABEL
