#!/opt/pwn.college/bash 
INITIAL=35
TARGET=38
sudo -H -u hacker bash -c "/usr/local/sbin/loc_count $*"
/usr/local/sbin/announce $INITIAL $? 
if [ "$?" -ge "$TARGET" ]; then
    echo
    echo Congratulations!  Additional code coverage detected!
    cat /flag
fi
if compgen -G "/out/crash*" > /dev/null; then
    echo
    echo "Crashes detected within the /out directory!"
    echo
fi
