#!/opt/pwn.college/bash
export PROJECT_NAME=curl
/challenge/.loc_count
cd /src

rm -rf /src/curl
rm -rf /src/curl_install
rm -rf /src/curl_fuzzer
rm -rf /src/nghttp2
rm -rf /src/openssl
rm -rf /src/zlib
#git clone --depth 1 https://github.com/curl/curl.git /src/$PROJECT_NAME
#git clone --depth 1 https://github.com/curl/curl-fuzzer.git /src/curl_fuzzer
cp -r /opt/fuzz-targets/curl /src
cp -r /opt/fuzz-targets/curl_fuzzer /src
cp -r /opt/fuzz-targets/zlib /src
cp -r /opt/fuzz-targets/openssl32 /src/openssl
cp -r /opt/fuzz-targets/nghttp2 /src
# Use curl-fuzzer's scripts to get latest dependencies.
#/src/curl_fuzzer/scripts/ossfuzz.sh

cp /opt/oss-fuzz/projects/$PROJECT_NAME/build.sh /src/

patch -tuN /src/curl_fuzzer/fuzz_targets -i /challenge/.fuzz_targets.patch -r -
#patch -tuN /src/build.sh -i /challenge/.build.patch -r -
cd /src/curl_fuzzer
cp /home/hacker/$PROJECT_NAME/* /src/curl_fuzzer


/challenge/.fi $PROJECT_NAME
