#!/opt/pwn.college/bash
. /usr/local/sbin/eafl
export PROJECT_NAME=pycryptodome
export SANITIZER=$1
[ -z "$SANITIZER" ] && export SANITIZER='none'
cd $SRC

#apt-get update && apt-get install -y make autoconf automake libtool
rm -rf /src/$PROJECT_NAME
#git clone https://github.com/Legrandin/pycryptodome.git
cp -r /opt/fuzz-targets/pycryptodome /src/pycryptodome

cp /opt/oss-fuzz/projects/$PROJECT_NAME/*_fuzzer.cc $SRC/
cp /opt/oss-fuzz/projects/$PROJECT_NAME/block_common.patch $SRC/pycryptodome/src

cp /opt/oss-fuzz/projects/$PROJECT_NAME/build.sh $SRC/

patch -tuN /src/build.sh -i /challenge/.build.patch -r -
cd $SRC/$PROJECT_NAME/src
if [ ! -d "/home/hacker/$PROJECT_NAME" ]; then
   mkdir /home/hacker/$PROJECT_NAME
   cp $SRC/pcd_aes_fuzzer.cc $SRC/newfuzzer.cc
   cp $SRC/*.cc /home/hacker/$PROJECT_NAME
   cp /src/build.sh /home/hacker/$PROJECT_NAME
   chown -R hacker /home/hacker/$PROJECT_NAME
else
   cp /home/hacker/$PROJECT_NAME/*.cc $SRC
   cp /home/hacker/$PROJECT_NAME/build.sh $SRC
fi
sudo --preserve-env compile
drivers
