#!/opt/pwn.college/bash
if [ "$1" = "afl" ]; then
    . /usr/local/sbin/eafl
    shift
    export LABEL=$1$FUZZING_ENGINE
else
    . /usr/local/sbin/e
    export LABEL=$1
fi
export PROJECT_NAME=pycryptodome
export SANITIZER=$1
[ -z "$SANITIZER" ] && export SANITIZER='none'

if [ ! -d "/src-orig" ]; then
    #apt-get update && apt-get install -y make autoconf automake libtool
    #rm -rf $SRC/$PROJECT_NAME
    #git clone https://github.com/Legrandin/pycryptodome.git
    cp -r /opt/fuzz-targets/pycryptodome $SRC

    cp /opt/oss-fuzz-new/projects/$PROJECT_NAME/*_fuzzer.cc $SRC/
    cp /opt/oss-fuzz-new/projects/$PROJECT_NAME/block_common.patch $SRC/pycryptodome$SRC

    cp /opt/oss-fuzz-new/projects/$PROJECT_NAME/build.sh $SRC/
    cp $SRC/pcd_aes_fuzzer.cc $SRC/newfuzzer.cc

    patch -tuN $SRC/build.sh -i /challenge/.build.patch -r -
    echo Please wait, creating /src-orig
    chown -hR hacker:hacker $SRC
    mv /src /src-orig
fi
#if [ ! -d "/src-$LABEL" ]; then
#   echo Please wait, initial setup
    rm -rf $SRC/$PROJECT_NAME
    cp -r /src-orig /src-$LABEL
#fi
mv /src-$LABEL /src

cd $SRC/$PROJECT_NAME/src
if [ ! -d "/home/hacker/fuzz-dojo/$PROJECT_NAME" ]; then
   mkdir -p /home/hacker/fuzz-dojo/$PROJECT_NAME
   cp $SRC/*.cc /home/hacker/fuzz-dojo/$PROJECT_NAME
   cp $SRC/build.sh /home/hacker/fuzz-dojo/$PROJECT_NAME
   chown -R hacker /home/hacker/fuzz-dojo/$PROJECT_NAME
else
   cp /home/hacker/fuzz-dojo/$PROJECT_NAME/*.cc $SRC
   cp /home/hacker/fuzz-dojo/$PROJECT_NAME/build.sh $SRC
fi
mkdir -p /home/hacker/.log
[ ! "$SANITIZER" = "introspector" ] && [ ! "$SANITIZER" = "coverage" ] && zip -ry /home/hacker/.log/$(TZ=US/Arizona date +"%F--%H-%M-%S")-$PROJECT_NAME /home/hacker/fuzz-dojo/$PROJECT_NAME
sudo --preserve-env compile
drivers
chown -hR hacker:hacker $SRC /home/hacker/fuzz-dojo /home/hacker/.log /out
mv /src /src-$LABEL
