#!/opt/pwn.college/bash
echo 9 > /tmp/initial
echo 14 > /tmp/target
if [ "$1" = "afl" ]; then
    . /usr/local/sbin/eafl
    shift
else
    . /usr/local/sbin/e
fi
export PROJECT_NAME=git
export SANITIZER=$1
[ -z "$SANITIZER" ] && export SANITIZER='none'
cd $SRC
rm -rf $SRC/$PROJECT_NAME
rm -rf $SRC/zlib
#apt-get update && apt-get install --no-install-recommends -y cvs cvsps gettext libcgi-pm-perl libcurl4-gnutls-dev \
# libdbd-sqlite3-perl liberror-perl libexpat1-dev libhttp-date-perl libio-pty-perl libmailtools-perl libpcre2-dev \
# libpcre3-dev libsvn-perl perl-modules libyaml-perl libz-dev python subversion tcl unzip asciidoc docbook-xsl xmlto libssl-dev zip

#git clone https://github.com/git/git git
cp -r /downloads/git $SRC/
cp -r /downloads/zlib $SRC/
cd $SRC/$PROJECT_NAME
#git checkout origin/next
#git pull origin next
mkdir -p $SRC/$PROJECT_NAME/oss-fuzz
cp /opt/oss-fuzz/projects/$PROJECT_NAME/fuzz-* $SRC/$PROJECT_NAME/oss-fuzz
cp /opt/oss-fuzz/projects/$PROJECT_NAME/Makefile.diff $SRC/$PROJECT_NAME

cd $SRC/$PROJECT_NAME
git apply Makefile.diff
# This is to fix Fuzz Introspector build by using LLVM old pass manager
# re https://github.com/ossf/fuzz-introspector/issues/305
export OLD_LLVMPASS=1

cp /opt/oss-fuzz/projects/$PROJECT_NAME/build.sh $SRC/

patch -tuN $SRC/build.sh -i /challenge/.build.patch -r -
patch -tuN $SRC/git/Makefile -i /challenge/.Makefile.patch -r -
cd $SRC/$PROJECT_NAME
if [ ! -d "/home/hacker/$PROJECT_NAME" ]; then
   mkdir /home/hacker/$PROJECT_NAME
   cp $SRC/$PROJECT_NAME/oss-fuzz/fuzz-cmd-diff.c $SRC/$PROJECT_NAME/oss-fuzz/fuzz-new.c
   cp $SRC/$PROJECT_NAME/oss-fuzz/*.c /home/hacker/$PROJECT_NAME
   cp $SRC/$PROJECT_NAME/Makefile /home/hacker/$PROJECT_NAME
   #cp $SRC/$PROJECT_NAME/oss-fuzz/.depend/fuzz-new.o.d /home/hacker/$PROJECT_NAME
   cp $SRC/build.sh /home/hacker/$PROJECT_NAME
   chown -R hacker /home/hacker/$PROJECT_NAME
else
   cp /home/hacker/$PROJECT_NAME/*.c $SRC/$PROJECT_NAME/oss-fuzz
   cp /home/hacker/$PROJECT_NAME/Makefile $SRC/$PROJECT_NAME
   #mkdir -p  $SRC/$PROJECT_NAME/oss-fuzz/.depend
   #cp /home/hacker/$PROJECT_NAME/fuzz-new.o.d $SRC/$PROJECT_NAME/oss-fuzz/.depend
   cp /home/hacker/$PROJECT_NAME/build.sh $SRC
fi
mkdir -p /home/hacker/.log
[ ! "$SANITIZER" = "introspector" ] && [ ! "$SANITIZER" = "coverage" ] && zip -ry /home/hacker/.log/$(TZ=US/Arizona date +"%F--%H-%M-%S")-$PROJECT_NAME /home/hacker/$PROJECT_NAME
compile
drivers