#!/bin/sh
. /usr/local/sbin/e
export PROJECT_NAME=libtasn1
[ -z "$SANITIZER" ] && export SANITIZER='none'
cd $SRC

#apt-get update && apt-get install -y make autoconf automake libtool bison
git clone git://git.savannah.gnu.org/gnulib.git
export GNULIB_TOOL=$SRC/gnulib/gnulib-tool
export GNULIB_SRCDIR=$SRC/gnulib
git clone https://gitlab.com/gnutls/libtasn1.git

cp /opt/oss-fuzz/projects/$PROJECT_NAME/build.sh $SRC/
cd $SRC/$PROJECT_NAME
if [ ! -d "/home/hacker/$PROJECT_NAME" ]; then
   mkdir ~/$PROJECT_NAME
   cp $SRC/$PROJECT_NAME/yyyyyyyyyyyy/zzzzzzzzzzzzzzzzz.c $SRC/$PROJECT_NAME/yyyyyyyyyyyy/newfuzzer.c
   cp $SRC/$PROJECT_NAME/yyyyyyyyyyyy/*.c ~/$PROJECT_NAME
else
   cp ~/$PROJECT_NAME/*.c $SRC/$PROJECT_NAME/yyyyyyyyyyyy
fi
#patch -tuN /src/build.sh -i /challenge/build.patch -r -
compile