#!/opt/pwn.college/bash
. /usr/local/sbin/e
export PROJECT_NAME=libtasn1
export SANITIZER=$1
[ -z "$SANITIZER" ] && export SANITIZER='none'
cd $SRC

#apt-get update && apt-get install -y make autoconf automake libtool bison
#git clone git://git.savannah.gnu.org/gnulib.git
export GNULIB_TOOL=$SRC/gnulib/gnulib-tool
export GNULIB_SRCDIR=$SRC/gnulib
#git clone https://gitlab.com/gnutls/libtasn1.git
cp -r /opt/fuzz-targets/gnulib /src/gnulib
cp -r /opt/fuzz-targets/libtasn1 /src/libtasn1

cp /opt/oss-fuzz/projects/$PROJECT_NAME/build.sh $SRC/

#patch -tuN /src/build.sh -i /challenge/build.patch -r -
cd $SRC/$PROJECT_NAME
if [ ! -d "/home/hacker/$PROJECT_NAME" ]; then
   mkdir /home/hacker/$PROJECT_NAME
   cp $SRC/$PROJECT_NAME/fuzz/libtasn1_gnutls_der_fuzzer.c  $SRC/$PROJECT_NAME/fuzz/new_fuzzer.c
   cp $SRC/$PROJECT_NAME/fuzz/*.c /home/hacker/$PROJECT_NAME
   cp /src/build.sh /home/hacker/$PROJECT_NAME
   chown -R hacker /home/hacker/$PROJECT_NAME
else
   cp /home/hacker/$PROJECT_NAME/*.c $SRC/$PROJECT_NAME/fuzz
   cp /home/hacker/$PROJECT_NAME/build.sh $SRC
fi
sudo --preserve-env compile