#!/bin/bash
export PROJECT_NAME=libtasn1
/usr/local/sbin/loc_count $PROJECT_NAME
cd /src/$PROJECT_NAME
export GNULIB_TOOL=/src/gnulib/gnulib-tool
export GNULIB_SRCDIR=/src/gnulib
/usr/local/sbin/fi $PROJECT_NAME
