#!/opt/pwn.college/bash
if [ "$1" = "afl" ]; then
    . /usr/local/sbin/eafl
    shift
else
    . /usr/local/sbin/e
fi
export PROJECT_NAME=yara
export SANITIZER=$1
[ -z "$SANITIZER" ] && export SANITIZER='none'
cd $SRC

#apt-get update && apt-get install -y \
#  automake \
#  autoconf \
#  make \
#  libtool \
#  pkg-config \
#  bison \
#  flex

#git clone --depth 1 https://github.com/VirusTotal/yara.git
cp -r /opt/fuzz-targets/yara /src

cp /opt/oss-fuzz/projects/$PROJECT_NAME/build.sh $SRC/

#patch -tuN /src/build.sh -i /challenge/.build.patch -r -
cd $SRC/yara

sudo --preserve-env compile
drivers
