#!/bin/sh

. /usr/local/sbin/e.sh
[ -z "$SANITIZER" ] && export SANITIZER='none'

apt-get update && apt-get install -y \
 make \
 pkg-config \
 gettext \
 autogen \
 autopoint \
 autoconf \
 autoconf-archive \
 automake \
 libtool \
 texinfo \
 flex \
 bison \
 gettext \
 gengetopt \
 curl \
 gperf \
 wget \
 python \
 rsync \
 gtk-doc-tools \
 libtasn1-bin \
 libz-dev

export GNULIB_TOOL=$SRC/gnulib/gnulib-tool
export GNULIB_SRCDIR=$SRC/gnulib
cd $SRC
git clone git://git.savannah.gnu.org/gnulib.git 
wget https://ftp.gnu.org/gnu/libunistring/libunistring-latest.tar.gz
tar -xzvf libunistring-latest.tar.gz
mv /src/libunistring-* /src/libunistring
wget https://ftp.gnu.org/gnu/libidn/libidn2-latest.tar.gz /src
tar -xzvf libidn2-latest.tar.gz 
mv /src/libidn2-* /src/libidn2
mv /src/libidn2/unistring/.libs/libunistring.lax/libunistring.a/ /src/libidn2/unistring/.libs/libunistring.a
git clone --depth=1 --recursive https://github.com/rockdaboot/libpsl.git 
git clone --depth=1 https://git.lysator.liu.se/nettle/nettle.git
git clone --depth=1 https://gitlab.com/gnutls/gnutls.git
git clone https://git.savannah.gnu.org/git/wget.git
cp /opt/oss-fuzz/projects/wget/build.sh $SRC/
cd $SRC/wget
compile
find-drv.sh
