#!/bin/bash
DRIVERS=('wget_cookie_fuzzer' 'wget_css_fuzzer' 'wget_ftpls_fuzzer' 'wget_html_fuzzer' 'wget_netrc_fuzzer' 'wget_ntlm_fuzzer' 'wget_options_fuzzer' 'wget_progress_fuzzer' 'wget_read_hunk_fuzzer' 'wget_robots_fuzzer' 'wget_url_fuzzer')
export PROJECT_NAME='wget' 

. /usr/local/sbin/e.sh
export SANITIZER='none'
/challenge/build-image

parallel run_fuzzer ::: ${DRIVERS[@]} ::: -max_total_time=10

cd $SRC/$PROJECT_NAME
export SANITIZER='coverage'
compile

for driver in "${DRIVERS[@]}"
do
    rm -rf /corpus/$driver
    mv /tmp/${driver}_corpus /corpus/$driver
done

coverage
echo
for driver in "${DRIVERS[@]}"
do
    echo $driver
    /usr/local/sbin/loc.py $PROJECT_NAME $driver
    echo
done
