#!/opt/pwn.college/bash 
INITIAL=45
TARGET=45
time sudo -H -u hacker bash -c "/usr/local/sbin/loc_count $*"
echo
echo newfuzzer
/usr/local/sbin/loc-calc newfuzzer
/usr/local/sbin/announce $INITIAL $? 
if [ "$?" -ge "$TARGET" ]; then
    echo
    echo Congratulations! But you will need to run /challenge/loc2 to win.
fi
if compgen -G "/out/crash*" > /dev/null; then
    echo
    echo "Crashes detected within the /out directory!"
    echo
fi
