#!/bin/sh
. /usr/local/sbin/e
export PROJECT_NAME=lzo
[ -z "$SANITIZER" ] && export SANITIZER='none'
cd $SRC

apt-get update && apt-get install -y make autoconf automake libtool wget
wget -O lzo.tar.gz http://www.oberhumer.com/opensource/lzo/download/lzo-2.10.tar.gz

cp /opt/oss-fuzz/projects/$PROJECT_NAME/*.c $SRC/
cp /opt/oss-fuzz/projects/$PROJECT_NAME/*.cc $SRC/
cp /opt/oss-fuzz/projects/$PROJECT_NAME/*.options $SRC/
mkdir $SRC/lzo_decompress_target_seeds
cp /opt/oss-fuzz/projects/$PROJECT_NAME/lzo_decompress_target_seeds $SRC/lzo_decompress_target_seeds

cp /opt/oss-fuzz/projects/$PROJECT_NAME/build.sh $SRC/

cd $SRC/
compile