#!/bin/sh
. /usr/local/sbin/e
export PROJECT_NAME=vorbis
export SANITIZER=$1
[ -z "$SANITIZER" ] && export SANITIZER='none'
cd $SRC

#apt-get update && apt-get install -y make autoconf automake ffmpeg libtool pkg-config python3 wget
RUN python3 -m pip install corpus-replicator
RUN git clone --depth 1 https://gitlab.xiph.org/xiph/ogg.git
RUN git clone --depth 1 https://gitlab.xiph.org/xiph/vorbis.git
RUN corpus-replicator -o decode_corpus audio_vorbis_ogg_libvorbis.yml audio
# TODO: remove `people.xiph.org` lines once upstream build script is updated
RUN mkdir people.xiph.org/
RUN touch people.xiph.org/dummy.ogg
WORKDIR vorbis
COPY build.sh $SRC/

cp /opt/oss-fuzz/projects/$PROJECT_NAME/*.c $SRC/
cp /opt/oss-fuzz/projects/$PROJECT_NAME/*.cc $SRC/
zzzzzzzzzz


cp /opt/oss-fuzz/projects/$PROJECT_NAME/build.sh $SRC/

cd $SRC/
if [ ! -d "/home/hacker/$PROJECT_NAME" ]; then
   mkdir /home/hacker/$PROJECT_NAME
   cp $SRC/zzzzzzzzzz.c $SRC/newfuzzer.c
   cp $SRC/*.c /home/hacker/$PROJECT_NAME
   cp $SRC/*.cc /home/hacker/$PROJECT_NAME
   cp /opt/oss-fuzz/projects/$PROJECT_NAME/build.sh /home/hacker/$PROJECT_NAME
else
   cp /home/hacker/$PROJECT_NAME/*.c $SRC
   cp /home/hacker/$PROJECT_NAME/*.cc $SRC
   cp /home/hacker/$PROJECT_NAME/build.sh $SRC
fi
#patch -tuN /src/build.sh -i /challenge/build.patch -r -
compile