#!/opt/pwn.college/bash 
INITIAL=32
TARGET=37
sudo cp /usr/local/sbin/loc_count /challenge/loc_count
sudo chmod 4755 /challenge/loc_count
time sudo -H -u hacker bash -c "/challenge/loc_count $*"
/usr/local/sbin/announce $INITIAL $? 
if [ "$?" -gt "$TARGET" ]; then
    echo
    echo Congratulations!  But make sure you also submit your improvements to Google!
    cat /flag
fi
if compgen -G "/out/crash*" > /dev/null; then
    echo
    echo "Crashes detected within the /out directory!"
    echo
fi
