#!/opt/pwn.college/bash
. /usr/local/sbin/eafl
export PROJECT_NAME=libtpms
export SANITIZER=$1
[ -z "$SANITIZER" ] && export SANITIZER='none'
cd $SRC

apt-get update && \
        apt-get install -y \
        make autoconf automake libtool \
        libstdc++-9-dev \
        libssl-dev libseccomp-dev pkg-config
git clone --depth 1 https://github.com/stefanberger/libtpms libtpms

cp -r /opt/fuzz-targets/cyclonedds /src/cyclonedds

cp /opt/oss-fuzz/projects/$PROJECT_NAME/build.sh $SRC/

cd $SRC/libtpms

sudo --preserve-env compile
drivers
