#!/opt/pwn.college/bash 
echo 70 > /tmp/initial
echo 75 > /tmp/target
if [ "$1" = "afl" ]; then
    . /usr/local/sbin/eafl
    shift
else
    . /usr/local/sbin/e
fi
export PROJECT_NAME=avahi
export SANITIZER=$1
[ -z "$SANITIZER" ] && export SANITIZER='none'
cd $SRC

#apt-get update && \
#   apt-get install -y autoconf gettext libtool m4 automake pkg-config libexpat-dev libexpat-dev:i386
#git clone --depth 1 https://github.com/swirsz/avahi
#git clone --depth 1 https://github.com/lathiat/avahi
cp -r /opt/fuzz-targets/avahi $SRC

cp /opt/oss-fuzz/projects/$PROJECT_NAME/build.sh $SRC/
cp /challenge/.fuzz-packet_seed_corpus.zip $OUT/fuzz-packet_seed_corpus.zip
patch -tuN $SRC/avahi/fuzz/oss-fuzz.sh -i /challenge/.oss-fuzz.patch -r -
cd $SRC/$PROJECT_NAME
if [ ! -d "/home/hacker/training-newdriver" ]; then
   mkdir /home/hacker/training-newdriver
   cp $SRC/$PROJECT_NAME/fuzz/fuzz-consume-record.c $SRC/$PROJECT_NAME/fuzz/fuzz-newfuzzer.c
   cp $SRC/$PROJECT_NAME/fuzz/*.c /home/hacker/training-newdriver
   cp /opt/oss-fuzz/projects/$PROJECT_NAME/build.sh /home/hacker/training-newdriver
   chown -R hacker /home/hacker/training-newdriver
else
   cp /home/hacker/training-newdriver/*.c $SRC/$PROJECT_NAME/fuzz
   cp /home/hacker/training-newdriver/build.sh $SRC
fi
mkdir -p /home/hacker/.log
[ ! "$SANITIZER" = "introspector" ] && [ ! "$SANITIZER" = "coverage" ] && zip -ry /home/hacker/.log/$(TZ=US/Arizona date +"%F--%H-%M-%S")-training-newdriver /home/hacker/training-newdriver
sudo --preserve-env compile
drivers
