#!/opt/pwn.college/bash
export PROJECT_NAME=avahi
/challenge/.loc_count
cd /src/$PROJECT_NAME
cp /home/hacker/training-newdriver/*.c /src/$PROJECT_NAME/fuzz
cp /challenge/.fuzz-packet_seed_corpus.zip $OUT/fuzz-packet_seed_corpus.zip
patch -tuN /src/avahi/fuzz/oss-fuzz.sh -i /challenge/.oss-fuzz.patch -r -
/challenge/.fi $PROJECT_NAME
