#!/opt/pwn.college/bash 
INITIAL=70
TARGET=75
time sudo -H -u hacker bash -c "/challenge/.loc_count $*"
/usr/local/sbin/announce $INITIAL $? 
if [ "$?" -ge "$TARGET" ]; then
    echo
    echo Congratulations!
    cat /flag
fi
if compgen -G "/out/crash*" > /dev/null; then
    echo
    echo "Crashes detected within the /out directory!"
    echo
fi
