#!/opt/pwn.college/bash
export PROJECT_NAME=sqlite3
/challenge/.loc_count
cd /src

rm -rf $PROJECT_NAME
#apt-get update && apt-get install -y make autoconf automake libtool curl tcl zlib1g-dev

# We won't be able to poll fossil for changes, so this will build
# only once a day.
mkdir /src/sqlite3 && \
    cd /src/sqlite3 && \
    cp -r /opt/fuzz-targets/sqlite3.tar.gz /src/sqlite3 && \
    tar xzf sqlite3.tar.gz
    #curl 'https://www.sqlite.org/src/tarball?uuid=trunk' -o sqlite3.tar.gz && \
    #tar xzf sqlite3.tar.gz

cd /src
find /src/sqlite3 -name "*.test" | xargs zip /src/ossfuzz_seed_corpus.zip

cp /home/hacker/$PROJECT_NAME/*.zip /src/sqlite3/test
cp /home/hacker/$PROJECT_NAME/*.options /src/sqlite3/test
cp /home/hacker/$PROJECT_NAME/*.c /src/sqlite3/test
cp /home/hacker/$PROJECT_NAME/main.mk  /src/sqlite3/

cd /src/$PROJECT_NAME

/challenge/.fi $PROJECT_NAME
