#!/bin/sh
. /usr/local/sbin/e
export PROJECT_NAME=gfwx
[ -z "$SANITIZER" ] && export SANITIZER='none'
cd $SRC

apt-get update && apt-get install -y make autoconf automake libtool
git clone --depth 1 https://github.com/guidovranken/gfwx-fuzzers.git gfwx

cp /opt/oss-fuzz/projects/$PROJECT_NAME/build.sh $SRC/
cd $SRC/$PROJECT_NAME
compile
