#!/bin/sh
. /usr/local/sbin/e
export PROJECT_NAME=gfwx
[ -z "$SANITIZER" ] && export SANITIZER='none'
cd $SRC

mkdir /src/tmp
cp -f /src/gfwx/*.src /src/tmp
rm -rf /src/$PROJECT_NAME
#apt-get update && apt-get install -y make autoconf automake libtool
git clone --depth 1 https://github.com/guidovranken/gfwx-fuzzers.git gfwx
mv -f /src/tmp/* /src/gfwx
rmdir /src/tmp

cp /opt/oss-fuzz/projects/$PROJECT_NAME/build.sh $SRC/
cd $SRC/$PROJECT_NAME
if [ ! -d "/home/hacker/$PROJECT_NAME" ]; then
   mkdir ~/$PROJECT_NAME
   cp $SRC/$PROJECT_NAME/yyyyyyyyyyyy/zzzzzzzzzzzzzzzzz.c $SRC/$PROJECT_NAME/yyyyyyyyyyyy/newfuzzer.c
   cp $SRC/$PROJECT_NAME/yyyyyyyyyyyy/*.c ~/$PROJECT_NAME
else
   cp ~/$PROJECT_NAME/*.c $SRC/$PROJECT_NAME/yyyyyyyyyyyy
fi
#patch -tuN /src/build.sh -i /challenge/build.patch -r -
compile
