#!/bin/sh
. /usr/local/sbin/e
export PROJECT_NAME=gfwx
[ -z "$SANITIZER" ] && export SANITIZER='none'
cd $SRC

mkdir /src/tmp
cp -f /src/gfwx/*.src /src/tmp
rm -rf /src/$PROJECT_NAME
#apt-get update && apt-get install -y make autoconf automake libtool
git clone --depth 1 https://github.com/guidovranken/gfwx-fuzzers.git gfwx
mv -f /src/tmp/* /src/gfwx
rmdir /src/tmp

cp /opt/oss-fuzz/projects/$PROJECT_NAME/build.sh $SRC/
cd $SRC/$PROJECT_NAME
if [ ! -d "/home/hacker/$PROJECT_NAME" ]; then
   mkdir ~/$PROJECT_NAME
   patch -tuN $SRC/$PROJECT_NAME/Makefile -i /challenge/Makefile.patch -r -
   patch -tuN $SRC/build.sh -i /challenge/build.patch -r -
   cp $SRC/$PROJECT_NAME/decoder.cpp $SRC/$PROJECT_NAME/newfuzzer.cpp
   cp $SRC/$PROJECT_NAME/*.cpp ~/$PROJECT_NAME
   cp $SRC/$PROJECT_NAME/Makefile ~/$PROJECT_NAME
else
   cp ~/$PROJECT_NAME/*.cpp $SRC/$PROJECT_NAME
   cp ~/$PROJECT_NAME/Makefile $SRC/$PROJECT_NAME
fi
compile
