#!/bin/bash
export PROJECT_NAME=gfwx
/usr/local/sbin/loc_count $PROJECT_NAME

cd /src
mkdir /src/tmp
cp /src/gfwx/Makefile /src/tmp
cp /src/gfwx/*.zip /src/tmp
cp /src/gfwx/*.cpp /src/tmp
rm -rf /src/$PROJECT_NAME
#apt-get update && apt-get install -y make autoconf automake libtool
git clone --depth 1 https://github.com/guidovranken/gfwx-fuzzers.git gfwx
mv -f /src/tmp/* /src/gfwx
rmdir /src/tmp

cd /src/$PROJECT_NAME
/usr/local/sbin/fi $PROJECT_NAME
