--- Make	2023-07-13 04:08:39.685431454 +0000
+++ Makefile	2023-07-13 04:10:54.461089941 +0000
@@ -4,3 +4,6 @@
 	$(CXX) $(CXXFLAGS) -std=c++17 -D_GLIBCXX_DEBUG -Wall -Wextra -I fuzzing-headers/include encoder.cpp $(LIB_FUZZING_ENGINE) -o fuzzer-encoder
 fuzzer-decoder : decoder.cpp
 	$(CXX) $(CXXFLAGS) -std=c++17 -D_GLIBCXX_DEBUG -Wall -Wextra -I fuzzing-headers/include decoder.cpp $(LIB_FUZZING_ENGINE) -o fuzzer-decoder
+newfuzzer : newfuzzer.cpp
+	$(CXX) $(CXXFLAGS) -std=c++17 -D_GLIBCXX_DEBUG -Wall -Wextra -I fuzzing-headers/include newfuzzer.cpp $(LIB_FUZZING_ENGINE) -o newfuzzer
+
