#!/bin/sh
. /usr/local/sbin/e
export PROJECT_NAME=bzip2
[ -z "$SANITIZER" ] && export SANITIZER='none'
cd $SRC

rm -rf /src/$PROJECT_NAME
rm -rf /src/$PROJECT_NAME-tests
#apt-get update && apt-get install -y make autoconf automake libtool wget
git clone git://sourceware.org/git/bzip2.git
git clone git://sourceware.org/git/bzip2-tests.git

cp /challenge/newfuzzer.c $SRC/newfuzzer.c

cp /opt/oss-fuzz/projects/$PROJECT_NAME/build.sh $SRC/
cp /opt/oss-fuzz/projects/$PROJECT_NAME/*.c $SRC/
if [ ! -d "/home/hacker/training-parameters" ]; then
   mkdir /home/hacker/training-parameters
   cp $SRC/*.c /home/hacker/training-parameters
   cp /opt/oss-fuzz/projects/$PROJECT_NAME/build.sh /home/hacker/$PROJECT_NAME
else
   cp /home/hacker/training-parameters/*.c $SRC
   cp /home/hacker/$PROJECT_NAME/build.sh $SRC
fi

cd $SRC
compile
