#!/opt/pwn.college/bash 
INITIAL=74
TARGET=75
sudo -H -u hacker bash -c /usr/local/sbin/loc_count
/usr/local/sbin/loc newfuzzer
/usr/local/sbin/announce $INITIAL $? 
if [ "$?" -gt "$TARGET" ]; then
    echo
    echo Congratulations!
    cat /flag
fi
