#!/bin/sh
. /usr/local/sbin/e
export PROJECT_NAME=minizip
[ -z "$SANITIZER" ] && export SANITIZER='none'
cd $SRC

#apt-get update && apt-get install -y make cmake pkg-config libssl-dev:i386
git clone -b develop https://github.com/zlib-ng/minizip-ng minizip

cp /opt/oss-fuzz/projects/$PROJECT_NAME/build.sh $SRC/
cd $SRC/$PROJECT_NAME
if [ ! -d "/home/hacker/$PROJECT_NAME" ]; then
   mkdir ~/training-locate
   cp $SRC/$PROJECT_NAME/test/fuzz/unzip_fuzzer.c $SRC/$PROJECT_NAME/test/fuzz/new_fuzzer.c
   cp $SRC/$PROJECT_NAME/test/fuzz/*.c ~/training-locate
else
   cp ~/training-locate/*.c $SRC/$PROJECT_NAME/test/fuzz
fi
patch -tuN /src/minizip/CMakeLists.txt -i /challenge/CMakeLists.patch -r -
compile
