#!/opt/pwn.college/bash
export PROJECT_NAME=elfutils
/challenge/.loc_count
cd /src

rm -rf elfutils
cp -r /opt/fuzz-targets/elfutils /src
cp -r /opt/fuzz-targets/zlib /src/$PROJECT_NAME

/challenge/.fi $PROJECT_NAME
