#!/opt/pwn.college/bash
rm /out/crash-*
rm /out/timeout-*
sudo -H -u hacker bash -c /usr/local/sbin/loc_count $1
if compgen -G "/out/crash-*" > /dev/null; then
    echo
    echo "Crashes detected within the /out directory!"
    echo
elif compgen -G "/out/timeout-*" > /dev/null; then
    echo
    echo "Timeouts detected within the /out directory!"
    echo
else
    echo
    echo Congratulations!  No crashes or timeout are detected.
    cat /flag
fi
