#!/opt/pwn.college/bash
export PROJECT_NAME=$1
/challenge/loc
/challenge/build introspector
if [ "$?" -gt 0 ]; then
	    exit 1
fi
DRIVERS=(/src/inspector/*.covreport)

rm -rf /out/introspector-report
mkdir -p /out/introspector-report
mv /out/inspector /out/introspector-report/inspector
mv /out/report /out/introspector-report/inspector/covreport

# fix delays caused by internet references to unpkg.com & googletagmanager.com
patch -tuN /out/introspector-report/inspector/fuzz_report.html -i /usr/local/sbin/fuzz_report.patch -r -

for f in /out/introspector-report/inspector/calltree_view*.html ; do patch -tuN "$f" -i /usr/local/sbin/calltree_view.patch -r -; done
for f in /out/report_target/*; do mv $f /out/introspector-report/inspector/covreport/$(basename $f); done

zip -y /home/hacker/.log/$(TZ=US/Arizona date +"%F--%H-%M-%S")-fi /out/introspector-report/inspector/fuzz_report.html
echo
echo Workspace:
echo  Coverage: https://pwn.college/workspace/code/proxy/8008/covreport
echo  Fuzz-Introspector: https://pwn.college/workspace/code/proxy/8008/fuzz_report.html
echo
echo Virtual Desktop under Applications/Web Browser:
echo  Coverage: http://127.0.0.1:8008/covreport
echo  Fuzz-Introspector: http://127.0.0.1:8008/fuzz_report.html
echo
echo If you encounter errors, run /challenge/fuzz-introspector under shell or Workspace first, then view report on Desktop/Web Browser
echo 
python3 -m http.server 8008 --directory /out/introspector-report/inspector/
