#!/opt/pwn.college/bash
. /usr/local/sbin/e
cp /home/hacker/fuzz-dojo/bounded_resource.h /usr/local/include/
if [ "$?" -gt 0 ]; then
    exit 1
fi
export LABEL=$1
export PROJECT_NAME=libjpeg-turbo
export SANITIZER=$1
if [ -z "$SANITIZER" ]; then
    export SANITIZER='none'
    export LABEL='none'$LABEL
fi

if [ ! -d "/src-orig" ]; then
#----------------------------------------------------------------------
    set -x
    cd $SRC
    apt-get update && apt-get install -y make yasm cmake
    git clone --depth 1 https://github.com/libjpeg-turbo/fuzz
    
    cd $SRC
    cat fuzz/branches.txt | while read branch; do \
      git clone --depth 1 https://github.com/libjpeg-turbo/libjpeg-turbo -b $branch libjpeg-turbo.$branch; \
    done

    cd $SRC
    git clone --depth 1 https://github.com/libjpeg-turbo/seed-corpora
    cd seed-corpora && zip -r ../decompress_fuzzer_seed_corpus.zip afl-testcases/jpeg* bugs/decompress*
    cd $SRC
    cat fuzz/branches.txt | while read branch; do \
      zip -r decompress_fuzzer_seed_corpus.zip libjpeg-turbo.$branch/testimages/*.jpg; \
    done
    
    cd $SRC
    cd seed-corpora && zip -r ../compress_fuzzer_seed_corpus.zip afl-testcases/bmp afl-testcases/gif* afl-testcases/targa bugs/compress*
    cd $SRC
    cat fuzz/branches.txt | while read branch; do \
      zip -r compress_fuzzer_seed_corpus.zip libjpeg-turbo.$branch/testimages/*.bmp libjpeg-turbo.$branch/testimages/*.ppm libjpeg-turbo.$branch/testimages/*.pgm; \
    done
    
    cd $SRC
    rm -rf seed-corpora

    #RUN apt-get update && apt-get install -y cmake
    #rm -rf $PROJECT_NAME
    #git clone --depth 1 -b develop https://github.com/nlohmann/json.git
    #cp -r /downloads/cjson $SRC

    cp /opt/oss-fuzz/projects/$PROJECT_NAME/build.sh $SRC/

    #patch -tuN $SRC/$PROJECT_NAME/fuzzing/ossfuzz.sh -i /challenge/.ossfuzz.patch -r -
    #cp $SRC/$PROJECT_NAME/fuzzing/cjson_read_fuzzer.c $SRC/$PROJECT_NAME/fuzzing/ewfuzzer.c
#----------------------------------------------------------------------
    cd /
    build-cleanup
fi
build-srcfolders
mv /src-$LABEL /src

cd $SRC
#rm -rf $SRC/$PROJECT_NAME/build

#----------------------------------------------------------------------
if [ ! -d "/home/hacker/fuzz-dojo/$PROJECT_NAME" ]; then
   mkdir -p /home/hacker/fuzz-dojo/$PROJECT_NAME
   cp -r $SRC/libjpeg-turbo.main/fuzz/* /home/hacker/fuzz-dojo/$PROJECT_NAME
   cp $SRC/build.sh /home/hacker/fuzz-dojo/$PROJECT_NAME
else
   cp -r /home/hacker/fuzz-dojo/$PROJECT_NAME/* $SRC/libjpeg-turbo.3.0.x/fuzz
   cp -r /home/hacker/fuzz-dojo/$PROJECT_NAME/* $SRC/libjpeg-turbo.3.1.x/fuzz
   cp -r /home/hacker/fuzz-dojo/$PROJECT_NAME/* $SRC/libjpeg-turbo.main/fuzz
   cp /home/hacker/fuzz-dojo/$PROJECT_NAME/build.sh $SRC
fi
#----------------------------------------------------------------------
if [ "$4" = "understanding" ]; then
    understanding $2 $3
elif [ "$4" = "planning" ]; then
    planning $2 $3
else
    fuzzlog
    compile
    drivers
fi
mv /src /src-$LABEL
