#!/opt/pwn.college/bash
echo 39 > /tmp/initial
echo 44 > /tmp/target
if [ "$1" = "afl" ]; then
    . /usr/local/sbin/eafl
    shift
else
    . /usr/local/sbin/e
fi
export PROJECT_NAME=curl
export SANITIZER=$1
[ -z "$SANITIZER" ] && export SANITIZER='none'
cd $SRC

rm -rf $SRC/curl
rm -rf $SRC/curl_install
rm -rf $SRC/curl_fuzzer
rm -rf $SRC/nghttp2
rm -rf $SRC/openssl
rm -rf $SRC/zlib
#git clone --depth 1 https://github.com/curl/curl.git $SRC/$PROJECT_NAME
#git clone --depth 1 https://github.com/curl/curl-fuzzer.git $SRC/curl_fuzzer
cp -r /opt/fuzz-targets/curl $SRC
cp -r /opt/fuzz-targets/curl_fuzzer $SRC
cp -r /opt/fuzz-targets/zlib $SRC
cp -r /opt/fuzz-targets/openssl32 $SRC/openssl
cp -r /opt/fuzz-targets/nghttp2 $SRC
# Use curl-fuzzer's scripts to get latest dependencies.
#$SRC/curl_fuzzer/scripts/ossfuzz.sh

cp /opt/oss-fuzz/projects/$PROJECT_NAME/build.sh $SRC/

patch -tuN $SRC/curl_fuzzer/fuzz_targets -i /challenge/.fuzz_targets.patch -r -
#patch -tuN $SRC/build.sh -i /challenge/.build.patch -r -
cd $SRC/curl_fuzzer
if [ ! -d "/home/hacker/$PROJECT_NAME" ]; then
   mkdir /home/hacker/$PROJECT_NAME
   cp $SRC/curl_fuzzer/curl_fuzzer.cc $SRC/curl_fuzzer/new_fuzzer.cc
   cp $SRC/curl_fuzzer/*.cc /home/hacker/$PROJECT_NAME
   cp $SRC/curl_fuzzer/*.sh /home/hacker/$PROJECT_NAME
   cp $SRC/curl_fuzzer/*.py /home/hacker/$PROJECT_NAME
   cp $SRC/curl_fuzzer/Makefile.am /home/hacker/$PROJECT_NAME
   cp $SRC/curl_fuzzer/scripts/fuzz_targets /home/hacker/$PROJECT_NAME
   chown -R hacker /home/hacker/$PROJECT_NAME
else
   cp /home/hacker/$PROJECT_NAME/* $SRC/curl_fuzzer
fi
mkdir -p /home/hacker/.log
[ ! "$SANITIZER" = "introspector" ] && [ ! "$SANITIZER" = "coverage" ] && zip -ry /home/hacker/.log/$(TZ=US/Arizona date +"%F--%H-%M-%S")-$PROJECT_NAME /home/hacker/$PROJECT_NAME
sudo --preserve-env compile
drivers
