#!/opt/pwn.college/bash
echo 68 > /tmp/initial
echo 73 > /tmp/target
if [ "$1" = "afl" ]; then
    . /usr/local/sbin/eafl
    shift
else
    . /usr/local/sbin/e
fi
export PROJECT_NAME=xz
export SANITIZER=$1
[ -z "$SANITIZER" ] && export SANITIZER='none'
cd $SRC

#apt-get install -y make autoconf autopoint libtool zip
#git clone https://git.tukaani.org/xz.git $SRC/xz
cp -r /opt/fuzz-targets/xz $SRC

cp /opt/oss-fuzz-new/projects/$PROJECT_NAME/build.sh $SRC/

#patch -tuN $SRC/xz/tests/ossfuzz/Makefile -i /challenge/.Makefile.patch -r -
cd $SRC/$PROJECT_NAME
if [ ! -d "/home/hacker/$PROJECT_NAME" ]; then
   mkdir /home/hacker/$PROJECT_NAME
   cp $SRC/$PROJECT_NAME/tests/ossfuzz/fuzz_encode_stream.c $SRC/$PROJECT_NAME/tests/ossfuzz/newfuzzer.c
   cp $SRC/$PROJECT_NAME/tests/ossfuzz/*.c /home/hacker/$PROJECT_NAME
   cp $SRC/build.sh /home/hacker/$PROJECT_NAME
   chown -R hacker /home/hacker/$PROJECT_NAME
else
   cp /home/hacker/$PROJECT_NAME/*.c $SRC/$PROJECT_NAME/tests/ossfuzz
   cp /home/hacker/$PROJECT_NAME/build.sh $SRC
fi
mkdir -p /home/hacker/.log
[ ! "$SANITIZER" = "introspector" ] && [ ! "$SANITIZER" = "coverage" ] && zip -ry /home/hacker/.log/$(TZ=US/Arizona date +"%F--%H-%M-%S")-$PROJECT_NAME /home/hacker/$PROJECT_NAME
sudo --preserve-env compile
drivers
