#!/opt/pwn.college/bash
. /usr/local/sbin/e
export PROJECT_NAME=vlc
export SANITIZER=$1
[ -z "$SANITIZER" ] && export SANITIZER='none'
cd $SRC

rm -rf vlc
#apt-get update && apt-get install -y make autoconf automake libtool \
  pkg-config cmake flex bison gettext libglu1-mesa-dev 
git clone --depth 1 https://github.com/videolan/vlc vlc

cp /opt/oss-fuzz/projects/$PROJECT_NAME/build.sh $SRC/

#patch -tuN /home/hacker/$PROJECT_NAME/Makefile.am -i /challenge/Makefile.patch -r -
cd $SRC/$PROJECT_NAME
if [ ! -d "/home/hacker/$PROJECT_NAME" ]; then
   mkdir /home/hacker/$PROJECT_NAME
   cp $SRC/vlc/test/vlc-demux-libfuzzer.c $SRC/vlc/test/vlc-new-libfuzzer.c
   cp $SRC/vlc/test/Makefile.am /home/hacker/$PROJECT_NAME
   cp $SRC/vlc/test/*.c /home/hacker/$PROJECT_NAME
   cp /src/build.sh /home/hacker/$PROJECT_NAME
   chown -R hacker /home/hacker/$PROJECT_NAME
else
   cp /home/hacker/$PROJECT_NAME/*.c $SRC/vlc/test
   cp /home/hacker/$PROJECT_NAME/Makefile.am $SRC/vlc/test
   cp /home/hacker/$PROJECT_NAME/build.sh $SRC
fi
sudo --preserve-env compile