#!/bin/sh
. /usr/local/sbin/e
export PROJECT_NAME=libgd
[ -z "$SANITIZER" ] && export SANITIZER='none'
cd $SRC

rm -rf $SRC/$PROJECT_NAME
apt-get update && \
    apt-get install -y make autoconf automake libtool pkg-config libz-dev
git clone --depth 1 https://github.com/libgd/libgd
wget https://lcamtuf.coredump.cx/afl/demo/afl_testcases.tgz

cp /opt/oss-fuzz/projects/$PROJECT_NAME/build.sh $SRC/
cp /opt/oss-fuzz/projects/$PROJECT_NAME/*.cc $SRC/

cd $SRC/$PROJECT_NAME
compile