#!/opt/pwn.college/bash
if [ "$1" = "afl" ]; then
    . /usr/local/sbin/eafl
    shift
else
    . /usr/local/sbin/e
fi
export PROJECT_NAME=libsodium
export SANITIZER=$1
[ -z "$SANITIZER" ] && export SANITIZER='none'
cd $SRC

rm -rf $SRC/$PROJECT_NAME
#apt-get update && apt-get install -y make
#git clone --depth 1 https://github.com/jedisct1/libsodium.git --branch stable libsodium
cp -r /opt/fuzz-targets/libsodium /src

cp /opt/oss-fuzz/projects/$PROJECT_NAME/*.h $SRC/
cp /opt/oss-fuzz/projects/$PROJECT_NAME/*.cc $SRC/
cp /opt/oss-fuzz/projects/$PROJECT_NAME/build.sh $SRC/

#patch -tuN /src/build.sh -i /challenge/.build.patch -r -
cd $SRC/$PROJECT_NAME
if [ ! -d "/home/hacker/$PROJECT_NAME" ]; then
   mkdir /home/hacker/$PROJECT_NAME
   cp $SRC/secret_key_auth_fuzzer.cc $SRC/new_fuzzer.cc
   cp $SRC/*.cc /home/hacker/$PROJECT_NAME
   cp $SRC/*.h /home/hacker/$PROJECT_NAME
   cp /src/build.sh /home/hacker/$PROJECT_NAME
   chown -R hacker /home/hacker/$PROJECT_NAME
else
   cp /home/hacker/$PROJECT_NAME/*.cc $SRC
   cp /home/hacker/$PROJECT_NAME/*.h $SRC
   cp /home/hacker/$PROJECT_NAME/build.sh $SRC
fi
sudo --preserve-env compile
drivers