#!/bin/sh
. /usr/local/sbin/e
export PROJECT_NAME=pycryptodome
[ -z "$SANITIZER" ] && export SANITIZER='none'
cd $SRC

#apt-get update && apt-get install -y make autoconf automake libtool
rm -rf /src/$PROJECT_NAME
git clone https://github.com/Legrandin/pycryptodome.git

cp /opt/oss-fuzz/projects/$PROJECT_NAME/*_fuzzer.cc $SRC/
cp /opt/oss-fuzz/projects/$PROJECT_NAME/block_common.patch $SRC/pycryptodome/src

cp /opt/oss-fuzz/projects/$PROJECT_NAME/build.sh $SRC/
cd $SRC/$PROJECT_NAME/src
if [ ! -d "/home/hacker/$PROJECT_NAME" ]; then
   mkdir ~/$PROJECT_NAME
   cp $SRC/$PROJECT_NAME/yyyyyyyyyyyy/zzzzzzzzzzzzzzzzz.c $SRC/$PROJECT_NAME/yyyyyyyyyyyy/newfuzzer.c
   cp $SRC/$PROJECT_NAME/yyyyyyyyyyyy/*.c ~/$PROJECT_NAME
else
   cp ~/$PROJECT_NAME/*.c $SRC/$PROJECT_NAME/yyyyyyyyyyyy
fi
#patch -tuN /src/build.sh -i /challenge/build.patch -r -
compile
