#!/bin/sh
. /usr/local/sbin/e.sh
export PROJECT_NAME=pycryptodome
[ -z "$SANITIZER" ] && export SANITIZER='none'
cd $SRC

apt-get update && apt-get install -y make autoconf automake libtool
git clone --depth 1 https://github.com/Legrandin/pycryptodome.git

cp /opt/oss-fuzz/projects/$PROJECT_NAME/*_fuzzer.cc $SRC/
cp /opt/oss-fuzz/projects/$PROJECT_NAME/block_common.patch $SRC/pycryptodome/src

cp /opt/oss-fuzz/projects/$PROJECT_NAME/build.sh $SRC/
cd $SRC/$PROJECT_NAME/src
compile
