#!/opt/pwn.college/bash
export PROJECT_NAME=pycryptodome
/challenge/.loc_count
cd /src
rm -rf /src/$PROJECT_NAME
#git clone https://github.com/Legrandin/pycryptodome.git
cp -r /opt/fuzz-targets/pycryptodome /src/pycryptodome

cp /opt/oss-fuzz/projects/$PROJECT_NAME/block_common.patch /src/pycryptodome/src

cd /src/$PROJECT_NAME/src
/challenge/.fi $PROJECT_NAME
