#!/bin/bash
export DRIVERS=('Per-fuzzer coverage' 'md2_fuzzer' 'md4_fuzzer' 'ripemd160_fuzzer' 'md5_fuzzer' 'aes_fuzzer' 'sha384_fuzzer' 'sha224_fuzzer' 'sha256_fuzzer')
export PROJECT_NAME=pycryptodome
/usr/local/sbin/loc_count.sh $PROJECT_NAME "${DRIVERS[@]}"
cd /src/$PROJECT_NAME/src
/usr/local/sbin/fi.sh $PROJECT_NAME "${DRIVERS[@]}"



