#!/bin/sh
. /usr/local/sbin/e
export PROJECT_NAME=ninja
export SANITIZER=$1
[ -z "$SANITIZER" ] && export SANITIZER='none'
cd $SRC

#apt-get update && apt-get install -y cmake

git clone --depth 1 https://github.com/ninja-build/ninja

mv $SRC/ninja/misc/oss-fuzz/build.sh $SRC/
mv $SRC/ninja/misc/oss-fuzz/sample_ninja_build $SRC/

cd $SRC/$PROJECT_NAME
if [ ! -d "/home/hacker/$PROJECT_NAME" ]; then
   mkdir /home/hacker/$PROJECT_NAME
   cp $SRC/ninja/misc/manifest_fuzzer.cc $SRC/src/ninja/misc/new_fuzzer.cc
   cp $SRC/ninja/misc/*.cc /home/hacker/$PROJECT_NAME
   cp $SRC/ninja/misc/oss-fuzz/build.sh /home/hacker/$PROJECT_NAME
else
   cp /home/hacker/$PROJECT_NAME/* $SRC
fi
#patch -tuN /src/build.sh -i /challenge/build.patch -r -
compile