#!/bin/sh
. /usr/local/sbin/e
export PROJECT_NAME=ninja
export SANITIZER=$1
[ -z "$SANITIZER" ] && export SANITIZER='none'
cd $SRC

#apt-get update && apt-get install -y zzzzzzzzzz
RUN apt-get update && apt-get install -y cmake

RUN git clone --depth 1 https://github.com/ninja-build/ninja
WORKDIR ninja
RUN mv $SRC/ninja/misc/oss-fuzz/build.sh $SRC/
RUN mv $SRC/ninja/misc/oss-fuzz/sample_ninja_build $SRC/

cp /opt/oss-fuzz/projects/$PROJECT_NAME/*.c $SRC/
cp /opt/oss-fuzz/projects/$PROJECT_NAME/*.cc $SRC/
zzzzzzzzzz


cp /opt/oss-fuzz/projects/$PROJECT_NAME/build.sh $SRC/

cd $SRC/
if [ ! -d "/home/hacker/$PROJECT_NAME" ]; then
   mkdir /home/hacker/$PROJECT_NAME
   cp $SRC/zzzzzzzzzz.c $SRC/newfuzzer.c
   cp $SRC/*.c /home/hacker/$PROJECT_NAME
   cp $SRC/*.cc /home/hacker/$PROJECT_NAME
   cp /opt/oss-fuzz/projects/$PROJECT_NAME/build.sh /home/hacker/$PROJECT_NAME
else
   cp /home/hacker/$PROJECT_NAME/*.c $SRC
   cp /home/hacker/$PROJECT_NAME/*.cc $SRC
   cp /home/hacker/$PROJECT_NAME/build.sh $SRC
fi
#patch -tuN /src/build.sh -i /challenge/build.patch -r -
compile