#!/bin/sh
. /usr/local/sbin/e
export PROJECT_NAME=zopfli
export SANITIZER=$1
[ -z "$SANITIZER" ] && export SANITIZER='none'
cd $SRC

#apt-get update && apt-get install -y make autoconf automake libtool
git clone --depth 1 https://github.com/google/zopfli
cp /opt/oss-fuzz/projects/$PROJECT_NAME/*.cc $SRC/

#patch -tuN /src/build.sh -i /challenge/build.patch -r -
cp /opt/oss-fuzz/projects/$PROJECT_NAME/build.sh $SRC/
cd $SRC/$PROJECT_NAME
if [ ! -d "/home/hacker/$PROJECT_NAME" ]; then
   mkdir /home/hacker/$PROJECT_NAME
   cp $SRC/zopfli_compress_fuzzer.cc $SRC/new_fuzzer.cc
   cp $SRC/*.cc /home/hacker/$PROJECT_NAME
   cp /src/build.sh /home/hacker/$PROJECT_NAME
else
   cp /home/hacker/$PROJECT_NAME/*.cc $SRC
   cp /home/hacker/$PROJECT_NAME/build.sh $SRC
fi
compile
