#!/bin/bash
export PROJECT_NAME=zopfli
INITIAL=76
TARGET=81
/usr/local/sbin/loc_count $PROJECT_NAME
/usr/local/sbin/announce $INITIAL $? 
if [ "$?" -gt "$TARGET" ]; then
    echo
    echo Congratulations!  But make sure you also submit your improvements to Google!
    cat /flag
fi
