#!/opt/pwn.college/bash
export PROJECT_NAME=libvnc
/challenge/.loc_count
cd /src
rm -rf /src/libvncserver
#git clone --depth 1 https://github.com/LibVNC/libvncserver.git
cp -r /opt/fuzz-targets/libvncserver /src

patch -tuN /src/libvncserver/CMakeLists.txt -i /challenge/.CMakeLists.patch -r -
cp /home/hacker/$PROJECT_NAME/*.c /src/libvncserver/test
cp /home/hacker/$PROJECT_NAME/CMakeLists.txt /src/libvncserver
cd /src/libvncserver
/challenge/.fi $PROJECT_NAME
