#!/bin/sh
. /usr/local/sbin/e.sh
export PROJECT_NAME=pcre2
[ -z "$SANITIZER" ] && export SANITIZER='none'
cd $SRC

apt-get update && apt-get install -y make autoconf automake libtool subversion
git clone https://github.com/PCRE2Project/pcre2 pcre2

cp /opt/oss-fuzz/projects/$PROJECT_NAME/build.sh $SRC/
cd $SRC/$PROJECT_NAME
compile