#!/bin/bash
export PROJECT_NAME=libssh
/usr/local/sbin/loc_count
cd /src
rm -rf /src/$PROJECT_NAME
git clone --depth=1 https://git.libssh.org/projects/libssh.git
cd /src/$PROJECT_NAME
/usr/local/sbin/fi $PROJECT_NAME
