#!/opt/pwn.college/bash
if [ "$1" = "afl" ]; then
    . /usr/local/sbin/eafl
    shift
    export LABEL=$1$FUZZING_ENGINE
else
    . /usr/local/sbin/e
    export LABEL=$1
fi
export PROJECT_NAME=bzip2
export SANITIZER=$1
if [ -z "$SANITIZER" ]; then
    export SANITIZER='none'
    export LABEL='none'$LABEL
fi

if [ ! -d "/src-orig" ]; then
#----------------------------------------------------------------------
    rm -rf $SRC/$PROJECT_NAME
    rm -rf $SRC/$PROJECT_NAME-tests
    #apt-get update && apt-get install -y make autoconf automake libtool wget
    #git clone https://github.com/swirsz/bzip2
    #git clone git://sourceware.org/git/bzip2-tests.git
    cp -r /downloads/swbzip2 $SRC/bzip2
    cp -r /downloads/bzip2-tests $SRC

    cp /challenge/newfuzzer.c $SRC/newfuzzer.c

    cp /opt/oss-fuzz/projects/$PROJECT_NAME/build.sh $SRC/
    cp /opt/oss-fuzz/projects/$PROJECT_NAME/*.c $SRC/

#----------------------------------------------------------------------
    build-cleanup
fi
build-srcfolders
mv /src-$LABEL /src

cd $SRC
#----------------------------------------------------------------------
if [ ! -d "/home/hacker/fuzz-dojo/training-sanitizer" ]; then
   mkdir -p /home/hacker/fuzz-dojo/training-sanitizer
   cp $SRC/*.c /home/hacker/fuzz-dojo/training-sanitizer
   cp /opt/oss-fuzz/projects/$PROJECT_NAME/build.sh /home/hacker/fuzz-dojo/training-sanitizer
else
   cp /home/hacker/fuzz-dojo/training-sanitizer/*.c $SRC
   cp /home/hacker/fuzz-dojo/training-sanitizer/build.sh $SRC
fi
#----------------------------------------------------------------------

mkdir -p /home/hacker/.log
[ ! "$SANITIZER" = "introspector" ] && [ ! "$SANITIZER" = "coverage" ] && zip -ry /home/hacker/.log/$(TZ=US/Arizona date +"%F--%H-%M-%S")-training-sanitizer /home/hacker/fuzz-dojo/training-sanitizer
compile
drivers
find $SRC -not -user hacker -print | xargs -n 100 -P 8 chown hacker:hacker /home/hacker/fuzz-dojo /home/hacker/.log /out
mv /src /src-$LABEL
