#!/opt/pwn.college/bash 
INITIAL=45
TARGET=45
sudo cp /usr/local/sbin/loc_count /challenge/loc_count
sudo chmod 4755 /challenge/loc_count
time sudo -H -u hacker bash -c "/challenge/loc_count $*"
echo
echo newfuzzer
/usr/local/sbin/loc-calc newfuzzer
/usr/local/sbin/announce $INITIAL $? 
if [ "$?" -ge "$TARGET" ]; then
    echo
    echo Congratulations! But you will need to run /challenge/loc2 to win.
fi
if compgen -G "/out/crash*" > /dev/null; then
    echo
    echo "Crashes detected within the /out directory!"
    echo
fi
