#!/bin/bash
export PROJECT_NAME=valijson
/usr/local/sbin/loc_count
cd /src

rm -rf valijson
git clone --depth 1 https://github.com/tristanpenman/valijson
cp /src/valijson/tests/fuzzing/oss-fuzz-build.sh $SRC/build.sh
# This is to fix Fuzz Introspector build by using LLVM old pass manager
# re https://github.com/ossf/fuzz-introspector/issues/305
export OLD_LLVMPASS=1

cd /src/$PROJECT_NAME
/usr/local/sbin/fi $PROJECT_NAME
