#!/bin/sh
. /usr/local/sbin/e
export PROJECT_NAME=zlib
[ -z "$SANITIZER" ] && export SANITIZER='none'
cd $SRC

#apt-get update && apt-get install -y make autoconf automake libtool
git clone --depth 1 -b develop https://github.com/swirsz/zlib

cp /opt/oss-fuzz/projects/$PROJECT_NAME/*_fuzzer.c* $SRC/

cp /opt/oss-fuzz/projects/$PROJECT_NAME/build.sh $SRC/
cd $SRC/$PROJECT_NAME
if [ ! -d "/home/hacker/$PROJECT_NAME" ]; then
   mkdir /home/hacker/$PROJECT_NAME
   cp $SRC/minigzip_fuzzer.c $SRC/new_fuzzer.c
   cp $SRC/*.c* /home/hacker/$PROJECT_NAME
   cp /opt/oss-fuzz/projects/$PROJECT_NAME/build.sh /home/hacker/$PROJECT_NAME
else
   cp /home/hacker/$PROJECT_NAME/*.c* $SRC
   cp /home/hacker/$PROJECT_NAME/build.sh $SRC
fi
#patch -tuN /src/build.sh -i /challenge/build.patch -r -
compile
