#!/bin/bash
export PROJECT_NAME=file
/usr/local/sbin/loc_count
cd /src
rm -rf $PROJECT_NAME
git clone --depth 1 https://github.com/file/file.git

cd /src/$PROJECT_NAME
/usr/local/sbin/fi $PROJECT_NAME
