#!/bin/sh
. /usr/local/sbin/e.sh
export PROJECT_NAME=libsodium
[ -z "$SANITIZER" ] && export SANITIZER='none'
cd $SRC

apt-get update && apt-get install -y make
git clone --depth 1 https://github.com/jedisct1/libsodium.git --branch stable libsodium

cp /opt/oss-fuzz/projects/$PROJECT_NAME/*.h $SRC/
cp /opt/oss-fuzz/projects/$PROJECT_NAME/*.cc $SRC/
cp /opt/oss-fuzz/projects/$PROJECT_NAME/build.sh $SRC/

cd $SRC/$PROJECT_NAME
compile