#!/opt/pwn.college/bash
. /usr/local/sbin/eafl
export PROJECT_NAME=libvpx
export SANITIZER=$1
[ -z "$SANITIZER" ] && export SANITIZER='none'
cd $SRC

apt-get update && apt-get install -y yasm wget gcc

git clone https://chromium.googlesource.com/webm/libvpx
wget https://storage.googleapis.com/downloads.webmproject.org/test_data/fuzzer/vpx_fuzzer_seed_corpus.zip

cp -r /opt/fuzz-targets/cyclonedds /src/cyclonedds
cp -r /opt/fuzz-targets/cyclonedds /src/cyclonedds

cp /opt/oss-fuzz/projects/$PROJECT_NAME/build.sh $SRC/
cp /opt/oss-fuzz/projects/$PROJECT_NAME/vpx_dec_fuzzer.dict $SRC/

cd $SRC/$PROJECT_NAME

sudo --preserve-env compile
drivers
