#!/opt/pwn.college/bash
echo 71 > /tmp/initial
echo 76 > /tmp/target
if [ "$1" = "afl" ]; then
    . /usr/local/sbin/eafl
    shift
else
    . /usr/local/sbin/e
fi
export PROJECT_NAME=bzip2
export SANITIZER=$1
[ -z "$SANITIZER" ] && export SANITIZER='none'
cd $SRC

rm -rf /src/$PROJECT_NAME
rm -rf /src/$PROJECT_NAME-tests
#apt-get update && apt-get install -y make autoconf automake libtool wget
#git clone https://github.com/swirsz/bzip2
#git clone git://sourceware.org/git/bzip2-tests.git
cp -r /opt/fuzz-targets/bzip2 /src
cp -r /opt/fuzz-targets/bzip2-tests /src

cp /challenge/newfuzzer.c $SRC/newfuzzer.c

cp /opt/oss-fuzz/projects/$PROJECT_NAME/build.sh $SRC/
cp /opt/oss-fuzz/projects/$PROJECT_NAME/*.c $SRC/
if [ ! -d "/home/hacker/training-calltree" ]; then
   mkdir /home/hacker/training-calltree
   cp $SRC/*.c /home/hacker/training-calltree
   cp /opt/oss-fuzz/projects/$PROJECT_NAME/build.sh /home/hacker/training-calltree
   chown -R hacker /home/hacker/training-calltree
else
   cp /home/hacker/training-calltree/*.c $SRC
   cp /home/hacker/training-calltree/build.sh $SRC
fi

cd $SRC
sudo --preserve-env compile
drivers
