#!/bin/bash
. /usr/local/sbin/e
export PROJECT_NAME=bzip2
[ -z "$SANITIZER" ] && export SANITIZER='none'
cd $SRC

rm -rf /src/$PROJECT_NAME
rm -rf /src/$PROJECT_NAME-tests
#apt-get update && apt-get install -y make autoconf automake libtool wget
git clone git://sourceware.org/git/bzip2.git
git clone git://sourceware.org/git/bzip2-tests.git

cp /challenge/newfuzzer.c $SRC/newfuzzer.c

cp /opt/oss-fuzz/projects/$PROJECT_NAME/build.sh $SRC/
cp /opt/oss-fuzz/projects/$PROJECT_NAME/*.c $SRC/
if [ ! -d "~/training-calltree" ]; then
   mkdir ~/training-calltree
   cp $SRC/*.c ~/training-calltree
   echo 11111111111111
else
   cp ~/training-calltree/*.c $SRC
   echo 2222222222222222
fi

cd $SRC
compile
