@@ -24,7 +24,7 @@
 # You may add extra compiler flags like this:
 CXXFLAGS += -std=c++11
 
-all: do_stuff_unittest do_stuff_fuzzer
+all: do_stuff_unittest do_stuff_fuzzer new_fuzzer
 
 clean:
 	rm -fv *.a *.o *unittest *_fuzzer *_seed_corpus.zip crash-* *.zip
@@ -44,6 +44,10 @@
 	${CXX} ${CXXFLAGS} $< my_api.a ${LIB_FUZZING_ENGINE} -o $@
 	zip -q -r do_stuff_fuzzer_seed_corpus.zip do_stuff_test_data
 
+new_fuzzer: new_fuzzer.cpp my_api.a standalone_fuzz_target_runner.o
+	${CXX} ${CXXFLAGS} $< my_api.a ${LIB_FUZZING_ENGINE} -o $@
+	zip -q -r new_fuzzer_seed_corpus.zip do_stuff_test_data
+
 
 # The library itself.
 my_api.a: my_api.cpp my_api.h
