#!/usr/bin/env python3
import json
import sys

print("###\n### Welcome to /challenge/"+sys.argv[0]+"!\n###\n")
print("In this challenge, you have a working fuzz driver that improve code coverage")
print("by calling functions higher in the call tree. Examine the source code of the")
print("current fuzz driver and the source code of the project to find 2 different")
print("function that can be swapped for similar functions.\n\n")

summary_file = "/out/fuzzer_stats/newfuzzer.json"
try:
    with open(summary_file, "r") as fj:
        content = json.load(fj)
        for dd in content['data']:
            filenames = dd.get('files')
            for files in filenames:
                if files.get('filename') == "/src/bzip2/bzlib.c":
                    if files['summary']['branches']['covered'] == 143:
                        print("2 functions can be called higher in the calltree")
                    if files['summary']['branches']['covered'] == 144:
                        print("1 more function can be called higher in the calltree")
                    if files['summary']['branches']['covered'] == 145:
                        print("Congratulations")
                        with open("/flag") as f:
                            print(f.read())
except:
    print("Missing "+summary_file)
    print("\nPlease run /challenge/loc first\n")
