#!/opt/pwn.college/bash 
TARGET=144
/challenge/check.py
if [ "$?" -gt "$TARGET" ]; then
    echo Additional functions could be called higher in the calltree.
else
    echo Congratulations
    cat /flag
fi