#!/opt/pwn.college/bash
if [ "$1" = "afl" ]; then
    . /usr/local/sbin/eafl
    shift
else
    . /usr/local/sbin/e
fi
export PROJECT_NAME=lighttpd1.4
export SANITIZER=$1
[ -z "$SANITIZER" ] && export SANITIZER='none'

if [ ! -d "/src-orig" ]; then
    rm -rf $SRC/$PROJECT_NAME
    #apt-get update && apt-get install -y libz-dev libpcre2-dev libtool pkg-config autoconf
    #git clone https://github.com/lighttpd/lighttpd1.4
    cp -r /opt/fuzz-targets/lighttpd1.4 $SRC
    cp $SRC/fuzz_burl.c $SRC/fuzz_new.c

    cp /opt/oss-fuzz-new/projects/lighttpd/build.sh $SRC/
    cp /opt/oss-fuzz-new/projects/lighttpd/fuzz_* $SRC/

    patch -tuN $SRC/build.sh -i /challenge/.build.patch -r -
    echo Please wait, initial setup
    chown -hR hacker:hacker $SRC/$PROJECT_NAME
    mv /src /src-orig
fi
if [ ! -d "/src-$SANITIZER" ]; then
    echo Please wait, initial setup
    cp -r /src-orig /src-$SANITIZER
fi
mv /src-$SANITIZER /src

cd $SRC/$PROJECT_NAME
if [ ! -d "/home/hacker/fuzz-dojo/$PROJECT_NAME" ]; then
   mkdir -p /home/hacker/fuzz-dojo/$PROJECT_NAME
   cp $SRC/*.c /home/hacker/fuzz-dojo/$PROJECT_NAME
   cp $SRC/build.sh /home/hacker/fuzz-dojo/$PROJECT_NAME
   chown -R hacker /home/hacker/fuzz-dojo/$PROJECT_NAME
else
   cp /home/hacker/fuzz-dojo/$PROJECT_NAME/*.c $SRC
   cp /home/hacker/fuzz-dojo/$PROJECT_NAME/build.sh $SRC
fi
mkdir -p /home/hacker/.log
[ ! "$SANITIZER" = "introspector" ] && [ ! "$SANITIZER" = "coverage" ] && zip -ry /home/hacker/.log/$(TZ=US/Arizona date +"%F--%H-%M-%S")-lighttpd /home/hacker/fuzz-dojo/$PROJECT_NAME
sudo --preserve-env compile
drivers
chown -hR hacker:hacker $SRC/$PROJECT_NAME
mv /src /src-$SANITIZER
