#!/opt/pwn.college/bash
. /usr/local/sbin/e
cp /home/hacker/fuzz-dojo/bounded_resource.h /usr/local/include/
if [ "$?" -gt 0 ]; then
    exit 1
fi
export LABEL=$1
export PROJECT_NAME=opus
export SANITIZER=$1
if [ -z "$SANITIZER" ]; then
    export SANITIZER='none'
    export LABEL='none'$LABEL
fi

if [ ! -d "/src-orig" ]; then
#----------------------------------------------------------------------
#RUN apt-get update && apt-get install -y make autoconf automake libtool wget

#RUN git clone --single-branch --branch ossfuzz https://gitlab.xiph.org/xiph/opus.git
#RUN wget https://opus-codec.org/static/testvectors/opus_testvectors.tar.gz
#WORKDIR opus
#COPY run_tests.sh build.sh $SRC/
#COPY *.cc tests/
#COPY *.h tests/

    cp -r /downloads/opus $SRC

    cp /downloads/opus_testvectors.tar.gz $SRC

    cp /opt/oss-fuzz/projects/opus/run_tests.sh $SRC
    cp /opt/oss-fuzz/projects/opus/build.sh $SRC
    cp /opt/oss-fuzz/projects/opus/*.cc $SRC/$PROJECT_NAME/tests
    cp /opt/oss-fuzz/projects/opus/*.h $SRC/$PROJECT_NAME/tests
    #cp /challenge/.fuzz-packet_seed_corpus.zip $OUT/fuzz-packet_seed_corpus.zip
    #patch -tuN $SRC/$PROJECT_NAME/ossfuzz.sh -i /challenge/.ossfuzz.patch -r -
    #patch -tuN $SRC/$PROJECT_NAME/Makefile.am -i /challenge/.Makefile.patch -r -
        
    #cp $SRC/$PROJECT_NAME/aspell_fuzzer.cpp $SRC/$PROJECT_NAME/new_fuzzer.cpp
#----------------------------------------------------------------------
    build-cleanup
fi
build-srcfolders
mv /src-$LABEL /src

cd $SRC/$PROJECT_NAME
#----------------------------------------------------------------------
if [ ! -d "/home/hacker/fuzz-dojo/$PROJECT_NAME" ]; then
   mkdir -p /home/hacker/fuzz-dojo/$PROJECT_NAME
   cp $SRC/$PROJECT_NAME/tests/*.cc /home/hacker/fuzz-dojo/$PROJECT_NAME
   cp $SRC/build.sh /home/hacker/fuzz-dojo/$PROJECT_NAME
else
   cp /home/hacker/fuzz-dojo/$PROJECT_NAME/* $SRC/$PROJECT_NAME/tests
   cp /home/hacker/fuzz-dojo/$PROJECT_NAME/build.sh $SRC
fi
#----------------------------------------------------------------------
if [ "$4" = "understanding" ]; then
    understanding $2 $3
elif [ "$4" = "planning" ]; then
    planning $2 $3
else
    fuzzlog
    compile
    drivers
fi
mv /src /src-$LABEL
