#!/bin/sh
. /usr/local/sbin/e
export PROJECT_NAME=curl
export SANITIZER=$1
[ -z "$SANITIZER" ] && export SANITIZER='none'
cd $SRC

rm -rf $SRC/curl
rm -rf $SRC/curl_install
rm -rf $SRC/curl_fuzzer
rm -rf $SRC/nghttp2
rm -rf $SRC/openssl
rm -rf $SRC/zlib
git clone --depth 1 https://github.com/curl/curl.git /src/$PROJECT_NAME
git clone --depth 1 https://github.com/curl/curl-fuzzer.git /src/curl_fuzzer

# Use curl-fuzzer's scripts to get latest dependencies.
/$SRC/curl_fuzzer/scripts/ossfuzzdeps.sh

cp /opt/oss-fuzz/projects/$PROJECT_NAME/build.sh $SRC/

cd $SRC/curl_fuzzer
if [ ! -d "/home/hacker/$PROJECT_NAME" ]; then
   mkdir /home/hacker/$PROJECT_NAME
   cp $SRC/curl_fuzzer/curl_fuzzer.cc $SRC/new_fuzzer.cc
   cp $SRC/curl_fuzzer/*.cc /home/hacker/$PROJECT_NAME
   cp $SRC/curl_fuzzer/*.sh /home/hacker/$PROJECT_NAME
   cp $SRC/curl_fuzzer/*.py /home/hacker/$PROJECT_NAME
   cp $SRC/curl_fuzzer/Makefile /home/hacker/$PROJECT_NAME
   cp /opt/oss-fuzz/projects/$PROJECT_NAME/build.sh /home/hacker/$PROJECT_NAME
else
   cp /home/hacker/$PROJECT_NAME/* $SRC
   cp /home/hacker/$PROJECT_NAME/build.sh $SRC
fi
#patch -tuN /src/build.sh -i /challenge/build.patch -r -
compile