#!/opt/pwn.college/bash
. /usr/local/sbin/e
cp /home/hacker/fuzz-dojo/bounded_resource.h /usr/local/include/
if [ "$?" -gt 0 ]; then
    exit 1
fi
export LABEL=$1
export PROJECT_NAME=spdlog
export SANITIZER=$1
if [ -z "$SANITIZER" ]; then
    export SANITIZER='none'
    export LABEL='none'$LABEL
fi

if [ ! -d "/src-orig" ]; then
#----------------------------------------------------------------------
#RUN apt-get update && apt-get install --yes cmake
#RUN git clone --depth 1 https://github.com/gabime/spdlog.git
#RUN zip spdlog_fuzzer_seed_corpus.zip spdlog/example/*
#WORKDIR spdlog
#COPY build.sh run_tests.sh spdlog_fuzzer.dict $SRC/
#COPY fuzz/* $SRC/



    cp -r /downloads/spdlog $SRC
    #cp -r /downloads/aspell-fuzz $SRC

    zip $SRC/spdlog_fuzzer_seed_corpus.zip $SRC/spdlog/example/*
    #cp /downloads/aspell*.bz2 /tmp

    cp /opt/oss-fuzz/projects/spdlog/build.sh $SRC
    cp /opt/oss-fuzz/projects/spdlog/run_tests.sh $SRC
    cp /opt/oss-fuzz/projects/spdlog/spdlog_fuzzer.dict $SRC
    cp /opt/oss-fuzz/projects/spdlog/fuzz/* $SRC/
    #cp /challenge/.fuzz-packet_seed_corpus.zip $OUT/fuzz-packet_seed_corpus.zip
    #patch -tuN $SRC/$PROJECT_NAME/ossfuzz.sh -i /challenge/.ossfuzz.patch -r -
    #patch -tuN $SRC/$PROJECT_NAME/Makefile.am -i /challenge/.Makefile.patch -r -
        
    #cp $SRC/$PROJECT_NAME/aspell_fuzzer.cpp $SRC/$PROJECT_NAME/new_fuzzer.cpp
#----------------------------------------------------------------------
    build-cleanup
fi
build-srcfolders
mv /src-$LABEL /src

cd $SRC/$PROJECT_NAME
#----------------------------------------------------------------------
if [ ! -d "/home/hacker/fuzz-dojo/$PROJECT_NAME" ]; then
   mkdir -p /home/hacker/fuzz-dojo/$PROJECT_NAME
   cp $SRC/*.cc /home/hacker/fuzz-dojo/$PROJECT_NAME
   cp $SRC/build.sh /home/hacker/fuzz-dojo/$PROJECT_NAME
else
   cp /home/hacker/fuzz-dojo/$PROJECT_NAME/* $SRC
   cp /home/hacker/fuzz-dojo/$PROJECT_NAME/build.sh $SRC
fi
#----------------------------------------------------------------------
if [ "$4" = "understanding" ]; then
    understanding $2 $3
elif [ "$4" = "planning" ]; then
    planning $2 $3
else
    fuzzlog
    compile
    drivers
fi
mv /src /src-$LABEL
