#!/bin/bash
export PROJECT_NAME=sudoers
sudo cp /usr/local/sbin/loc_count /usr/local/sbin/fi /challenge
sudo chmod 4755 /challenge/loc_count /challenge/fi
/challenge/loc_count
cd /src
rm -rf sudo
git clone https://github.com/sudo-project/sudo
cd /src/sudo
/challenge/fi $PROJECT_NAME
