#!/opt/pwn.college/bash
if [ "$1" = "afl" ]; then
    . /usr/local/sbin/eafl
    shift
    export LABEL=$1$FUZZING_ENGINE
else
    . /usr/local/sbin/e
    export LABEL=$1
fi
export PROJECT_NAME=vorbis
export SANITIZER=$1
if [ -z "$SANITIZER" ]; then
    export SANITIZER='none'
    export LABEL='none'$LABEL
fi

if [ ! -d "/src-orig" ]; then
    #apt-get update && apt-get install -y make autoconf automake ffmpeg libtool pkg-config python3 wget
    #python3 -m pip install corpus-replicator
    #git clone --depth 1 https://gitlab.xiph.org/xiph/ogg.git
    #git clone --depth 1 https://gitlab.xiph.org/xiph/vorbis.git
    cd $SRC
    cp -r /downloads/ogg $SRC
    cp -r /downloads/vorbis $SRC

    corpus-replicator -o decode_corpus audio_vorbis_ogg_libvorbis.yml audio
    # TODO: remove `people.xiph.org` lines once upstream build script is updated
    mkdir people.xiph.org/
    touch people.xiph.org/dummy.ogg

    cp /opt/oss-fuzz-new/projects/$PROJECT_NAME/build.sh $SRC/
    cp $SRC/$PROJECT_NAME/contrib/oss-fuzz/decode_fuzzer.cc $SRC/$PROJECT_NAME/contrib/oss-fuzz/new_fuzzer.cc
    
    patch -tuN $SRC/$PROJECT_NAME/contrib/oss-fuzz/build.sh -i /challenge/.build.patch -r -
    echo Please wait, creating /src-orig
    chown -hR hacker:hacker $SRC
    mv /src /src-orig
fi
if [ ! -d "/src-$LABEL" ]; then
    echo Please wait, creating /src-$LABEL
    cp -r /src-orig /src-$LABEL
fi
mv /src-$LABEL /src

cd $SRC
mkdir people.xiph.org/
touch people.xiph.org/dummy.ogg

cd $SRC/$PROJECT_NAME
if [ ! -d "/home/hacker/fuzz-dojo/$PROJECT_NAME" ]; then
   mkdir -p /home/hacker/fuzz-dojo/$PROJECT_NAME
   cp $SRC/$PROJECT_NAME/contrib/oss-fuzz/*.cc /home/hacker/fuzz-dojo/$PROJECT_NAME
   cp $SRC/$PROJECT_NAME/contrib/oss-fuzz/build.sh /home/hacker/fuzz-dojo/$PROJECT_NAME
   chown -R hacker /home/hacker/fuzz-dojo/$PROJECT_NAME
else
   cp /home/hacker/fuzz-dojo/$PROJECT_NAME/*.cc $SRC/$PROJECT_NAME/contrib/oss-fuzz/
   cp /home/hacker/fuzz-dojo/$PROJECT_NAME/build.sh $SRC/$PROJECT_NAME/contrib/oss-fuzz
fi
mkdir -p /home/hacker/.log
[ ! "$SANITIZER" = "introspector" ] && [ ! "$SANITIZER" = "coverage" ] && zip -ry /home/hacker/.log/$(TZ=US/Arizona date +"%F--%H-%M-%S")-$PROJECT_NAME /home/hacker/fuzz-dojo/$PROJECT_NAME
compile
drivers
chown -hR hacker:hacker $SRC /home/hacker/fuzz-dojo /home/hacker/.log /out
mv /src /src-$LABEL