#!/opt/pwn.college/bash
. /usr/local/sbin/e
export PROJECT_NAME=poppler
export SANITIZER=$1
[ -z "$SANITIZER" ] && export SANITIZER='none'
cd $SRC

apt-get update && apt-get install -y wget autoconf automake libtool pkg-config gperf python
pip3 install meson ninja gyp-next

git clone --depth 1 https://github.com/madler/zlib.git
git clone --depth 1 https://gitlab.freedesktop.org/freetype/freetype.git
git clone --depth 1 https://github.com/mm2/Little-CMS.git
git clone --depth 1 https://github.com/uclouvain/openjpeg
git clone --depth 1 https://github.com/glennrp/libpng.git
git clone --depth 1 https://gitlab.freedesktop.org/fontconfig/fontconfig.git
git clone --depth 1 https://gitlab.freedesktop.org/cairo/cairo.git
git clone --depth 1 --branch=5.15 git://code.qt.io/qt/qtbase.git
git clone --depth 1 https://gitlab.gnome.org/GNOME/pango.git
wget https://ftp.gnome.org/pub/gnome/sources/glib/2.70/glib-2.70.0.tar.xz
tar xvJf $SRC/glib-2.70.0.tar.xz
wget https://boostorg.jfrog.io/artifactory/main/release/1.83.0/source/boost_1_83_0.tar.bz2
wget https://ftp.mozilla.org/pub/security/nss/releases/NSS_3_75_RTM/src/nss-3.75-with-nspr-4.32.tar.gz
git clone --depth 1 --single-branch https://gitlab.freedesktop.org/poppler/poppler.git

git clone --depth 1 https://github.com/mozilla/pdf.js pdf.js && \
    zip -q $SRC/poppler_seed_corpus.zip pdf.js/test/pdfs/*.pdf && \
    rm -rf pdf.js

wget https://raw.githubusercontent.com/google/fuzzing/master/dictionaries/pdf.dict 
mv pdf.dict poppler.dict

cp /opt/oss-fuzz/projects/$PROJECT_NAME/build.sh $SRC/

#patch -tuN /src/build.sh -i /challenge/.build.patch -r -
cd $SRC/poppler

sudo --preserve-env compile
drivers
