#!/opt/pwn.college/bash
. /usr/local/sbin/e
LABEL=$1
PROJECT_NAME=cjson
SANITIZER=$1
if [ -z "$SANITIZER" ]; then
    SANITIZER='none'
    LABEL='none'
fi

SRC=/src-$LABEL

if [ "$LABEL" = "none" ]; then
    FLAGS=""
elif [ "$LABEL" = "address" ]; then
    FLAGS=$SANITIZER_FLAGS_address
elif [ "$LABEL" = "memory" ]; then
    FLAGS=$SANITIZER_FLAGS_memory
elif [ "$LABEL" = "undefined" ]; then
    FLAGS=$SANITIZER_FLAGS_undefined
elif [ "$LABEL" = "thread" ]; then
    FLAGS=$SANITIZER_FLAGS_thread
fi
set -x

cp /home/hacker/fuzz-dojo/$PROJECT_NAME/*.c $SRC/$PROJECT_NAME/misc/fuzz
mv $SRC /src

cd /src/$PROJECT_NAME/

$CXX $CXXFLAGS /src/cjson/fuzzing/cjson_read_fuzzer.c -I. \
    -o $OUT/cjson_read_fuzzer \
    $LIB_FUZZING_ENGINE /src/cjson/build/libcjson.a -pthreads

$CXX $CXXFLAGS /src/cjson/fuzzing/newfuzzer.c -I. \
    -o $OUT/newfuzzer \
    $LIB_FUZZING_ENGINE /src/cjson/build/libcjson.a -pthreads

cd
mv /src $SRC
chown -hR hacker:hacker $SRC /home/hacker/fuzz-dojo /home/hacker/.log /out
