#!/opt/pwn.college/bash
if [ "$1" = "afl" ]; then
    . /usr/local/sbin/eafl
    shift
else
    . /usr/local/sbin/e
fi
export PROJECT_NAME=minizip
export SANITIZER=$1
[ -z "$SANITIZER" ] && export SANITIZER='none'
cd $SRC

#apt-get update && apt-get install -y make cmake pkg-config libssl-dev:i386
#git clone -b develop https://github.com/zlib-ng/minizip-ng minizip
cp -r /opt/fuzz-targets/minizip $SRC

cp /opt/oss-fuzz-new/projects/$PROJECT_NAME/build.sh $SRC/
cd $SRC/$PROJECT_NAME
if [ ! -d "/home/hacker/training-locate" ]; then
   mkdir /home/hacker/training-locate
   cp $SRC/$PROJECT_NAME/test/fuzz/unzip_fuzzer.c $SRC/$PROJECT_NAME/test/fuzz/new_fuzzer.c
   cp $SRC/$PROJECT_NAME/test/fuzz/*.c /home/hacker/training-locate
   cp /opt/oss-fuzz-new/projects/$PROJECT_NAME/build.sh /home/hacker/training-locate
   chown -R hacker /home/hacker/training-locate
else
   cp /home/hacker/training-locate/*.c $SRC/$PROJECT_NAME/test/fuzz
   cp /home/hacker/training-locate/build.sh $SRC
fi
patch -tuN $SRC/minizip/CMakeLists.txt -i /challenge/.CMakeLists.patch -r -
mkdir -p /home/hacker/.log
[ ! "$SANITIZER" = "introspector" ] && [ ! "$SANITIZER" = "coverage" ] && zip -ry /home/hacker/.log/$(TZ=US/Arizona date +"%F--%H-%M-%S")-training-locate /home/hacker/training-locate
sudo --preserve-env compile
drivers
