#!/opt/pwn.college/bash
. /usr/local/sbin/eafl
export PROJECT_NAME=minizip
export SANITIZER=$1
[ -z "$SANITIZER" ] && export SANITIZER='none'
cd $SRC

#apt-get update && apt-get install -y make cmake pkg-config libssl-dev:i386
#git clone -b develop https://github.com/zlib-ng/minizip-ng minizip
cp -r /opt/fuzz-targets/minizip /src/minizip

cp /opt/oss-fuzz/projects/$PROJECT_NAME/build.sh $SRC/
cd $SRC/$PROJECT_NAME
if [ ! -d "/home/hacker/training-locate" ]; then
   mkdir /home/hacker/training-locate
   cp $SRC/$PROJECT_NAME/test/fuzz/unzip_fuzzer.c $SRC/$PROJECT_NAME/test/fuzz/new_fuzzer.c
   cp $SRC/$PROJECT_NAME/test/fuzz/*.c /home/hacker/training-locate
   cp /opt/oss-fuzz/projects/$PROJECT_NAME/build.sh /home/hacker/training-locate
   chown -R hacker /home/hacker/training-locate
else
   cp /home/hacker/training-locate/*.c $SRC/$PROJECT_NAME/test/fuzz
   cp /home/hacker/training-locate/build.sh $SRC
fi
patch -tuN /src/minizip/CMakeLists.txt -i /challenge/.CMakeLists.patch -r -
sudo --preserve-env compile
drivers
