#!/opt/pwn.college/bash
export PROJECT_NAME=minizip
/challenge/.loc_count $PROJECT_NAME
cd /src/$PROJECT_NAME
cp /home/hacker/training-locate/*.c /src/$PROJECT_NAME/test/fuzz
/challenge/.fi $PROJECT_NAME
