#!/opt/pwn.college/bash
. /usr/local/sbin/e
if [ "$?" -gt 0 ]; then
    exit 1
fi
export LABEL=$1
export PROJECT_NAME=libsass
export SANITIZER=$1
if [ -z "$SANITIZER" ]; then
    export SANITIZER='none'
    export LABEL='none'$LABEL
fi

if [ ! -d "/src-orig" ]; then
#----------------------------------------------------------------------
    #apt-get update && apt-get install -y make autoconf automake libtool
    #git clone --depth 1 https://github.com/sass/libsass.git libsass
    cd $SRC
    cp -r /downloads/libsass $SRC

    # This is to fix Fuzz Introspector build by using LLVM old pass manager
    # re https://github.com/ossf/fuzz-introspector/issues/305
    export OLD_LLVMPASS=1

    cp /opt/oss-fuzz/projects/$PROJECT_NAME/build.sh $SRC/
    cp /opt/oss-fuzz/projects/$PROJECT_NAME/data_context_fuzzer.cc  $SRC/

    cd /
    cp $SRC/data_context_fuzzer.cc $SRC/new_fuzzer.cc
    patch -tuN $SRC/build.sh -i /challenge/.build.patch -r -
#----------------------------------------------------------------------
    build-cleanup
fi
build-srcfolders
git config --global --add safe.directory /src/libsass
mv /src-$LABEL /src

cd $SRC
#----------------------------------------------------------------------
if [ ! -d "/home/hacker/fuzz-dojo/$PROJECT_NAME" ]; then
   mkdir -p /home/hacker/fuzz-dojo/$PROJECT_NAME
   cp $SRC/*.cc /home/hacker/fuzz-dojo/$PROJECT_NAME
   cp $SRC/build.sh /home/hacker/fuzz-dojo/$PROJECT_NAME
else
   cp /home/hacker/fuzz-dojo/$PROJECT_NAME/*.cc $SRC
   cp /home/hacker/fuzz-dojo/$PROJECT_NAME/build.sh $SRC
fi
#----------------------------------------------------------------------
if [ "$4" = "understanding" ]; then
    understanding $2 $3
elif [ "$4" = "planning" ]; then
    planning $2 $3
else
    fuzzlog
    compile
    drivers
fi
mv /src /src-$LABEL
