#!/opt/pwn.college/bash
. /usr/local/sbin/e
cp /home/hacker/fuzz-dojo/bounded_resource.h /usr/local/include/
if [ "$?" -gt 0 ]; then
    exit 1
fi
export LABEL=$1
export PROJECT_NAME=rsync
export SANITIZER=$1
if [ -z "$SANITIZER" ]; then
    export SANITIZER='none'
    export LABEL='none'$LABEL
fi

if [ ! -d "/src-orig" ]; then
#----------------------------------------------------------------------
    #FROM gcr.io/oss-fuzz-base/base-builder
    #RUN apt-get update && apt-get install -y autoconf automake libtool pkg-config zlib1g-dev libpopt-dev
    #RUN git clone --depth 1 https://github.com/WayneD/rsync.git rsync
    #WORKDIR rsync
    #COPY build.sh $SRC/
    #COPY *fuzzer*.c $SRC/
    cp -r /downloads/rsync $SRC

    mkdir -p /opt/oss-fuzz/projects/rsync
    cp /challenge/.build.sh /opt/oss-fuzz/projects/rsync/build.sh
    cp /challenge/.fuzz_parse_rule.c /opt/oss-fuzz/projects/rsync/fuzz_parse_rule.c
    cp /challenge/.rsync_flist_fuzzer.c /opt/oss-fuzz/projects/rsync/rsync_flist_fuzzer.c
    cp /challenge/.project.yaml /opt/oss-fuzz/projects/rsync/project.yaml


    cp /challenge/.build.sh $SRC/build.sh
    cp /challenge/.fuzz_parse_rule.c  $SRC/fuzz_parse_rule.c
    cp /challenge/.rsync_flist_fuzzer.c  $SRC/rsync_flist_fuzzer.c

    #patch -tuN $SRC/$PROJECT_NAME/fuzzing/ossfuzz.sh -i /challenge/.ossfuzz.patch -r -
    #cp $SRC/$PROJECT_NAME/fuzzing/cjson_read_fuzzer.c $SRC/$PROJECT_NAME/fuzzing/newfuzzer.c
#----------------------------------------------------------------------
    build-cleanup
fi
build-srcfolders
mv /src-$LABEL /src

cd $SRC/$PROJECT_NAME
rm -rf $SRC/$PROJECT_NAME/build

#----------------------------------------------------------------------
if [ ! -d "/home/hacker/fuzz-dojo/$PROJECT_NAME" ]; then
   mkdir -p /home/hacker/fuzz-dojo/$PROJECT_NAME
   cp -r $SRC/*.c /home/hacker/fuzz-dojo/$PROJECT_NAME
   cp $SRC/build.sh /home/hacker/fuzz-dojo/$PROJECT_NAME
else
   cp -r /home/hacker/fuzz-dojo/$PROJECT_NAME/* $SRC
   cp /home/hacker/fuzz-dojo/$PROJECT_NAME/build.sh $SRC
fi
#----------------------------------------------------------------------
if [ "$4" = "understanding" ]; then
    understanding $2 $3
elif [ "$4" = "planning" ]; then
    planning $2 $3
else
    fuzzlog
    compile
    drivers
fi
mv /src /src-$LABEL
