#!/opt/pwn.college/bash
export PROJECT_NAME=speex
/challenge/.loc_count
cd /src

rm -rf /src/$PROJECT_NAME
#apt-get update && apt-get install -y make autoconf libtool pkg-config wget
#git clone --depth 1 https://gitlab.xiph.org/xiph/ogg.git
#git clone --depth 1 https://gitlab.xiph.org/xiph/speex.git speex
cp -r /opt/fuzz-targets/ogg /src/ogg
cp -r /opt/fuzz-targets/speex /src/speex

/challenge/.fi $PROJECT_NAME
