#!/opt/pwn.college/bash
export PROJECT_NAME=speex
/challenge/.loc_count
cd /src

rm -rf /src/$PROJECT_NAME
#apt-get update && apt-get install -y make autoconf libtool pkg-config wget
#git clone --depth 1 https://gitlab.xiph.org/xiph/ogg.git
#git clone --depth 1 https://gitlab.xiph.org/xiph/speex.git speex
cp -r /opt/fuzz-targets/ogg /src/ogg
cp -r /opt/fuzz-targets/speex /src/speex
cd /src/$PROJECT_NAME
cp /src/$PROJECT_NAME/contrib/oss-fuzz/speexdec_fuzzer.cc /src/$PROJECT_NAME/contrib/oss-fuzz/new_fuzzer.cc
patch -tuN /src/speex/src/generate-samples.sh -i /challenge/.generate-samples.patch -r -

/challenge/.fi $PROJECT_NAME
