#!/opt/pwn.college/bash
. /usr/local/sbin/e
export PROJECT_NAME=bzip2
export SANITIZER=$1
[ -z "$SANITIZER" ] && export SANITIZER='none'
cd $SRC

rm -rf /src/$PROJECT_NAME
rm -rf /src/$PROJECT_NAME-tests
#apt-get update && apt-get install -y make autoconf automake libtool wget
#git clone https://github.com/swirsz/bzip2
#git clone git://sourceware.org/git/bzip2-tests.git
cp -r /opt/fuzz-targets/bzip2 /src/bzip2
cp -r /opt/fuzz-targets/bzip2-tests /src/bzip2-tests

cp /opt/oss-fuzz/projects/$PROJECT_NAME/build.sh $SRC/
cp /opt/oss-fuzz/projects/$PROJECT_NAME/*.c $SRC/
if [ ! -d "/home/hacker/training-seedcorpus" ]; then
   mkdir /home/hacker/training-seedcorpus
   cp $SRC/build.sh /home/hacker/training-seedcorpus
   cp $SRC/*.c /home/hacker/training-seedcorpus
   cp /opt/oss-fuzz/projects/$PROJECT_NAME/build.sh /home/hacker/training-seedcorpus
   chown -R hacker /home/hacker/$PROJECT_NAME
else
   cp /home/hacker/training-seedcorpus/* $SRC
   cp /home/hacker/training-seedcorpus/build.sh $SRC
fi

cd $SRC
sudo --preserve-env compile
