#!/opt/pwn.college/bash
echo 74 > /tmp/initial
echo 79 > /tmp/target
if [ "$1" = "afl" ]; then
    . /usr/local/sbin/eafl
    shift
else
    . /usr/local/sbin/e
fi
export PROJECT_NAME=bzip2
export SANITIZER=$1
[ -z "$SANITIZER" ] && export SANITIZER='none'
cd $SRC

rm -rf $SRC/$PROJECT_NAME
rm -rf $SRC/$PROJECT_NAME-tests
#apt-get update && apt-get install -y make autoconf automake libtool wget
#git clone https://github.com/swirsz/bzip2
#git clone git://sourceware.org/git/bzip2-tests.git
cp -r /opt/fuzz-targets/bzip2 $SRC
cp -r /opt/fuzz-targets/bzip2-tests $SRC

cp /opt/oss-fuzz/projects/$PROJECT_NAME/build.sh $SRC/
cp /opt/oss-fuzz/projects/$PROJECT_NAME/*.c $SRC/
if [ ! -d "/home/hacker/training-seedcorpus" ]; then
   mkdir /home/hacker/training-seedcorpus
   cp $SRC/build.sh /home/hacker/training-seedcorpus
   cp $SRC/*.c /home/hacker/training-seedcorpus
   cp /opt/oss-fuzz/projects/$PROJECT_NAME/build.sh /home/hacker/training-seedcorpus
   chown -R hacker /home/hacker/training-seedcorpus
else
   cp /home/hacker/training-seedcorpus/* $SRC
   cp /home/hacker/training-seedcorpus/build.sh $SRC
fi

cd $SRC
mkdir -p /home/hacker/.log
[ ! "$SANITIZER" = "introspector" ] && [ ! "$SANITIZER" = "coverage" ] && zip -ry /home/hacker/.log/$(TZ=US/Arizona date +"%F--%H-%M-%S")-training-seedcorpus /home/hacker/training-seedcorpus
sudo --preserve-env compile
drivers
