#!/opt/pwn.college/bash
. /usr/local/sbin/e
export LABEL=$1
export PROJECT_NAME=bzip2
export SANITIZER=$1
if [ -z "$SANITIZER" ]; then
    export SANITIZER='none'
    export LABEL='none'$LABEL
fi

if [ ! -d "/src-orig" ]; then
#----------------------------------------------------------------------
    rm -rf $SRC/$PROJECT_NAME
    rm -rf $SRC/$PROJECT_NAME-tests
    #apt-get update && apt-get install -y make autoconf automake libtool wget
    #git clone https://github.com/swirsz/bzip2
    #git clone git://sourceware.org/git/bzip2-tests.git
    cp -r /downloads/swbzip2 $SRC/bzip2
    cp -r /downloads/bzip2-tests $SRC

    cp /opt/oss-fuzz/projects/$PROJECT_NAME/build.sh $SRC/
    cp /opt/oss-fuzz/projects/$PROJECT_NAME/*.c $SRC/

#----------------------------------------------------------------------
    build-cleanup
fi
build-srcfolders
mv /src-$LABEL /src

cd $SRC
#----------------------------------------------------------------------
if [ ! -d "/home/hacker/fuzz-dojo/training-implement-seedcorpus" ]; then
   mkdir -p /home/hacker/fuzz-dojo/training-implement-seedcorpus
   cp $SRC/build.sh /home/hacker/fuzz-dojo/training-implement-seedcorpus
   cp $SRC/*.c /home/hacker/fuzz-dojo/training-implement-seedcorpus
   cp $SRC/build.sh /home/hacker/fuzz-dojo/training-implement-seedcorpus
else
   cp /home/hacker/fuzz-dojo/training-implement-seedcorpus/* $SRC
   cp /home/hacker/fuzz-dojo/training-implement-seedcorpus/build.sh $SRC
fi
export PROJECT_NAME=training-implement-seedcorpus
#----------------------------------------------------------------------
fuzzlog
compile
drivers
mv /src /src-$LABEL
