#!/bin/bash
export PROJECT_NAME=libssh2
/usr/local/sbin/loc_count
cd /src
rm -rf /src/$PROJECT_NAME
git clone --depth 1 https://github.com/libssh2/libssh2.git /src/libssh2
cd /src/$PROJECT_NAME
/usr/local/sbin/fi $PROJECT_NAME
