#!/opt/pwn.college/bash
if [ "$1" = "afl" ]; then
    . /usr/local/sbin/eafl
    shift
    export LABEL=$1$FUZZING_ENGINE
else
    . /usr/local/sbin/e
    export LABEL=$1
fi
export PROJECT_NAME=mupdf
export SANITIZER=$1
if [ -z "$SANITIZER" ]; then
    export SANITIZER='none'
    export LABEL='none'$LABEL
fi

#if [ ! -d "/src-orig" ]; then
    cd $SRC
    rm -rf $SRC/$PROJECT_NAME
    #apt-get update && apt-get install -y make libtool pkg-config

    #git clone --recursive --depth 1 git://git.ghostscript.com/mupdf.git mupdf
    #git clone --depth 1 https://github.com/mozilla/pdf.js pdf.js 
    cp -r /downloads/mupdf $SRC
    cp -r /downloads/pdf.js $SRC

    zip -q $SRC/pdf_fuzzer_seed_corpus.zip pdf.js/test/pdfs/*.pdf
    zip -q $SRC/new_fuzzer_seed_corpus.zip pdf.js/test/pdfs/*.pdf && rm -rf pdf.js

    #wget https://raw.githubusercontent.com/rc0r/afl-fuzz/master/dictionaries/pdf.dict
    cp /downloads/pdf.dict $SRC
    cp pdf.dict new_fuzzer.dict
    mv pdf.dict pdf_fuzzer.dict

    cp /opt/oss-fuzz-new/projects/$PROJECT_NAME/build.sh $SRC/
    cp /opt/oss-fuzz-new/projects/$PROJECT_NAME/*.cc $SRC/
    cp /opt/oss-fuzz-new/projects/$PROJECT_NAME/pdf_fuzzer.options $SRC/
    cp /opt/oss-fuzz-new/projects/$PROJECT_NAME/pdf_fuzzer.options $SRC/new_fuzzer.options

    cp $SRC/pdf_fuzzer.cc $SRC/new_fuzzer.cc
    rm -rf /out/src
    cp -r /src /out
    patch -tuN $SRC/build.sh -i /challenge/.build.patch -r -

    chown -hR hacker:hacker $SRC
#    mv /src /src-orig
#fi
#if [ ! -d "/src-$LABEL" ]; then
#    echo Please wait, initial setup
#    cp -r /src-orig /src-$LABEL
#fi
#mv /src-$LABEL /src

    
cd $SRC/$PROJECT_NAME
if [ ! -d "/home/hacker/fuzz-dojo/$PROJECT_NAME" ]; then
   mkdir -p /home/hacker/fuzz-dojo/$PROJECT_NAME
   cp $SRC/*.cc /home/hacker/fuzz-dojo/$PROJECT_NAME
   cp $SRC/build.sh /home/hacker/fuzz-dojo/$PROJECT_NAME
   chown -R hacker /home/hacker/fuzz-dojo/$PROJECT_NAME
else
   cp /home/hacker/fuzz-dojo/$PROJECT_NAME/*.cc $SRC
   cp /home/hacker/fuzz-dojo/$PROJECT_NAME/build.sh $SRC
fi
mkdir -p /home/hacker/.log
[ ! "$SANITIZER" = "introspector" ] && [ ! "$SANITIZER" = "coverage" ] && zip -ry /home/hacker/.log/$(TZ=US/Arizona date +"%F--%H-%M-%S")-$PROJECT_NAME /home/hacker/fuzz-dojo/$PROJECT_NAME
compile
drivers
chown -hR hacker:hacker $SRC /home/hacker/fuzz-dojo /home/hacker/.log /out
#mv /src /src-$LABEL
