#!/opt/pwn.college/bash
. /usr/local/sbin/e
export PROJECT_NAME=binutils
export SANITIZER=$1
[ -z "$SANITIZER" ] && export SANITIZER='none'
cd $SRC

apt-get update && apt-get install -y make texinfo libgmp-dev libmpfr-dev
apt-get install -y flex bison
git clone --depth=1 https://github.com/DavidKorczynski/binary-samples binary-samples
git clone --recursive --depth 1 git://sourceware.org/git/binutils-gdb.git binutils-gdb

cp /opt/oss-fuzz/projects/$PROJECT_NAME/build.sh $SRC/
cp /opt/oss-fuzz/projects/$PROJECT_NAME/fuzz_*.c $SRC/

cd $SRC/

sudo --preserve-env compile