#!/opt/pwn.college/bash
if [ "$1" = "afl" ]; then
    . /usr/local/sbin/eafl
    shift
else
    . /usr/local/sbin/e
fi
export PROJECT_NAME=usbguard
export SANITIZER=$1
[ -z "$SANITIZER" ] && export SANITIZER='none'

if [ ! -d "/src-orig" ]; then

#apt-get update && apt-get install -y make autoconf automake libtool pkg-config libxml2-utils1 libxml2-dev xsltproc \
#  libprotobuf-dev protobuf-compiler libdbus-1-dev libdbus-glib-1-dev libgio2.0-cil-dev libgcrypt20-dev \
#  libpolkit-gobject-1-dev libseccomp-dev libcap-ng-dev

#git clone https://github.com/ClusterLabs/libqb && cd libqb && \
#    ./autogen.sh && ./configure && make && make install

rm -rf $PROJECT_NAME
rm -rf inspector

#git clone --recurse-submodules --depth 1 https://github.com/USBGuard/usbguard usbguard
cp -r /opt/fuzz-targets/usbguard $SRC

# This is to fix Fuzz Introspector build by using LLVM old pass manager
# re https://github.com/ossf/fuzz-introspector/issues/305
export OLD_LLVMPASS=1

cp /opt/oss-fuzz-new/projects/$PROJECT_NAME/build.sh $SRC/

patch -tuN $SRC/$PROJECT_NAME$SRC/Tests/Fuzzers/Makefile.am -i /challenge/.Makefile.patch -r -
cd $SRC/usbguard
if [ ! -d "/home/hacker/fuzz-dojo/$PROJECT_NAME" ]; then
   mkdir -p /home/hacker/fuzz-dojo/$PROJECT_NAME
   cp $SRC/$PROJECT_NAME$SRC/Tests/Fuzzers/fuzzer-uevent.cpp $SRC/$PROJECT_NAME$SRC/Tests/Fuzzers/fuzzer-new.cpp
   cp $SRC/$PROJECT_NAME$SRC/Tests/Fuzzers/*.cpp /home/hacker/fuzz-dojo/$PROJECT_NAME
   cp $SRC/$PROJECT_NAME$SRC/Tests/Fuzzers/Makefile.am /home/hacker/fuzz-dojo/$PROJECT_NAME
   cp $SRC/build.sh /home/hacker/fuzz-dojo/$PROJECT_NAME
   chown -R hacker /home/hacker/fuzz-dojo/$PROJECT_NAME
else
   cp /home/hacker/fuzz-dojo/$PROJECT_NAME/*.cpp $SRC/$PROJECT_NAME$SRC/Tests/Fuzzers
   cp /home/hacker/fuzz-dojo/$PROJECT_NAME/Makefile.am $SRC/$PROJECT_NAME$SRC/Tests/Fuzzers
   cp /home/hacker/fuzz-dojo/$PROJECT_NAME/build.sh $SRC
fi
mkdir -p /home/hacker/.log
[ ! "$SANITIZER" = "introspector" ] && [ ! "$SANITIZER" = "coverage" ] && zip -ry /home/hacker/.log/$(TZ=US/Arizona date +"%F--%H-%M-%S")-$PROJECT_NAME /home/hacker/fuzz-dojo/$PROJECT_NAME
sudo --preserve-env compile
drivers
chown -hR hacker:hacker /src
mv /src /src-$SANITIZER