#!/opt/pwn.college/bash
if [ "$1" = "afl" ]; then
    . /usr/local/sbin/eafl
    shift
else
    . /usr/local/sbin/e
fi
export PROJECT_NAME=vorbis
export SANITIZER=$1
[ -z "$SANITIZER" ] && export SANITIZER='none'

if [ ! -d "/src-orig" ]; then
    #apt-get update && apt-get install -y make autoconf automake ffmpeg libtool pkg-config python3 wget
    #python3 -m pip install corpus-replicator
    #git clone --depth 1 https://gitlab.xiph.org/xiph/ogg.git
    #git clone --depth 1 https://gitlab.xiph.org/xiph/vorbis.git

    cp -r /opt/fuzz-targets/ogg $SRC
    cp -r /opt/fuzz-targets/vorbis $SRC

    corpus-replicator -o decode_corpus audio_vorbis_ogg_libvorbis.yml audio
    # TODO: remove `people.xiph.org` lines once upstream build script is updated
    mkdir people.xiph.org/
    touch people.xiph.org/dummy.ogg

    cp /opt/oss-fuzz-new/projects/$PROJECT_NAME/build.sh $SRC/

    patch -tuN $SRC/$PROJECT_NAME/contrib/oss-fuzz/build.sh -i /challenge/.build.patch -r -
    echo Please wait, initial filecopy
    chown -hR hacker:hacker $SRC/$PROJECT_NAME
    mv /src /src-orig
fi
if [ ! -d "/src-$SANITIZER" ]; then
    echo Please wait, initial filecopy
    cp -r /src-orig /src-$SANITIZER
fi
mv /src-$SANITIZER /src

cd $SRC/$PROJECT_NAME
if [ ! -d "/home/hacker/fuzz-dojo/$PROJECT_NAME" ]; then
   mkdir -p /home/hacker/fuzz-dojo/$PROJECT_NAME
   cp $SRC/$PROJECT_NAME/contrib/oss-fuzz/decode_fuzzer.cc $SRC/$PROJECT_NAME/contrib/oss-fuzz/new_fuzzer.cc
   cp $SRC/$PROJECT_NAME/contrib/oss-fuzz/*.cc /home/hacker/fuzz-dojo/$PROJECT_NAME
   cp $SRC/$PROJECT_NAME/contrib/oss-fuzz/build.sh /home/hacker/fuzz-dojo/$PROJECT_NAME
   chown -R hacker /home/hacker/fuzz-dojo/$PROJECT_NAME
else
   cp /home/hacker/fuzz-dojo/$PROJECT_NAME/*.cc $SRC/$PROJECT_NAME/contrib/oss-fuzz/
   cp /home/hacker/fuzz-dojo/$PROJECT_NAME/build.sh $SRC/$PROJECT_NAME/contrib/oss-fuzz
fi
mkdir -p /home/hacker/.log
[ ! "$SANITIZER" = "introspector" ] && [ ! "$SANITIZER" = "coverage" ] && zip -ry /home/hacker/.log/$(TZ=US/Arizona date +"%F--%H-%M-%S")-$PROJECT_NAME /home/hacker/fuzz-dojo/$PROJECT_NAME
sudo --preserve-env compile
drivers
chown -hR hacker:hacker $SRC/$PROJECT_NAME
mv /src /src-$SANITIZER