#!/bin/bash
export DRIVERS=('fuzz_mime' 'fuzz_tok822')
export PROJECT_NAME=opensips
/usr/local/sbin/loc_count.sh $PROJECT_NAME "${DRIVERS[@]}"
cd /src/$PROJECT_NAME
/usr/local/sbin/fi.sh $PROJECT_NAME "${DRIVERS[@]}"
