#!/opt/pwn.college/bash
. /usr/local/sbin/e
export LABEL=$1
export PROJECT_NAME=pcre2
export SANITIZER=$1
if [ -z "$SANITIZER" ]; then
    export SANITIZER='none'
    export LABEL='none'$LABEL
fi

if [ ! -d "/src-orig" ]; then
    #apt-get update && apt-get install -y make autoconf automake libtool subversion
    #git clone https://github.com/PCRE2Project/pcre2 pcre2
    cp -r /downloads/pcre2 $SRC

    cp /opt/oss-fuzz/projects/$PROJECT_NAME/build.sh $SRC/

    #patch -tuN $SRC/build.sh -i /challenge/.build.patch -r -
    build-cleanup
fi
if [ ! -d "/src-$LABEL" ]; then
    echo Please wait, creating /src-$LABEL
    cp -r /src-orig /src-$LABEL
fi
mv /src-$LABEL /src

cd $SRC/$PROJECT_NAME
if [ ! -d "/home/hacker/fuzz-dojo/$PROJECT_NAME" ]; then
   mkdir -p /home/hacker/fuzz-dojo/$PROJECT_NAME
   #cp $SRC/$PROJECT_NAME/pcre2_fuzz*.dict /home/hacker/fuzz-dojo/$PROJECT_NAME
   #cp $SRC/$PROJECT_NAME/pcre2_fuzz*.options /home/hacker/fuzz-dojo/$PROJECT_NAME
   cp $SRC/$PROJECT_NAME/src/pcre2_fuzzsupport.c /home/hacker/fuzz-dojo/$PROJECT_NAME
   chown -R hacker /home/hacker/fuzz-dojo/$PROJECT_NAME
else
   #cp /home/hacker/fuzz-dojo/$PROJECT_NAME/*.dict $SRC/$PROJECT_NAME
   #cp /home/hacker/fuzz-dojo/$PROJECT_NAME/*.options $SRC/$PROJECT_NAME
   cp /home/hacker/fuzz-dojo/$PROJECT_NAME/pcre2_fuzzsupport.c $SRC/$PROJECT_NAME/src
fi
fuzzlog
compile
drivers
mv /src /src-$LABEL
