@@ -3,5 +3,10 @@
 	$(CXX) $(CXXFLAGS) $(LIB_FUZZING_ENGINE) fuzz.o -o $(OUT)/fuzz \
 	      ../../src/liblzma/.libs/liblzma.a
 
+newfuzzer: newfuzzer.c
+	$(CC) $(CFLAGS) -c newfuzzer.c -I ../../src/liblzma/api/
+	$(CXX) $(CXXFLAGS) $(LIB_FUZZING_ENGINE) newfuzzer.o -o $(OUT)/newfuzzer \
+              ../../src/liblzma/.libs/liblzma.a
+
 clean:
 	rm -f *.o
