#!/opt/pwn.college/bash
. /usr/local/sbin/e
if [ "$?" -gt 0 ]; then
    exit 1
fi
export LABEL=$1
export PROJECT_NAME=php-src
export SANITIZER=$1
if [ -z "$SANITIZER" ]; then
    export SANITIZER='none'
    export LABEL='none'$LABEL
fi

if [ ! -d "/src-orig" ]; then
#----------------------------------------------------------------------
#RUN apt-get update && apt-get install -y autoconf automake libtool bison re2c pkg-config
#RUN git clone --depth 1 --branch master https://github.com/php/php-src.git php-src
#WORKDIR php-src
#COPY replay_build.sh build.sh $SRC/



    cp -r /downloads/php-src $SRC

    #cp /downloads/aspell*.bz2 /tmp

    cp /opt/oss-fuzz/projects/php/replay_build.sh $SRC
    cp /opt/oss-fuzz/projects/php/build.sh $SRC
    #cp /challenge/.fuzz-packet_seed_corpus.zip $OUT/fuzz-packet_seed_corpus.zip
    #patch -tuN $SRC/$PROJECT_NAME/ossfuzz.sh -i /challenge/.ossfuzz.patch -r -
    #patch -tuN $SRC/$PROJECT_NAME/Makefile.am -i /challenge/.Makefile.patch -r -
        
    #cp $SRC/$PROJECT_NAME/aspell_fuzzer.cpp $SRC/$PROJECT_NAME/new_fuzzer.cpp
#----------------------------------------------------------------------
    build-cleanup
fi
build-srcfolders
mv /src-$LABEL /src

cd $SRC/$PROJECT_NAME
#----------------------------------------------------------------------
if [ ! -d "/home/hacker/fuzz-dojo/$PROJECT_NAME" ]; then
   mkdir -p /home/hacker/fuzz-dojo/$PROJECT_NAME
   cp $SRC/$PROJECT_NAME/sapi/fuzzer/*.c /home/hacker/fuzz-dojo/$PROJECT_NAME
   cp $SRC/build.sh /home/hacker/fuzz-dojo/$PROJECT_NAME
else
   cp /home/hacker/fuzz-dojo/$PROJECT_NAME/*.c $SRC/$PROJECT_NAME/sapi/fuzzer
   cp /home/hacker/fuzz-dojo/$PROJECT_NAME/build.sh $SRC
fi
#----------------------------------------------------------------------
if [ "$4" = "understanding" ]; then
    understanding $2 $3
elif [ "$4" = "planning" ]; then
    planning $2 $3
else
    fuzzlog
    compile
    drivers
fi
mv /src /src-$LABEL
