#!/bin/sh
. /usr/local/sbin/e
export PROJECT_NAME=snappy
[ -z "$SANITIZER" ] && export SANITIZER='none'
cd $SRC

rm -rf $SRC/$PROJECT_NAME/build
apt-get update && apt-get install -y make autoconf automake libtool gettext pkg-config build-essential
git clone --recurse-submodules https://github.com/google/snappy

cp /opt/oss-fuzz/projects/$PROJECT_NAME/build.sh $SRC/

cd $SRC/
compile