#!/bin/sh
. /usr/local/sbin/e
export PROJECT_NAME=snappy
[ -z "$SANITIZER" ] && export SANITIZER='none'
cd $SRC

rm -rf $SRC/$PROJECT_NAME/build
#apt-get update && apt-get install -y make autoconf automake libtool gettext pkg-config build-essential
git clone --recurse-submodules https://github.com/google/snappy

cp /opt/oss-fuzz/projects/$PROJECT_NAME/build.sh $SRC/

cd $SRC/
if [ ! -d "/home/hacker/$PROJECT_NAME" ]; then
   mkdir ~/$PROJECT_NAME
   cp $SRC/$PROJECT_NAME/snappy_compress_fuzzer.cc $SRC/$PROJECT_NAME/new_fuzzer.cc
   cp $SRC/$PROJECT_NAME/*.cc ~/$PROJECT_NAME
else
   cp ~/$PROJECT_NAME/*.cc $SRC/$PROJECT_NAME
fi
patch -tuN /src/snappy/build/Makefile -i /challenge/Makefile.patch -r -
compile
