#!/opt/pwn.college/bash
export PROJECT_NAME=snappy
sudo cp /usr/local/sbin/loc_count /usr/local/sbin/fi /challenge
sudo chmod 4755 /challenge/loc_count /challenge/fi
/challenge/loc_count
cd /src
rm -rf /src/$PROJECT_NAME/build
cp /home/hacker/$PROJECT_NAME/*.cc /src/$PROJECT_NAME
/challenge/fi $PROJECT_NAME
