@@ -186,6 +186,19 @@
 snappy_compress_fuzzer/fast:
 	$(MAKE) $(MAKESILENT) -f CMakeFiles/snappy_compress_fuzzer.dir/build.make CMakeFiles/snappy_compress_fuzzer.dir/build
 .PHONY : snappy_compress_fuzzer/fast
+#============================================================================= 
+# Target rules for targets named new_fuzzer
+
+# Build rule for target.
+new_fuzzer: cmake_check_build_system
+        $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 new_fuzzer
+.PHONY : new_fuzzer
+
+# fast build rule for target.
+new_fuzzer/fast:
+        $(MAKE) $(MAKESILENT) -f CMakeFiles/new_fuzzer.dir/build.make CMakeFiles/new_fuzzer.dir/build
+.PHONY : new_fuzzer/fast    
+
 
 #=============================================================================
 # Target rules for targets named snappy_uncompress_fuzzer
@@ -319,7 +332,33 @@
 snappy_compress_fuzzer.cc.s:
 	$(MAKE) $(MAKESILENT) -f CMakeFiles/snappy_compress_fuzzer.dir/build.make CMakeFiles/snappy_compress_fuzzer.dir/snappy_compress_fuzzer.cc.s
 .PHONY : snappy_compress_fuzzer.cc.s
+#####################################################
+new_fuzzer.o: new_fuzzer.cc.o
+.PHONY : new_compress_fuzzer.o
+
+# target to build an object file
+new_fuzzer.cc.o:
+        $(MAKE) $(MAKESILENT) -f CMakeFiles/new_fuzzer.dir/build.make CMakeFiles/new_fuzzer.dir/new_fuzzer.cc.o
+.PHONY : new_fuzzer.cc.o
+
+new_fuzzer.i: new_fuzzer.cc.i
+.PHONY : new_fuzzer.i
+
+# target to preprocess a source file
+new_fuzzer.cc.i:
+        $(MAKE) $(MAKESILENT) -f CMakeFiles/new_fuzzer.dir/build.make CMakeFiles/new_fuzzer.dir/new_fuzzer.cc.i
+.PHONY : new_fuzzer.cc.i
+
+new_fuzzer.s: new_fuzzer.cc.s
+.PHONY : new_fuzzer.s
+
+# target to generate assembly for a file
+new_fuzzer.cc.s:
+        $(MAKE) $(MAKESILENT) -f CMakeFiles/new_fuzzer.dir/build.make CMakeFiles/new_fuzzer.dir/new_fuzzer.cc.s
+.PHONY : new_fuzzer.cc.s
+
 
+###################################################
 snappy_uncompress_fuzzer.o: snappy_uncompress_fuzzer.cc.o
 .PHONY : snappy_uncompress_fuzzer.o
 
