#!/opt/pwn.college/bash
. /usr/local/sbin/e
export LABEL=$1
export PROJECT_NAME=liblouis
SANITIZER=$1
if [ -z "$SANITIZER" ]; then
    SANITIZER='none'
    export LABEL='none'
fi

SRC=/src-$LABEL
if [ -z "$(find /out -mindepth 1 -maxdepth 1)" ] || [ ! -d "$SRC" ]; then
    echo "Run /challenge/build first"
    rm /tmp/build.lck
else 

if [ "$LABEL" = "none" ]; then
    FLAGS=""
elif [ "$LABEL" = "address" ]; then
    FLAGS=$SANITIZER_FLAGS_address
elif [ "$LABEL" = "memory" ]; then
    FLAGS=$SANITIZER_FLAGS_memory
elif [ "$LABEL" = "undefined" ]; then
    FLAGS=$SANITIZER_FLAGS_undefined
elif [ "$LABEL" = "thread" ]; then
    FLAGS=$SANITIZER_FLAGS_thread
fi
set -x
#----------------------------------------------------------------------

cp /home/hacker/fuzz-dojo/$PROJECT_NAME/*.c $SRC/$PROJECT_NAME/tests/fuzzing

cd $SRC/$PROJECT_NAME/tests/fuzzing

$CC $CFLAGS $FLAGS -pthread -c fuzz_newfuzzer.c -o fuzz_newfuzzer.o \
    -I$SRC/liblouis -I$SRC/liblouis/liblouis
$CXX $CXXFLAGS $FLAGS $LIB_FUZZING_ENGINE -pthread fuzz_newfuzzer.o \
    -o $OUT/fuzz_newfuzzer fuzz_lib.a

#----------------------------------------------------------------------
drivers
fi
