#!/opt/pwn.college/bash
if [ "$?" -gt 0 ]; then
    exit 1
fi
export LABEL=$1
export PROJECT_NAME=cjson
export SANITIZER=$1
if [ "$3" != "$PROJECT_NAME" ]; then
    echo "[ERROR] Project $PROJECT_NAME not available in this challenge"
    exit 1
fi
. /usr/local/sbin/e
if [ -z "$SANITIZER" ]; then
    export SANITIZER='none'
    export LABEL='none'$LABEL
fi

if [ ! -d "/src-orig" ]; then
#----------------------------------------------------------------------
    #RUN apt-get update && apt-get install -y cmake
    #rm -rf $PROJECT_NAME
    #git clone --depth 1 -b develop https://github.com/nlohmann/json.git
    cp -r /downloads/cjson $SRC

    cp /opt/oss-fuzz/projects/$PROJECT_NAME/build.sh $SRC/

#----------------------------------------------------------------------
    build-cleanup-oss
fi
build-srcfolders
if [ "$4" == "skip" ]; then
    chown -hR hacker:hacker /src-$LABEL /out
    rm -rf /tmp/build.lck
else
    mv /src-$LABEL /src

    cd $SRC/$PROJECT_NAME
    if [ "$4" = "understanding" ]; then
        understanding $2 $3
    elif [ "$4" = "planning" ]; then
        planning $2 $3
    else
        if [ $(echo -n "$2" | sha256sum | cut -d' ' -f1) != "2ed73ee0d7ad2fd8b8e57fc154cfc26f3948ed32b2844b34479333e5b07712a5" ]; then
            oss_help
            exit 1
        fi
        fuzzlog
        compile
        drivers > /dev/null
    fi
    mv /src /src-$LABEL
fi
