#!/opt/pwn.college/bash
if [ $(echo -n "$1" | sha256sum | cut -d' ' -f1) != "2ed73ee0d7ad2fd8b8e57fc154cfc26f3948ed32b2844b34479333e5b07712a5" ]; then
    echo Call this script using ossfuzz commands only
    echo
    echo Run: \'. ossfuzz\' then \'python3 infra/helper.py  {command} {project name} {options}\'
    echo
    exit 1
fi
/usr/local/sbin/fi