#!/opt/pwn.college/bash
echo 100 > /tmp/initial
echo 100 > /tmp/target
if [ "$1" = "afl" ]; then
    . /usr/local/sbin/eafl
    shift
else
    . /usr/local/sbin/e
fi
export PROJECT_NAME=zlib
export SANITIZER=$1
[ -z "$SANITIZER" ] && export SANITIZER='none'
cd $SRC

#apt-get update && apt-get install -y make autoconf automake libtool
#git clone --depth 1 https://github.com/swirsz/zlib
cp -r /opt/fuzz-targets/zlib $SRC

cp /opt/oss-fuzz-new/projects/$PROJECT_NAME/*_fuzzer.c* $SRC/

cp /opt/oss-fuzz-new/projects/$PROJECT_NAME/build.sh $SRC/
cd $SRC/$PROJECT_NAME
if [ ! -d "/home/hacker/training-crashes" ]; then
   mkdir /home/hacker/training-crashes
   cp $SRC/minigzip_fuzzer.c $SRC/new_fuzzer.c
   cp $SRC/*.c* /home/hacker/training-crashes
   cp /opt/oss-fuzz-new/projects/$PROJECT_NAME/build.sh /home/hacker/training-crashes
   chown -R hacker /home/hacker/training-crashes
else
   cp /home/hacker/training-crashes/*.c* $SRC
   cp /home/hacker/training-crashes/build.sh $SRC
fi
#patch -tuN $SRC/build.sh -i /challenge/.build.patch -r -
mkdir -p /home/hacker/.log
[ ! "$SANITIZER" = "introspector" ] && [ ! "$SANITIZER" = "coverage" ] && zip -ry /home/hacker/.log/$(TZ=US/Arizona date +"%F--%H-%M-%S")-training-crashes /home/hacker/training-crashes
sudo --preserve-env compile
drivers
