#!/opt/pwn.college/bash
if [ "$1" = "afl" ]; then
    . /usr/local/sbin/eafl
    shift
else
    . /usr/local/sbin/e
fi
export PROJECT_NAME=zlib
export SANITIZER=$1
[ -z "$SANITIZER" ] && export SANITIZER='none'

if [ ! -d "/src-orig" ]; then
    #apt-get update && apt-get install -y make autoconf automake libtool
    #git clone --depth 1 https://github.com/swirsz/zlib
    cp -r /opt/fuzz-targets/zlib $SRC

    cp /opt/oss-fuzz-new/projects/$PROJECT_NAME/*_fuzzer.c* $SRC/

    cp $SRC/minigzip_fuzzer.c $SRC/new_fuzzer.c
    cp /opt/oss-fuzz-new/projects/$PROJECT_NAME/build.sh $SRC/
    echo Please wait, initial setup
    chown -hR hacker:hacker $SRC/$PROJECT_NAME
    mv /src /src-orig
fi
if [ ! -d "/src-$SANITIZER" ]; then
    echo Please wait, initial setup
    cp -r /src-orig /src-$SANITIZER
fi
mv /src-$SANITIZER /src

cd $SRC/$PROJECT_NAME
if [ ! -d "/home/hacker/fuzz-dojo/training-crashes" ]; then
   mkdir /home/hacker/fuzz-dojo/training-crashes
   cp $SRC/*.c* /home/hacker/fuzz-dojo/training-crashes
   cp /opt/oss-fuzz-new/projects/$PROJECT_NAME/build.sh /home/hacker/fuzz-dojo/training-crashes
   chown -R hacker /home/hacker/fuzz-dojo/training-crashes
else
   cp /home/hacker/fuzz-dojo/training-crashes/*.c* $SRC
   cp /home/hacker/fuzz-dojo/training-crashes/build.sh $SRC
fi
#patch -tuN $SRC/build.sh -i /challenge/.build.patch -r -
mkdir -p /home/hacker/.log
[ ! "$SANITIZER" = "introspector" ] && [ ! "$SANITIZER" = "coverage" ] && zip -ry /home/hacker/.log/$(TZ=US/Arizona date +"%F--%H-%M-%S")-training-crashes /home/hacker/fuzz-dojo/training-crashes
sudo --preserve-env compile
drivers
chown -hR hacker:hacker $SRC/$PROJECT_NAME
mv /src /src-$SANITIZER
