#!/opt/pwn.college/bash
if [ "$1" = "afl" ]; then
    . /usr/local/sbin/eafl
    shift
    export LABEL=$1$FUZZING_ENGINE
else
    . /usr/local/sbin/e
    export LABEL=$1
fi
export PROJECT_NAME=zlib
export SANITIZER=$1
if [ -z "$SANITIZER" ]; then
    export SANITIZER='none'
    export LABEL='none'$LABEL
fi

if [ ! -d "/src-orig" ]; then
#----------------------------------------------------------------------
    #apt-get update && apt-get install -y make autoconf automake libtool
    #git clone --depth 1 https://github.com/swirsz/zlib
    cp -r /downloads/swzlib $SRC/zlib

    cp /opt/oss-fuzz/projects/$PROJECT_NAME/*_fuzzer.c* $SRC/

    cp $SRC/minigzip_fuzzer.c $SRC/new_fuzzer.c
    cp /opt/oss-fuzz/projects/$PROJECT_NAME/build.sh $SRC/
#----------------------------------------------------------------------
    build-cleanup
fi
build-srcfolders
mv /src-$LABEL /src

cd $SRC/$PROJECT_NAME
#----------------------------------------------------------------------
if [ ! -d "/home/hacker/fuzz-dojo/training-crashes" ]; then
   mkdir -p /home/hacker/fuzz-dojo/training-crashes
   cp $SRC/*.c* /home/hacker/fuzz-dojo/training-crashes
   cp /opt/oss-fuzz/projects/$PROJECT_NAME/build.sh /home/hacker/fuzz-dojo/training-crashes
else
   cp /home/hacker/fuzz-dojo/training-crashes/*.c* $SRC
   cp /home/hacker/fuzz-dojo/training-crashes/build.sh $SRC
fi
#----------------------------------------------------------------------
#patch -tuN $SRC/build.sh -i /challenge/.build.patch -r -
mkdir -p /home/hacker/.log
[ ! "$SANITIZER" = "introspector" ] && [ ! "$SANITIZER" = "coverage" ] && zip -ry /home/hacker/.log/$(TZ=US/Arizona date +"%F--%H-%M-%S")-training-crashes /home/hacker/fuzz-dojo/training-crashes
compile
drivers
find $SRC -not -user hacker -print | xargs -n 100 -P 8 chown hacker:hacker /home/hacker/fuzz-dojo /home/hacker/.log /out
mv /src /src-$LABEL
