#!/opt/pwn.college/bash
INITIAL=100
TARGET=100
/usr/local/sbin/loc_count $INITIAL $TARGET $@

if compgen -G "/out/timeout-*" > /dev/null
then
    echo
    echo "Timeouts detected within the /out directory!"
    echo
elif compgen -G "/out/crash-*" > /dev/null
then
    echo
    echo "Crashes detected within the /out directory!"
    echo
else
    echo
    echo Congratulations!  No crashes detected.
    cat /flag
fi
