#!/opt/pwn.college/bash
. /usr/local/sbin/eafl
export PROJECT_NAME=exiv2
export SANITIZER=$1
[ -z "$SANITIZER" ] && export SANITIZER='none'
cd $SRC

git clone https://github.com/Exiv2/exiv2 exiv2
./exiv2/ci/install_dependencies.sh

cp /opt/oss-fuzz/projects/$PROJECT_NAME/build.sh $SRC/

cd $SRC/$PROJECT_NAME

sudo --preserve-env compile
drivers
