#!/opt/pwn.college/bash
if [ "$1" = "afl" ]; then
    . /usr/local/sbin/eafl
    shift
else
    . /usr/local/sbin/e
fi
export PROJECT_NAME=e2fsprogs
export SANITIZER=$1
[ -z "$SANITIZER" ] && export SANITIZER='none'
cd $SRC

rm -rf /src/e2fsprogs
rm -rf /src/fuzz

#apt-get install -y --allow-downgrades --allow-remove-essential --allow-change-held-packages git make texinfo
#git clone --depth 1 https://github.com/tytso/e2fsprogs
cp -r /opt/fuzz-targets/e2fsprogs /src

cp /opt/oss-fuzz/projects/$PROJECT_NAME/build.sh $SRC/
cp -r /opt/oss-fuzz/projects/$PROJECT_NAME/fuzz $SRC/

patch -tuN /src/e2fsprogs/Makefile -i /challenge/.Makefile.patch -r -
cd $SRC/$PROJECT_NAME
if [ ! -d "/home/hacker/$PROJECT_NAME" ]; then
   mkdir /home/hacker/$PROJECT_NAME
   cp $SRC/$PROJECT_NAME/fuzz/fuzz-consume-record.c $SRC/$PROJECT_NAME/fuzz/fuzz-newfuzzer.c
   cp $SRC/$PROJECT_NAME/fuzz/*.c /home/hacker/$PROJECT_NAME
   cp /src/build.sh /home/hacker/$PROJECT_NAME
   chown -R hacker /home/hacker/$PROJECT_NAME
else
   cp /home/hacker/$PROJECT_NAME/*.c $SRC/$PROJECT_NAME/fuzz
   cp /home/hacker/$PROJECT_NAME/build.sh $SRC
fi

sudo --preserve-env compile
drivers
