#!/opt/pwn.college/bash
. /usr/local/sbin/e
export LABEL=$1
export PROJECT_NAME=miniz
export SANITIZER=$1
if [ -z "$SANITIZER" ]; then
    export SANITIZER='none'
    export LABEL='none'$LABEL
fi

if [ ! -d "/src-orig" ]; then
    #git clone --depth 1 https://github.com/richgel999/miniz.git
    cp -r /downloads/miniz $SRC

    cp /opt/oss-fuzz-new/projects/$PROJECT_NAME/build.sh $SRC/

    cp $SRC/$PROJECT_NAME/tests/compress_fuzzer.c $SRC/$PROJECT_NAME/tests/new_fuzzer.c
    #patch -tuN $SRC/build.sh -i /challenge/.build.patch -r -
    echo Please wait, creating /src-orig
    find $SRC -not -user hacker -print | sudo xargs -n 100 -P 8 chown hacker:hacker
    mv /src /src-orig
fi
if [ ! -d "/src-$LABEL" ]; then
    echo Please wait, creating /src-$LABEL
    cp -r /src-orig /src-$LABEL
fi
mv /src-$LABEL /src
rm -rf $SRC/$PROJECT_NAME/build

cd $SRC/$PROJECT_NAME
if [ ! -d "/home/hacker/fuzz-dojo/$PROJECT_NAME" ]; then
   mkdir -p /home/hacker/fuzz-dojo/$PROJECT_NAME
   cp $SRC/$PROJECT_NAME/tests/*.c /home/hacker/fuzz-dojo/$PROJECT_NAME
   cp $SRC/build.sh /home/hacker/fuzz-dojo/$PROJECT_NAME
   chown -R hacker /home/hacker/fuzz-dojo/$PROJECT_NAME
else
   cp /home/hacker/fuzz-dojo/$PROJECT_NAME/*.c $SRC/$PROJECT_NAME/tests
   cp /home/hacker/fuzz-dojo/$PROJECT_NAME/build.sh $SRC
fi
fuzzlog
compile
drivers
mv /src /src-$LABEL
