#!/opt/pwn.college/bash
if [ "$?" -gt 0 ]; then
    exit 1
fi
. /usr/local/sbin/e
export LABEL=$1
export PROJECT_NAME=guetzli
export SANITIZER=$1
if [ -z "$SANITIZER" ]; then
    export SANITIZER='none'
    export LABEL='none'$LABEL
fi

if [ ! -d "/src-orig" ]; then
#----------------------------------------------------------------------
    #apt-get update && apt-get install -y make autoconf automake libtool libpng-dev pkg-config curl

    #mkdir afl-testcases
    #cd afl-testcases/ && curl https://lcamtuf.coredump.cx/afl/demo/afl_testcases.tgz | tar -xz
    cd $SRC
    cp -r /downloads/afl-testcases $SRC

    zip guetzli_fuzzer_seed_corpus.zip afl-testcases/jpeg/full/images/* afl-testcases/jpeg_turbo/full/images/*

    #git clone --depth=1 https://github.com/google/guetzli 
    cp -r /downloads/guetzli $SRC

    cp /opt/oss-fuzz/projects/$PROJECT_NAME/build.sh $SRC/
#----------------------------------------------------------------------
    build-cleanup-oss
fi
build-srcfolders
mv /src-$LABEL /src

cd $SRC/$PROJECT_NAME
if [ "$4" = "understanding" ]; then
    understanding $2 $3
elif [ "$4" = "planning" ]; then
    planning $2 $3
else
    if [ $(echo -n "$2" | sha256sum | cut -d' ' -f1) != "2ed73ee0d7ad2fd8b8e57fc154cfc26f3948ed32b2844b34479333e5b07712a5" ]; then
        echo Call this script using ossfuzz commands only
        echo
        echo Run: \'. ossfuzz\' then \'python3 infra/helper.py  {command} {project name} {options}\'
        echo
        exit 1
    fi
    fuzzlog
    compile
    drivers > /dev/null
fi
mv /src /src-$LABEL
