#!/bin/sh
. /usr/local/sbin/e.sh
PROJECT_NAME=bzip2
[ -z "$SANITIZER" ] && export SANITIZER='none'
cd $SRC

apt-get update && apt-get install -y make autoconf automake libtool wget
git clone git://sourceware.org/git/bzip2.git
cp /opt/oss-fuzz/projects/$PROJECT_NAME/build.sh /opt/oss-fuzz/projects/$PROJECT_NAME/*.c $SRC/
cd $SRC
compile
