#!/bin/bash
DRIVERS=('bzip2_fd' 'bzip2_decompress_target' 'bzip2_compress_target' 'bzip2_filename')
export PROJECT_NAME='bzip2' 

. /usr/local/sbin/e.sh
cd $SRC
/challenge/loc

export SANITIZER='introspector'
compile

rm -rf /out/introspector-report
mkdir -p /out/introspector-report
mv /out/inspector /out/introspector-report/inspector
mv /out/report /out/introspector-report/inspector/covreport

for driver in "${DRIVERS[@]}"
do
    mv /out/report_target/$driver /out/introspector-report/inspector/covreport/$driver
done

python3 -m http.server 8008 --directory /out/introspector-report/inspector/
