#!/bin/bash
DRIVERS=('bzip2_fd' 'bzip2_decompress_target' 'bzip2_compress_target' 'bzip2_filename')
export PROJECT_NAME='bzip2' 

. /usr/local/sbin/e.sh
export SANITIZER='none'
#apt-get update && apt-get install -y make autoconf automake libtool wget
rm -rf $SRC/bzip2
git clone git://sourceware.org/git/bzip2.git $SRC/bzip2
cp -f /opt/oss-fuzz/projects/bzip2/build.sh /opt/oss-fuzz/projects/bzip2/*.c $SRC/
cd $SRC
compile

parallel run_fuzzer ::: ${DRIVERS[@]} ::: -max_total_time=5

export SANITIZER='coverage'
compile

for driver in "${DRIVERS[@]}"
do
    rm -rf /corpus/$driver
    mv /tmp/${driver}_corpus /corpus/$driver
done

coverage

export SANITIZER='introspector'
compile

rm -rf /out/introspector-report
mkdir -p /out/introspector-report
mv /out/inspector /out/introspector-report/inspector
mv /out/report /out/introspector-report/inspector/covreport

for driver in "${DRIVERS[@]}"
do
    mv /out/report_target/$driver /out/introspector-report/inspector/covreport/$driver
done

python3 -m http.server 8008 --directory /out/introspector-report/inspector/
