#!/bin/bash
DRIVERS=('bzip2_fd' 'bzip2_decompress_target' 'bzip2_compress_target' 'bzip2_filename')

. /usr/local/sbin/e.sh
export SANITIZER='none'
#apt-get update && apt-get install -y make autoconf automake libtool wget
git clone git://sourceware.org/git/bzip2.git $SRC/bzip2
cp /opt/oss-fuzz/projects/bzip2/build.sh /opt/oss-fuzz/projects/bzip2/*.c $SRC/
cd $SRC
compile

parallel run_fuzzer ::: ${DRIVERS[@]} ::: -max_total_time=5

export SANITIZER='coverage'
compile

for driver in "${DRIVERS[@]}"
do
    mv /tmp/${driver}_corpus /corpus/$driver
done

#pip3 install Jinja2
coverage

for driver in "${DRIVERS[@]}"
do
    /usr/local/sbin/loc.py bzip2 $driver
done

