#!/opt/pwn.college/bash
. /usr/local/sbin/e
LABEL=$1
export PROJECT_NAME=uriparser
export SANITIZER=$1
if [ -z "$SANITIZER" ]; then
    export SANITIZER='none'
    LABEL='none'
fi

SRC=/src-$LABEL

if [ "$LABEL" = "none" ]; then
    FLAGS=""
elif [ "$LABEL" = "address" ]; then
    FLAGS=$SANITIZER_FLAGS_address
elif [ "$LABEL" = "memory" ]; then
    FLAGS=$SANITIZER_FLAGS_memory
elif [ "$LABEL" = "undefined" ]; then
    FLAGS=$SANITIZER_FLAGS_undefined
elif [ "$LABEL" = "thread" ]; then
    FLAGS=$SANITIZER_FLAGS_thread
fi
set -x

cp /home/hacker/fuzz-dojo/$PROJECT_NAME/N*.cpp $SRC/$PROJECT_NAME/fuzz

mv $SRC /src
cd /src/$PROJECT_NAME

sudo --preserve-env compile

mv /src $SRC
chown -hR hacker:hacker $SRC /home/hacker/fuzz-dojo /home/hacker/.log /out
