#!/opt/pwn.college/bash
. /usr/local/sbin/e
if [ "$?" -gt 0 ]; then
    exit 1
fi
export LABEL=$1
export PROJECT_NAME=lame
export SANITIZER=$1
if [ -z "$SANITIZER" ]; then
    export SANITIZER='none'
    export LABEL='none'$LABEL
fi

if [ ! -d "/src-orig" ]; then
#----------------------------------------------------------------------
    #apt-get update && apt-get install -y make autoconf automake libtool subversion pkg-config wget
    cd $SRC
    rm -rf lame
    rm -rf LAME-fuzzers
    rm -rf mpg123

    # ubuntu apt has not recent enough mpg123
    #wget https://www.mpg123.de/snapshot
    cp /downloads/snapshot/* $SRC
    tar -xvf snapshot
    mv mpg123* mpg123

    #git clone --depth 1 https://github.com/guidovranken/LAME-fuzzers
    cp -r /downloads/LAME-fuzzers $SRC

    #svn checkout https://svn.code.sf.net/p/lame/svn/trunk/lame $SRC/lame
    cp -r /downloads/lame $SRC

    # This is to fix Fuzz Introspector build by using LLVM old pass manager
    # re https://github.com/ossf/fuzz-introspector/issues/305
    export OLD_LLVMPASS=1
    cd /
    cp /opt/oss-fuzz/projects/$PROJECT_NAME/build.sh $SRC/

    cp $SRC/LAME-fuzzers/fuzzer-encoder.cpp $SRC/LAME-fuzzers/fuzzer-new.cpp
    cp $SRC/LAME-fuzzers/fuzzer-encoder.dict $SRC/LAME-fuzzers/fuzzer-new.dict
    cp $SRC/LAME-fuzzers/fuzzer-encoder_seed_corpus.zip $SRC/LAME-fuzzers/fuzzer-new_seed_corpus.zip
    patch -tuN $SRC/build.sh -i /challenge/.build.patch -r -
#----------------------------------------------------------------------
    build-cleanup
fi
build-srcfolders
mv /src-$LABEL /src

cd $SRC/
#----------------------------------------------------------------------
if [ ! -d "/home/hacker/fuzz-dojo/$PROJECT_NAME" ]; then
   mkdir -p /home/hacker/fuzz-dojo/$PROJECT_NAME
   cp -r $SRC/LAME-fuzzers/* /home/hacker/fuzz-dojo/$PROJECT_NAME
   cp $SRC/build.sh /home/hacker/fuzz-dojo/$PROJECT_NAME
else
   cp /home/hacker/fuzz-dojo/$PROJECT_NAME/*.cpp $SRC/LAME-fuzzers
   cp /home/hacker/fuzz-dojo/$PROJECT_NAME/*.dict $SRC/LAME-fuzzers
   cp /home/hacker/fuzz-dojo/$PROJECT_NAME/*.zip $SRC/LAME-fuzzers
   cp /home/hacker/fuzz-dojo/$PROJECT_NAME/build.sh $SRC
fi
#----------------------------------------------------------------------
if [ "$4" = "understanding" ]; then
    understanding $2 $3
elif [ "$4" = "planning" ]; then
    planning $2 $3
else
    fuzzlog
    compile
    drivers
fi
mv /src /src-$LABEL