#!/bin/bash
export PROJECT_NAME=lame
/usr/local/sbin/loc_count
cd /src
rm -rf lame
rm -rf LAME-fuzzers
rm -rf mpg123
rm -rf expat-2.4.1

# ubuntu apt has not recent enough mpg123
wget https://www.mpg123.de/snapshot
tar -xvf snapshot
mv mpg123* mpg123

git clone --depth 1 https://github.com/guidovranken/LAME-fuzzers

svn checkout https://svn.code.sf.net/p/lame/svn/trunk/lame $SRC/lame

# This is to fix Fuzz Introspector build by using LLVM old pass manager
# re https://github.com/ossf/fuzz-introspector/issues/305
export OLD_LLVMPASS=1

/usr/local/sbin/fi $PROJECT_NAME
