#!/opt/pwn.college/bash
if [ "$?" -gt 0 ]; then
    exit 1
fi
export LABEL=$1
export PROJECT_NAME=apache-httpd
export SANITIZER=$1
. /usr/local/sbin/e
if [ -z "$SANITIZER" ]; then
    export SANITIZER='none'
    export LABEL='none'$LABEL
fi

if [ ! -d "/src-orig" ]; then
#----------------------------------------------------------------------
    #apt-get update && apt-get install -y make autoconf automake libtool wget uuid-dev pkg-config libtool-bin libbsd-dev

    #git clone https://github.com/PCRE2Project/pcre2 pcre2 && \
        #cd pcre2 && ./autogen.sh && ./configure && make && make install

    #git clone https://github.com/AdaLogics/fuzz-headers
    cp -r /downloads/fuzz-headers $SRC
    cp -r /downloads/pcre2 $SRC/pcre2
    cd $SRC/pcre2
        ./autogen.sh 
        ./configure
        make
        make install 
    cd $SRC

    #wget https://github.com/libexpat/libexpat/releases/download/R_2_4_1/expat-2.4.1.tar.gz && \
    # tar -xf expat-2.4.1.tar.gz && cd expat-2.4.1 && ./configure && make && make install
        
    rm -rf $SRC/httpd
    #git clone --depth=1 https://github.com/apache/httpd
    cp -r /downloads/httpd $SRC

    cp /opt/oss-fuzz/projects/$PROJECT_NAME/fuzz_*.c $SRC/
    cp /opt/oss-fuzz/projects/$PROJECT_NAME/build.sh $SRC/

    cd /
    patch -tuN $SRC/build.sh -i /challenge/.build.patch -r -
#----------------------------------------------------------------------
    build-cleanup-oss
fi
build-srcfolders
if [ "$4" == "skip" ]; then
    chown -hR hacker:hacker /src-$LABEL /out
    rm -rf /tmp/build.lck
else
    mv /src-$LABEL /src

    cd $SRC/$PROJECT_NAME
    if [ "$4" = "understanding" ]; then
        understanding_oss $2 $3
    elif [ "$4" = "planning" ]; then
        planning $2 $3
    else
        if [ $(echo -n "$2" | sha256sum | cut -d' ' -f1) != "2ed73ee0d7ad2fd8b8e57fc154cfc26f3948ed32b2844b34479333e5b07712a5" ]; then
            oss_help
            rm -rf /tmp/build.lck
            mv /src /src-$LABEL
            exit 1
        elif [ "$3" != "$PROJECT_NAME" ]; then
            echo "[ERROR] Project $3 not available in this challenge"
            rm -rf /tmp/build.lck
            mv /src /src-$LABEL
            exit 1
        fi
        fuzzlog_oss $SRC/$PROJECT_NAME/fuzz/*
        compile
        drivers > /dev/null
    fi
    mv /src /src-$LABEL
fi
