#!/bin/sh
. /usr/local/sbin/e
export PROJECT_NAME=$PROJECT_NAME
export SANITIZER=$1
[ -z "$SANITIZER" ] && export SANITIZER='none'
cd $SRC

#apt-get update && apt-get install -y cmake ninja-build

rm -rf $SRC/$PROJECT_NAME
git clone --depth 1 --branch master https://github.com/fmtlib/fmt.git

cp /opt/oss-fuzz/projects/$PROJECT_NAME/build.sh $SRC/

cd $SRC/$PROJECT_NAME
if [ ! -d "/home/hacker/$PROJECT_NAME" ]; then
   mkdir /home/hacker/$PROJECT_NAME
   cp $SRC/$PROJECT_NAME/test/fuzzing/one-arg.cc $SRC/$PROJECT_NAME/test/fuzzing/newfuzzer.cc
   cp $SRC/$PROJECT_NAME/test/fuzzing/CMakeLists.txt /home/hacker/$PROJECT_NAME
   cp $SRC/$PROJECT_NAME/test/fuzzing/*.h /home/hacker/$PROJECT_NAME
   cp $SRC/$PROJECT_NAME/test/fuzzing/*.cc /home/hacker/$PROJECT_NAME
   cp /opt/oss-fuzz/projects/$PROJECT_NAME/build.sh /home/hacker/$PROJECT_NAME
else
   cp /home/hacker/$PROJECT_NAME/* $SRC/$PROJECT_NAME/test/fuzzing
fi
#patch -tuN /src/build.sh -i /challenge/build.patch -r -
compile