#!/bin/bash
export PROJECT_NAME=fmt
sudo cp /usr/local/sbin/loc_count /usr/local/sbin/fi /challenge
sudo chmod 4755 /challenge/loc_count /challenge/fi
/challenge/loc_count
cd /src
#apt-get update && apt-get install -y cmake ninja-build
rm -rf /src/$PROJECT_NAME
git clone --depth 1 --branch master https://github.com/fmtlib/fmt.git
cd /src/$PROJECT_NAME
/challenge/fi $PROJECT_NAME
