#!/opt/pwn.college/bash
. /usr/local/sbin/e
if [ "$?" -gt 0 ]; then
    exit 1
fi
export LABEL=$1
export PROJECT_NAME=arduinojson
export SANITIZER=$1
if [ -z "$SANITIZER" ]; then
    export SANITIZER='none'
    export LABEL='none'$LABEL
fi

if [ ! -d "/src-orig" ]; then
#----------------------------------------------------------------------
    #apt-get update && apt-get install -y make zip git
    rm -rf $SRC/$PROJECT_NAME
    #git clone --depth 1 https://github.com/bblanchon/ArduinoJson.git arduinojson
    cp -r /downloads/arduinojson $SRC

    cp /opt/oss-fuzz/projects/$PROJECT_NAME/build.sh $SRC/

#----------------------------------------------------------------------
    build-cleanup
fi
build-srcfolders
mv /src-$LABEL /src

cd $SRC/$PROJECT_NAME
#----------------------------------------------------------------------
if [ ! -d "/home/hacker/fuzz-dojo/$PROJECT_NAME" ]; then
   mkdir -p /home/hacker/fuzz-dojo/$PROJECT_NAME
   cp $SRC/$PROJECT_NAME/extras/fuzzing/CMakeLists.txt /home/hacker/fuzz-dojo/$PROJECT_NAME/CMakeLists.txt
   cp $SRC/$PROJECT_NAME/extras/fuzzing/Makefile /home/hacker/fuzz-dojo/$PROJECT_NAME/Makefile
   cp $SRC/$PROJECT_NAME/extras/fuzzing/*.cpp /home/hacker/fuzz-dojo/$PROJECT_NAME
   cp $SRC/build.sh /home/hacker/fuzz-dojo/$PROJECT_NAME
else
   cp /home/hacker/fuzz-dojo/$PROJECT_NAME/*.cpp $SRC/$PROJECT_NAME/extras/fuzzing
   cp /home/hacker/fuzz-dojo/$PROJECT_NAME/CMakeLists.txt $SRC/$PROJECT_NAME/extras/fuzzing
   cp /home/hacker/fuzz-dojo/$PROJECT_NAME/Makefile $SRC/$PROJECT_NAME/extras/fuzzing
   cp /home/hacker/fuzz-dojo/$PROJECT_NAME/build.sh $SRC
fi
#----------------------------------------------------------------------
if [ -e "/tmp/build.lck" ]; then
  rm /tmp/build.lck
fi
mv /src /src-$LABEL

cd ~/fuzz-dojo/$PROJECT_NAME
DRIVERS=($(ls -p *.cpp | grep -v /))
for driver in "${DRIVERS[@]}"
do
    COUNT=$(diff ~/fuzz-dojo/$PROJECT_NAME/$driver /src-orig/$PROJECT_NAME/extras/fuzzing/$driver | wc -w)
    if test $COUNT -gt 10
    then
        echo Examining $driver
    else
        echo Add more comments to $driver - word count: $COUNT
        exit(0)
    fi
done
cat /flag
