#!/opt/pwn.college/bash
echo 56 > /tmp/initial
echo 61 > /tmp/target
if [ "$1" = "afl" ]; then
    . /usr/local/sbin/eafl
    shift
else
    . /usr/local/sbin/e
fi
export PROJECT_NAME=libtasn1
export SANITIZER=$1
[ -z "$SANITIZER" ] && export SANITIZER='none'
cd $SRC

rm -rf $SRC/$PROJECT_NAME
rm -rf $SRC/gnulib


#apt-get update && apt-get install -y make autoconf automake libtool bison
#git clone git://git.savannah.gnu.org/gnulib.git
export GNULIB_TOOL=$SRC/gnulib/gnulib-tool
export GNULIB_SRCDIR=$SRC/gnulib
#git clone https://gitlab.com/gnutls/libtasn1.git
cp -r /opt/fuzz-targets/gnulib $SRC
cp -r /opt/fuzz-targets/libtasn1 $SRC

cp /opt/oss-fuzz-new/projects/$PROJECT_NAME/build.sh $SRC/

#patch -tuN $SRC/build.sh -i /challenge/.build.patch -r -
cd $SRC/$PROJECT_NAME
if [ ! -d "/home/hacker/$PROJECT_NAME" ]; then
   mkdir /home/hacker/$PROJECT_NAME
   cp $SRC/$PROJECT_NAME/fuzz/libtasn1_gnutls_der_fuzzer.c  $SRC/$PROJECT_NAME/fuzz/new_fuzzer.c
   cp $SRC/$PROJECT_NAME/fuzz/*.c /home/hacker/$PROJECT_NAME
   cp $SRC/build.sh /home/hacker/$PROJECT_NAME
   chown -R hacker /home/hacker/$PROJECT_NAME
else
   cp /home/hacker/$PROJECT_NAME/*.c $SRC/$PROJECT_NAME/fuzz
   cp /home/hacker/$PROJECT_NAME/build.sh $SRC
fi
mkdir -p /home/hacker/.log
[ ! "$SANITIZER" = "introspector" ] && [ ! "$SANITIZER" = "coverage" ] && zip -ry /home/hacker/.log/$(TZ=US/Arizona date +"%F--%H-%M-%S")-$PROJECT_NAME /home/hacker/$PROJECT_NAME
sudo --preserve-env compile
drivers