#!/opt/pwn.college/bash
export PROJECT_NAME=libtasn1
/challenge/.loc_count
cd /src/$PROJECT_NAME
cp /home/hacker/$PROJECT_NAME/*.c /src/$PROJECT_NAME/fuzz
export GNULIB_TOOL=/src/gnulib/gnulib-tool
export GNULIB_SRCDIR=/src/gnulib
/challenge/.fi $PROJECT_NAME
