#!/opt/pwn.college/bash
echo 10 > /tmp/initial
echo 15 > /tmp/target
if [ "$1" = "afl" ]; then
    . /usr/local/sbin/eafl
    shift
else
    . /usr/local/sbin/e
fi
export PROJECT_NAME=xvid
export SANITIZER=$1
[ -z "$SANITIZER" ] && export SANITIZER='none'
cd $SRC

rm -rf xvidcore-install
#apt-get update && apt-get install -y make autoconf automake libtool subversion
#svn checkout http://svn.xvid.org/trunk --username anonymous --password "" --non-interactive --no-auth-cache
#git clone --depth 1 https://github.com/guidovranken/fuzzing-headers.git
#git clone --depth 1 https://github.com/guidovranken/oss-fuzz-fuzzers.git

cp -r /opt/fuzz-targets/trunk $SRC
cp -r /opt/fuzz-targets/fuzzing-headers $SRC
cp -r /opt/fuzz-targets/oss-fuzz-fuzzers $SRC

cp /opt/oss-fuzz/projects/$PROJECT_NAME/build.sh $SRC/

patch -tuN $SRC/build.sh -i /challenge/.build.patch -r -
cd $SRC
if [ ! -d "/home/hacker/$PROJECT_NAME" ]; then
   cp $SRC/oss-fuzz-fuzzers/xvid/fuzzer.cpp $SRC/oss-fuzz-fuzzers/xvid/newfuzzer.cpp
   cp -r $SRC/oss-fuzz-fuzzers/xvid /home/hacker/$PROJECT_NAME
   cp $SRC/build.sh /home/hacker/$PROJECT_NAME
   chown -R hacker /home/hacker/$PROJECT_NAME
else
   rm -rf $SRC/oss-fuzz-fuzzers/xvid
   cp -r /home/hacker/$PROJECT_NAME $SRC/oss-fuzz-fuzzers/xvid
   cp /home/hacker/$PROJECT_NAME/build.sh $SRC
fi
mkdir -p /home/hacker/.log
[ ! "$SANITIZER" = "introspector" ] && [ ! "$SANITIZER" = "coverage" ] && zip -ry /home/hacker/.log/$(TZ=US/Arizona date +"%F--%H-%M-%S")-$PROJECT_NAME /home/hacker/$PROJECT_NAME
sudo --preserve-env compile
drivers