#!/opt/pwn.college/bash
export PROJECT_NAME=xvid
/challenge/.loc_count
cd /src

rm -rf xvidcore-install
#apt-get update && apt-get install -y make autoconf automake libtool subversion
#svn checkout http://svn.xvid.org/trunk --username anonymous --password "" --non-interactive --no-auth-cache
#git clone --depth 1 https://github.com/guidovranken/fuzzing-headers.git
#git clone --depth 1 https://github.com/guidovranken/oss-fuzz-fuzzers.git

cp -r /opt/fuzz-targets/trunk /src
cp -r /opt/fuzz-targets/fuzzing-headers /src
cp -r /opt/fuzz-targets/oss-fuzz-fuzzers /src

rm -rf /src/oss-fuzz-fuzzers/xvid
cp -r /home/hacker/$PROJECT_NAME /src/oss-fuzz-fuzzers/xvid
   
/challenge/.fi $PROJECT_NAME
