#!/opt/pwn.college/bash 
INITIAL=78
TARGET=83
time sudo -H -u hacker bash -c "/challenge/.loc_count $*"
/usr/local/sbin/announce $INITIAL $? 
if [ "$?" -gt "$TARGET" ]; then
    echo
    echo Congratulations!  But make sure you also submit your improvements to Google!
    cat /flag
fi
if compgen -G "/out/crash*" > /dev/null; then
    echo
    echo "Crashes detected within the /out directory!"
    echo
fi
