#!/opt/pwn.college/bash
echo 48 > /tmp/initial
echo 53 > /tmp/target
if [ "$1" = "afl" ]; then
    . /usr/local/sbin/eafl
    shift
else
    . /usr/local/sbin/e
fi
export PROJECT_NAME=pcre2
export SANITIZER=$1
[ -z "$SANITIZER" ] && export SANITIZER='none'
cd $SRC

#apt-get update && apt-get install -y make autoconf automake libtool subversion
#git clone https://github.com/PCRE2Project/pcre2 pcre2
cp -r /opt/fuzz-targets/pcre2 $SRC

cp /opt/oss-fuzz-new/projects/$PROJECT_NAME/build.sh $SRC/

#patch -tuN $SRC/build.sh -i /challenge/.build.patch -r -
cd $SRC/$PROJECT_NAME
if [ ! -d "/home/hacker/$PROJECT_NAME" ]; then
   mkdir /home/hacker/$PROJECT_NAME
   #cp $SRC/$PROJECT_NAME/pcre2_fuzz*.dict /home/hacker/$PROJECT_NAME
   #cp $SRC/$PROJECT_NAME/pcre2_fuzz*.options /home/hacker/$PROJECT_NAME
   cp $SRC/$PROJECT_NAME/src/pcre2_fuzzsupport.c /home/hacker/$PROJECT_NAME
   chown -R hacker /home/hacker/$PROJECT_NAME
else
   #cp /home/hacker/$PROJECT_NAME/*.dict $SRC/$PROJECT_NAME
   #cp /home/hacker/$PROJECT_NAME/*.options $SRC/$PROJECT_NAME
   cp /home/hacker/$PROJECT_NAME/pcre2_fuzzsupport.c $SRC/$PROJECT_NAME/src
fi
mkdir -p /home/hacker/.log
[ ! "$SANITIZER" = "introspector" ] && [ ! "$SANITIZER" = "coverage" ] && zip -ry /home/hacker/.log/$(TZ=US/Arizona date +"%F--%H-%M-%S")-$PROJECT_NAME /home/hacker/$PROJECT_NAME
sudo --preserve-env compile
drivers
