#!/opt/pwn.college/bash
. /usr/local/sbin/e
export PROJECT_NAME=woff2
export SANITIZER=$1
[ -z "$SANITIZER" ] && export SANITIZER='none'
cd $SRC

#apt-get update && apt-get install -y make autoconf automake libtool

#git clone --depth 1 --recursive https://github.com/google/woff2
cp -r /opt/fuzz-targets/woff2 /src/woff2

cp /opt/oss-fuzz/projects/$PROJECT_NAME/*.options $SRC/
cp /opt/oss-fuzz/projects/$PROJECT_NAME/build.sh $SRC/
mkdir $SRC/corpus
cp -r /opt/oss-fuzz/projects/$PROJECT_NAME/corpus $SRC/corpus

#patch -tuN /src/build.sh -i /challenge/.build.patch -r -
cd $SRC/woff2

sudo --preserve-env compile
drivers
