#!/opt/pwn.college/bash
. /usr/local/sbin/eafl
export PROJECT_NAME=mupdf
export SANITIZER=$1
[ -z "$SANITIZER" ] && export SANITIZER='none'
cd $SRC

apt-get update && apt-get install -y make libtool pkg-config

git clone --recursive --depth 1 git://git.ghostscript.com/mupdf.git mupdf
git clone --depth 1 https://github.com/mozilla/pdf.js pdf.js && \
    zip -q $SRC/pdf_fuzzer_seed_corpus.zip pdf.js/test/pdfs/*.pdf && \
    rm -rf pdf.js
wget https://raw.githubusercontent.com/rc0r/afl-fuzz/master/dictionaries/pdf.dict
mv pdf.dict pdf_fuzzer.dict

cp /opt/oss-fuzz/projects/$PROJECT_NAME/build.sh $SRC/
cp /opt/oss-fuzz/projects/$PROJECT_NAME/*.cc $SRC/
cp /opt/oss-fuzz/projects/$PROJECT_NAME/*.options $SRC/

cd $SRC/mupdf
sudo --preserve-env compile
drivers
