#!/bin/bash
export PROJECT_NAME=php
sudo cp /usr/local/sbin/loc_count /usr/local/sbin/fi /challenge
sudo chmod 4755 /challenge/loc_count /challenge/fi
/challenge/loc_count
cd /src
rm -rf php-src
# The current clang revision is broken, pin to older one.
#FROM gcr.io/oss-fuzz-base/base-builder@sha256:111d6b9d3a52bd3392602c71dc8936c628607a7a9bc86d381db7586f9b1e840f
#RUN apt-get update && apt-get install -y autoconf automake libtool bison re2c pkg-config
git clone --depth 1 --branch master https://github.com/php/php-src.git php-src

patch -tuN $SRC/php-src/sapi/fuzzer/Makefile.frag  -i /challenge/Makefile.patch -r -
cd /src/php-src

/challenge/fi $PROJECT_NAME
