#!/bin/bash
export PROJECT_NAME=mariadb
sudo cp /usr/local/sbin/loc_count /usr/local/sbin/fi /challenge
sudo chmod 4755 /challenge/loc_count /challenge/fi
/challenge/loc_count
cd /src
rm -rf server
#apt-get install -y build-essential libncurses5-dev gnutls-dev bison zlib1g-dev ccache
git clone --depth=1 https://github.com/MariaDB/server

cd /src/server

/challenge/fi $PROJECT_NAME
