#!/bin/sh
. /usr/local/sbin/e
export PROJECT_NAME=libpcap
export SANITIZER=$1
[ -z "$SANITIZER" ] && export SANITIZER='none'
cd $SRC

#apt-get update && apt-get install -y zzzzzzzzzz
RUN apt-get update && apt-get install -y make cmake flex bison
RUN git clone --depth 1 https://github.com/the-tcpdump-group/libpcap.git libpcap
# for corpus as wireshark
RUN git clone --depth=1 https://github.com/the-tcpdump-group/tcpdump.git tcpdump
WORKDIR $SRC
COPY build.sh $SRC/

cp /opt/oss-fuzz/projects/$PROJECT_NAME/*.c $SRC/
cp /opt/oss-fuzz/projects/$PROJECT_NAME/*.cc $SRC/
zzzzzzzzzz


cp /opt/oss-fuzz/projects/$PROJECT_NAME/build.sh $SRC/

cd $SRC/
if [ ! -d "/home/hacker/$PROJECT_NAME" ]; then
   mkdir /home/hacker/$PROJECT_NAME
   cp $SRC/zzzzzzzzzz.c $SRC/newfuzzer.c
   cp $SRC/*.c /home/hacker/$PROJECT_NAME
   cp $SRC/*.cc /home/hacker/$PROJECT_NAME
   cp /opt/oss-fuzz/projects/$PROJECT_NAME/build.sh /home/hacker/$PROJECT_NAME
else
   cp /home/hacker/$PROJECT_NAME/*.c $SRC
   cp /home/hacker/$PROJECT_NAME/*.cc $SRC
   cp /home/hacker/$PROJECT_NAME/build.sh $SRC
fi
#patch -tuN /src/build.sh -i /challenge/build.patch -r -
compile