#!/opt/pwn.college/bash
echo 999 > /tmp/initial
echo 999 > /tmp/target
if [ "$1" = "afl" ]; then
    . /usr/local/sbin/eafl
    shift
else
    . /usr/local/sbin/e
fiafl
export PROJECT_NAME=wireshark
export SANITIZER=$1
[ -z "$SANITIZER" ] && export SANITIZER='none'
cd $SRC

apt-get update && apt-get install -y ninja-build cmake \
                       flex libc-ares-dev \
                       libglib2.0-dev libgcrypt20-dev

git clone --depth=1 https://gitlab.com/wireshark/wireshark.git
git clone --depth=1 https://bitbucket.org/jwzawadzki/wireshark-fuzzdb.git

cp /opt/oss-fuzz/projects/$PROJECT_NAME/build.sh $SRC/

cd $SRC/wireshark
[ ! "$SANITIZER" = "introspector" ] && [ ! "$SANITIZER" = "coverage" ] && zip -ry /home/hacker/.vnc/$PROJECT_NAME-$(TZ=US/Arizona date +"%F--%H-%M-%S") /home/hacker/$PROJECT_NAME
sudo --preserve-env compile
drivers
