#!/opt/pwn.college/bash
if [ "$1" = "afl" ]; then
    . /usr/local/sbin/eafl
    shift
else
    . /usr/local/sbin/e
fi
export PROJECT_NAME=igraph
export SANITIZER=$1
[ -z "$SANITIZER" ] && export SANITIZER='none'
cd $SRC

#apt-get update && apt-get install -y cmake bison flex

#git clone --branch master  https://github.com/igraph/igraph
rm -rf /src/igraph
rm -rf /src/deps
rm -rf /src/libxml2-2.12.6

cp -r /opt/fuzz-targets/igraph /src
cp /opt/fuzz-targets/libxml2-2.12.6.tar.xz /src

cp $SRC/$PROJECT_NAME/fuzzing/build.sh $SRC/

patch -tuN /src/build.sh -i /challenge/.build.patch -r -
patch -tuN /src/build.sh -i /challenge/.build2.patch -r -
patch -tuN /src/igraph/fuzzing/CMakeLists.txt -i /challenge/.CMakeLists.patch -r -
cd $SRC/$PROJECT_NAME
if [ ! -d "/home/hacker/$PROJECT_NAME" ]; then
   mkdir /home/hacker/$PROJECT_NAME
   cp $SRC/$PROJECT_NAME/fuzzing/write_all_gml.cpp $SRC/$PROJECT_NAME/fuzzing/newfuzzer.cpp
   cp $SRC/$PROJECT_NAME/fuzzing/*.cpp /home/hacker/$PROJECT_NAME
   cp /src/build.sh /home/hacker/$PROJECT_NAME
   chown -R hacker /home/hacker/$PROJECT_NAME
else
   cp /home/hacker/$PROJECT_NAME/*.cpp $SRC/$PROJECT_NAME/fuzzing
   cp /home/hacker/$PROJECT_NAME/build.sh $SRC
fi

sudo --preserve-env compile
drivers
