#!/opt/pwn.college/bash
if [ "$1" = "afl" ]; then
    . /usr/local/sbin/eafl
    shift
else
    . /usr/local/sbin/e
fi
export PROJECT_NAME=igraph
export SANITIZER=$1
[ -z "$SANITIZER" ] && export SANITIZER='none'
cd $SRC

#apt-get update && apt-get install -y cmake bison flex

#git clone --branch master  https://github.com/igraph/igraph
rm -rf $SRC/$PROJECT_NAME
rm -rf /src/deps

cp -r /opt/fuzz-targets/igraph /src
cp /opt/fuzz-targets/libxml2-2.12.6.tar.xz /src

cp $SRC/$PROJECT_NAME/fuzzing/build.sh $SRC/

patch -tuN /src/build.sh -i /challenge/.build.patch -r -
cd $SRC/$PROJECT_NAME

sudo --preserve-env compile
drivers
