#!/opt/pwn.college/bash
. /usr/local/sbin/e
if [ "$?" -gt 0 ]; then
    exit 1
fi
export LABEL=$1
export PROJECT_NAME=c-ares
export SANITIZER=$1
if [ -z "$SANITIZER" ]; then
    export SANITIZER='none'
    export LABEL='none'$LABEL
fi

if [ ! -d "/src-orig" ]; then
#----------------------------------------------------------------------
    #apt-get update && apt-get install -y make autoconf automake libtool
    #git clone --depth 1 https://github.com/c-ares/c-ares.git
    
    #apt-get update && apt-get install -y make autoconf automake libtool pkg-config
    #RUN git clone --depth 1 https://github.com/c-ares/c-ares.git
    #RUN git clone --depth 1 https://github.com/google/googletest

    #WORKDIR c-ares
    #COPY build.sh run_tests.sh $SRC/
    
    cp -r /downloads/c-ares $SRC
    cp -r /downloads/googletest $SRC
    #export OLD_LLVMPASS=1

    cp /opt/oss-fuzz/projects/$PROJECT_NAME/build.sh $SRC/
    #patch -tuN $SRC/build.sh -i /challenge/.build.patch -r -
    cp /opt/oss-fuzz/projects/$PROJECT_NAME/run_tests.sh $SRC/
#----------------------------------------------------------------------
    build-cleanup
fi
build-srcfolders
mv /src-$LABEL /src

cd $SRC/$PROJECT_NAME

#----------------------------------------------------------------------
if [ ! -d "/home/hacker/fuzz-dojo/$PROJECT_NAME" ]; then
   mkdir -p /home/hacker/fuzz-dojo/$PROJECT_NAME
   cp $SRC/$PROJECT_NAME/test/*.c /home/hacker/fuzz-dojo/$PROJECT_NAME
   cp $SRC/build.sh /home/hacker/fuzz-dojo/$PROJECT_NAME
else
   cp /home/hacker/fuzz-dojo/$PROJECT_NAME/*.c $SRC/$PROJECT_NAME/test
   cp /home/hacker/fuzz-dojo/$PROJECT_NAME/build.sh $SRC
fi
#----------------------------------------------------------------------
if [ "$4" = "understanding" ]; then
    understanding $2 $3
elif [ "$4" = "planning" ]; then
    planning $2 $3
else
    fuzzlog
    compile
    drivers
fi
mv /src /src-$LABEL
