#!/opt/pwn.college/bash
. /usr/local/sbin/eafl
export PROJECT_NAME=xpdf
export SANITIZER=$1
[ -z "$SANITIZER" ] && export SANITIZER='none'
cd $SRC

git clone --depth 1 https://gitlab.freedesktop.org/freetype/freetype

apt-get update
apt-get install --no-install-recommends -y make wget cmake qtbase5-dev libcups2-dev autoconf automake autotools-dev libtool
wget https://dl.xpdfreader.com/xpdf-latest.tar.gz

cp /opt/oss-fuzz/projects/$PROJECT_NAME/fuzz_*.cc $SRC/
cp /opt/oss-fuzz/projects/$PROJECT_NAME/fuzz_*.options $SRC/
cp /opt/oss-fuzz/projects/$PROJECT_NAME/build.sh $SRC/

cd $SRC/

sudo --preserve-env compile
drivers
