#!/bin/sh
. /usr/local/sbin/e
export PROJECT_NAME=mariadb
export SANITIZER=$1
[ -z "$SANITIZER" ] && export SANITIZER='none'
cd $SRC

rm -rf server
#apt-get install -y build-essential libncurses5-dev gnutls-dev bison zlib1g-dev ccache
git clone  https://github.com/MariaDB/server

cp /opt/oss-fuzz/projects/$PROJECT_NAME/*.c $SRC/
cp /opt/oss-fuzz/projects/$PROJECT_NAME/build.sh $SRC/

cd $SRC/server
if [ ! -d "/home/hacker/$PROJECT_NAME" ]; then
   mkdir /home/hacker/$PROJECT_NAME
   cp $SRC/fuzz_json.c $SRC/fuzz_new.c
   cp $SRC/*.c /home/hacker/$PROJECT_NAME
   cp /opt/oss-fuzz/projects/$PROJECT_NAME/build.sh /home/hacker/$PROJECT_NAME
else
   cp /home/hacker/$PROJECT_NAME/*.c $SRC
   cp /home/hacker/$PROJECT_NAME/build.sh $SRC
fi
#patch -tuN /src/build.sh -i /challenge/build.patch -r -
compile