#!/opt/pwn.college/bash
. /usr/local/sbin/e
export LABEL=$1
export PROJECT_NAME=args
SANITIZER=$1
if [ -z "$SANITIZER" ]; then
    SANITIZER='none'
    export LABEL='none'
fi

SRC=/src-$LABEL
if [ -z "$(find /out -mindepth 1 -maxdepth 1)" ] || [ ! -d "$SRC" ]; then
    echo "Run /challenge/build first"
    rm /tmp/build.lck
else 

if [ "$LABEL" = "none" ]; then
    export FLAGS=""
elif [ "$LABEL" = "address" ]; then
    export FLAGS=$SANITIZER_FLAGS_address
elif [ "$LABEL" = "memory" ]; then
    export FLAGS=$SANITIZER_FLAGS_memory
elif [ "$LABEL" = "undefined" ]; then
    export FLAGS=$SANITIZER_FLAGS_undefined
elif [ "$LABEL" = "thread" ]; then
    export FLAGS=$SANITIZER_FLAGS_thread
fi
set -x
#----------------------------------------------------------------------

cp /home/hacker/fuzz-dojo/$PROJECT_NAME/*.cpp $SRC/$PROJECT_NAME/fuzz
cp /home/hacker/fuzz-dojo/$PROJECT_NAME/build.sh $SRC

cd $SRC/$PROJECT_NAME

clang++ -O1 -fno-omit-frame-pointer -gline-tables-only -DFUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION -fsanitize=fuzzer-no-link -stdlib=libc++ -fsanitize=fuzzer -I$SRC/args $SRC/args/fuzz/newfuzzer_fuzzer.cpp -o /out/newfuzzer_fuzzer

#----------------------------------------------------------------------
drivers
fi
