#!/opt/pwn.college/bash
. /usr/local/sbin/e
export LABEL=$1
export PROJECT_NAME=example
export SANITIZER=$1
if [ -z "$SANITIZER" ]; then
    export SANITIZER='none'
    export LABEL='none'$LABEL
fi

if [ ! -d "/src-orig" ]; then
#----------------------------------------------------------------------
    #apt-get update && apt-get install -y make cmake pkg-config libssl-dev:i386
    #git clone https://github.com/google/oss-fuzz.git example
    cp -r /downloads/example $SRC

    cp /challenge/do_stuff_unittest.cpp $SRC/example/projects/example/my-api-repo
    cp /challenge/do_stuff_fuzzer.cpp $SRC/example/projects/example/my-api-repo
    cp /challenge/my_api.cpp $SRC/example/projects/example/my-api-repo

    cp /opt/oss-fuzz/projects/$PROJECT_NAME/build.sh $SRC/
#----------------------------------------------------------------------
    build-cleanup
fi
build-srcfolders
mv /src-$LABEL /src

cd $SRC/$PROJECT_NAME
#----------------------------------------------------------------------
if [ ! -d "/home/hacker/fuzz-dojo/training-fix-broken" ]; then
   mkdir -p /home/hacker/fuzz-dojo/training-fix-broken
   cp -r $SRC/$PROJECT_NAME/projects/example/my-api-repo/* /home/hacker/fuzz-dojo/training-fix-broken
   cp /opt/oss-fuzz/projects/$PROJECT_NAME/build.sh /home/hacker/fuzz-dojo/training-fix-broken
else
   cp /home/hacker/fuzz-dojo/training-fix-broken/* $SRC/$PROJECT_NAME/projects/example/my-api-repo
   cp /home/hacker/fuzz-dojo/training-fix-broken/build.sh $SRC
fi
export PROJECT_NAME=training-fix-broken
#----------------------------------------------------------------------
fuzzlog
compile
drivers
mv /src /src-$LABEL
