#!/opt/pwn.college/bash
echo 76 > /tmp/initial
echo 95 > /tmp/target
if [ "$1" = "afl" ]; then
    . /usr/local/sbin/eafl
    shift
else
    . /usr/local/sbin/e
fi
export PROJECT_NAME=example
export SANITIZER=$1
[ -z "$SANITIZER" ] && export SANITIZER='none'
cd $SRC

#apt-get update && apt-get install -y make cmake pkg-config libssl-dev:i386
#git clone https://github.com/google/oss-fuzz.git example
cp -r /opt/fuzz-targets/example /src

cp /challenge/do_stuff_unittest.cpp /src/example/projects/example/my-api-repo
cp /challenge/do_stuff_fuzzer.cpp /src/example/projects/example/my-api-repo
cp /challenge/my_api.cpp /src/example/projects/example/my-api-repo

cp /opt/oss-fuzz/projects/$PROJECT_NAME/build.sh $SRC/
cd $SRC/$PROJECT_NAME
if [ ! -d "/home/hacker/training-broken" ]; then
   mkdir /home/hacker/training-broken
   cp $SRC/$PROJECT_NAME/projects/example/my-api-repo/* /home/hacker/training-broken
   cp /opt/oss-fuzz/projects/$PROJECT_NAME/build.sh /home/hacker/training-broken
   chown -R hacker /home/hacker/training-broken
else
   cp /home/hacker/training-broken/* $SRC/$PROJECT_NAME/projects/example/my-api-repo
   cp /home/hacker/training-broken/build.sh $SRC
fi
#patch -tuN $SRC/$PROJECT_NAME/projects/example/my-api-repo/Makefile -i /challenge/.Makefile.patch -r -
sudo --preserve-env compile
drivers
