#!/bin/bash
export PROJECT_NAME=example
sudo cp /usr/local/sbin/loc_count /usr/local/sbin/fi /challenge
sudo chmod 4755 /challenge/loc_count /challenge/fi
/challenge/loc_count $PROJECT_NAME
cd /src/$PROJECT_NAME
/challenge/fi $PROJECT_NAME
