#!/opt/pwn.college/bash 
INITIAL=76
TARGET=95
sudo -H -u hacker bash -c "/usr/local/sbin/loc_count $1"
/usr/local/sbin/announce $INITIAL $? 
if [ "$?" -gt "$TARGET" ]; then
    echo
    echo Congratulations!
    cat /flag
    echo
else
    echo
    echo Need greater code coverage to pass this challenge!
    echo Run /challenge/fuzz-introspector to see what lines of code are not being executed.
    echo
fi
if compgen -G "/out/crash*" > /dev/null; then
    echo
    echo "Crashes detected within the /out directory!"
    echo
fi
