#!/opt/pwn.college/bash 
export PROJECT_NAME=cel-go
INITIAL=999
TARGET=999
/usr/local/sbin/loc_count $PROJECT_NAME
/usr/local/sbin/announce $INITIAL $? 
if [ "$?" -gt "$TARGET" ]; then
    echo
    echo Congratulations!  But make sure you also submit your improvements to Google!
    cat /flag
fi
