#!/opt/pwn.college/bash
. /usr/local/sbin/e
if [ "$?" -gt 0 ]; then
    exit 1
fi
export LABEL=$1
export PROJECT_NAME=usbguard
export SANITIZER=$1
if [ -z "$SANITIZER" ]; then
    export SANITIZER='none'
    export LABEL='none'$LABEL
fi

if [ ! -d "/src-orig" ]; then
#----------------------------------------------------------------------
    #apt-get update && apt-get install -y make autoconf automake libtool pkg-config libxml2-utils1 libxml2-dev xsltproc \
    #  libprotobuf-dev protobuf-compiler libdbus-1-dev libdbus-glib-1-dev libgio2.0-cil-dev libgcrypt20-dev \
    #  libpolkit-gobject-1-dev libseccomp-dev libcap-ng-dev

    #git clone https://github.com/ClusterLabs/libqb && cd libqb && \
    #    ./autogen.sh && ./configure && make && make install
    cd $SRC
    rm -rf $PROJECT_NAME
    rm -rf inspector

    #git clone --recurse-submodules --depth 1 https://github.com/USBGuard/usbguard usbguard
    cp -r /downloads/usbguard $SRC
    cp -r /downloads/libqb $SRC
    cd $SRC/libqb
    ./autogen.sh
    ./configure 
    make 
    make install 
    cd $SRC

    # This is to fix Fuzz Introspector build by using LLVM old pass manager
    # re https://github.com/ossf/fuzz-introspector/issues/305
    export OLD_LLVMPASS=1

    cp /opt/oss-fuzz/projects/$PROJECT_NAME/build.sh $SRC/

    patch -tuN $SRC/$PROJECT_NAME$SRC/Tests/Fuzzers/Makefile.am -i /challenge/.Makefile.patch -r -
    cp $SRC/$PROJECT_NAME$SRC/Tests/Fuzzers/fuzzer-uevent.cpp $SRC/$PROJECT_NAME$SRC/Tests/Fuzzers/fuzzer-new.cpp

#----------------------------------------------------------------------
    build-cleanup
fi
build-srcfolders
mv /src-$LABEL /src

cd $SRC/$PROJECT_NAME
#----------------------------------------------------------------------
if [ ! -d "/home/hacker/fuzz-dojo/$PROJECT_NAME" ]; then
   mkdir -p /home/hacker/fuzz-dojo/$PROJECT_NAME
   cp $SRC/$PROJECT_NAME$SRC/Tests/Fuzzers/*.cpp /home/hacker/fuzz-dojo/$PROJECT_NAME
   cp $SRC/$PROJECT_NAME$SRC/Tests/Fuzzers/Makefile.am /home/hacker/fuzz-dojo/$PROJECT_NAME
   cp $SRC/build.sh /home/hacker/fuzz-dojo/$PROJECT_NAME
else
   cp /home/hacker/fuzz-dojo/$PROJECT_NAME/*.cpp $SRC/$PROJECT_NAME/src/Tests/Fuzzers
   cp /home/hacker/fuzz-dojo/$PROJECT_NAME/Makefile.am $SRC/$PROJECT_NAME/src/Tests/Fuzzers
   cp /home/hacker/fuzz-dojo/$PROJECT_NAME/build.sh $SRC
fi
#----------------------------------------------------------------------
if [ ! -z "$4" ]; then
    $4 $2 $3
else
    fuzzlog
    compile
    drivers
fi
mv /src /src-$LABEL