#!/bin/bash
export PROJECT_NAME=usbguard
/usr/local/sbin/loc_count
cd /src
rm -rf $PROJECT_NAME
git clone --recurse-submodules --depth 1 https://github.com/USBGuard/usbguard usbguard
cd /src/usbguard
/usr/local/sbin/fi $PROJECT_NAME
