#!/opt/pwn.college/bash
export PROJECT_NAME=libpng
/challenge/.loc_count
cd /src

#apt-get update && \
#    apt-get install -y make autoconf automake libtool zlib1g-dev

#git clone --depth 1 https://github.com/madler/zlib.git
#git clone --depth 1 https://github.com/pnggroup/libpng.git

cp -r /opt/fuzz-targets/zlib /src
cp -r /opt/fuzz-targets/libpng /src

cp /src/libpng/contrib/oss-fuzz/build.sh /src

patch -tuN /src/build.sh -i /challenge/.build.patch -r -
cd /src/libpng

cp /home/hacker/$PROJECT_NAME/*.cc /src/$PROJECT_NAME/contrib/oss-fuzz
cp /home/hacker/$PROJECT_NAME/build.sh /src
   
/challenge/.fi $PROJECT_NAME
