#!/opt/pwn.college/bash
export PROJECT_NAME=libsass
/challenge/.loc_count
cd /src

cp -r /opt/fuzz-targets/libsass /src

# This is to fix Fuzz Introspector build by using LLVM old pass manager
# re https://github.com/ossf/fuzz-introspector/issues/305
export OLD_LLVMPASS=1

cp /opt/oss-fuzz/projects/$PROJECT_NAME/build.sh /src/
cp /opt/oss-fuzz/projects/$PROJECT_NAME/data_context_fuzzer.cc  /src/


cp /home/hacker/$PROJECT_NAME/*.cc /src
cp /home/hacker/$PROJECT_NAME/build.sh /src
/challenge/.fi $PROJECT_NAME
