#!/opt/pwn.college/bash
. /usr/local/sbin/e
if [ "$?" -gt 0 ]; then
    exit 1
fi
export LABEL=$1
export PROJECT_NAME=openssh
export SANITIZER=$1
if [ -z "$SANITIZER" ]; then
    export SANITIZER='none'
    export LABEL='none'$LABEL
fi

#if [ ! -d "/src-orig" ]; then
#----------------------------------------------------------------------
    cd $SRC
    rm -rf $SRC/$PROJECT_NAME
    #apt-get update && apt-get install -y make autoconf automake libtool
    #apt-get install -y libz-dev libssl1.1 libssl-dev libedit-dev zip
    #git clone --depth 1 https://github.com/openssh/openssh-portable openssh
    #git clone --depth 1 https://github.com/djmdjm/openssh-fuzz-cases
    cp -r /downloads/openssh $SRC
    cp -r /downloads/openssh-fuzz-cases $SRC

    cp /opt/oss-fuzz/projects/$PROJECT_NAME/build.sh $SRC/
    cp $SRC/$PROJECT_NAME/regress/misc/fuzz-harness/agent_fuzz.cc $SRC/$PROJECT_NAME/regress/misc/fuzz-harness/newfuzzer.cc

    export CFLAGS="$CFLAGS -Wno-error=implicit-function-declaration"
    patch -tuN $SRC/build.sh -i /challenge/.build.patch -r -
    patch -tuN $SRC/$PROJECT_NAME/regress/misc/fuzz-harness/Makefile -i /challenge/.Makefile.patch -r -
#----------------------------------------------------------------------
    build-cleanup2
#    mv /src /src-orig
#fi
#if [ ! -d "/src-$LABEL" ]; then
#    echo Please wait, initial setup
#    cp -r /src-orig /src-$LABEL
#fi
#mv /src-$LABEL /src

cd $SRC/$PROJECT_NAME
#----------------------------------------------------------------------
if [ ! -d "/home/hacker/fuzz-dojo/$PROJECT_NAME" ]; then
   mkdir -p /home/hacker/fuzz-dojo/$PROJECT_NAME
   cp $SRC/$PROJECT_NAME/regress/misc/fuzz-harness/*.cc /home/hacker/fuzz-dojo/$PROJECT_NAME
   cp $SRC/build.sh /home/hacker/fuzz-dojo/$PROJECT_NAME
else
   cp /home/hacker/fuzz-dojo/$PROJECT_NAME/*.cc $SRC/$PROJECT_NAME/regress/misc/fuzz-harness
   cp /home/hacker/fuzz-dojo/$PROJECT_NAME/build.sh $SRC
fi
#----------------------------------------------------------------------
if [ "$4" = "understanding" ]; then
    understanding $2 $3
elif [ "$4" = "planning" ]; then
    planning $2 $3
else
    fuzzlog
    compile
    drivers
fi
#mv /src /src-$LABEL
