#!/bin/bash
export PROJECT_NAME=openssh
sudo cp /usr/local/sbin/loc_count /usr/local/sbin/fi /challenge
sudo chmod 4755 /challenge/loc_count /challenge/fi
/challenge/loc_count
cd /src
mkdir /src/tmp
cp -f /src/openssh/regress/misc/fuzz-harness/* /src/tmp
rm -rf /src/$PROJECT_NAME
git clone --depth 1 https://github.com/openssh/openssh-portable openssh
mv -f /src/tmp/* /src/openssh/regress/misc/fuzz-harness
rmdir /src/tmp
cd /src/$PROJECT_NAME
/challenge/fi $PROJECT_NAME
