#!/bin/sh
. /usr/local/sbin/e.sh
[ -z "$SANITIZER" ] && export SANITIZER='none'

apt-get install -y make
git clone --depth 1 https://github.com/openssl/openssl.git $SRC/openssl
cd $SRC/openssl/ && git submodule update --init fuzz/corpora
cd $SRC
git clone --depth 1 --branch OpenSSL_1_1_1-stable https://github.com/openssl/openssl.git openssl111
git clone --depth 1 --branch openssl-3.0 https://github.com/openssl/openssl.git openssl30
export AFL_SKIP_OSSFUZZ=1
export AFL_LLVM_MODE_WORKAROUND=0
cp /opt/oss-fuzz/projects/openssl/build.sh /opt/oss-fuzz/projects/openssl/*.options $SRC/
cd $SRC/openssl
compile
