#!/bin/bash
export DRIVERS=('asn1' 'bignum' 'client' 'cms_111' 'crl_111' 'llvm-symbolizer' 'smime' 'asn1_111' 'bignum_111' 'client_111' 'cms_30' 'crl_30' 'pem' 'v3name' 'asn1_30' 'bignum_30' 'client_30' 'conf' 'ct' 'punycode' 'x509' 'asn1parse' ' bndiv' 'cmp' 'conf_111' 'ct_111' 'server' 'x509_111' 'asn1parse_111' 'bndiv_111' 'cmp_30' 'conf_30' 'ct_30' 'server_111' 'x509_30' 'asn1parse_30' 'bndiv_30' 'cms' 'crl' 'decoder' 'server_30')
export PROJECT_NAME=openssl
/usr/local/sbin/loc_count.sh $PROJECT_NAME "${DRIVERS[@]}"
