#!/opt/pwn.college/bash
. /usr/local/sbin/e
if [ "$?" -gt 0 ]; then
    exit 1
fi
export LABEL=$1
export PROJECT_NAME=wavpack
export SANITIZER=$1
if [ -z "$SANITIZER" ]; then
    export SANITIZER='none'
    export LABEL='none'$LABEL
fi

if [ ! -d "/src-orig" ]; then
#----------------------------------------------------------------------
    #apt-get update && apt-get install -y make autoconf automake libtool gettext
    #git clone --depth 1 https://github.com/dbry/WavPack.git wavpack

    cp -r /downloads/wavpack $SRC

    cp $SRC/wavpack/fuzzing/build.sh $SRC
    cp $SRC/$PROJECT_NAME/fuzzing/fuzzer.cc $SRC/$PROJECT_NAME/fuzzing/newfuzzer.cc
    cp $SRC/$PROJECT_NAME/fuzzing/fuzzer.dict $SRC/$PROJECT_NAME/fuzzing/newfuzzer.dict
    cp $SRC/$PROJECT_NAME/fuzzing/fuzzer.options $SRC/$PROJECT_NAME/fuzzing/newfuzzer.options
    cp $SRC/$PROJECT_NAME/fuzzing/fuzzer_seed_corpus.zip $SRC/$PROJECT_NAME/fuzzing/newfuzzer_seed_corpus.zip
   
    patch -tuN $SRC/build.sh -i /challenge/.build.patch -r -
#----------------------------------------------------------------------
    build-cleanup
fi
build-srcfolders
mv /src-$LABEL /src

cd $SRC/$PROJECT_NAME
#----------------------------------------------------------------------
if [ ! -d "/home/hacker/fuzz-dojo/$PROJECT_NAME" ]; then
   mkdir -p /home/hacker/fuzz-dojo/$PROJECT_NAME
   cp $SRC/$PROJECT_NAME/fuzzing/*.cc /home/hacker/fuzz-dojo/$PROJECT_NAME
   cp $SRC/$PROJECT_NAME/fuzzing/*.dict /home/hacker/fuzz-dojo/$PROJECT_NAME
   cp $SRC/$PROJECT_NAME/fuzzing/*.options /home/hacker/fuzz-dojo/$PROJECT_NAME
   cp $SRC/$PROJECT_NAME/fuzzing/*.zip /home/hacker/fuzz-dojo/$PROJECT_NAME
   cp $SRC/build.sh /home/hacker/fuzz-dojo/$PROJECT_NAME
else
   cp /home/hacker/fuzz-dojo/$PROJECT_NAME/* $SRC/$PROJECT_NAME/fuzzing
   cp /home/hacker/fuzz-dojo/$PROJECT_NAME/build.sh $SRC
fi
#----------------------------------------------------------------------
if [ "$4" = "understanding" ]; then
    understanding $2 $3
elif [ "$4" = "planning" ]; then
    planning $2 $3
else
    fuzzlog
    compile
    drivers
fi
mv /src /src-$LABEL
