#!/opt/pwn.college/bash
. /usr/local/sbin/e
export PROJECT_NAME=liblouis
export SANITIZER=$1
[ -z "$SANITIZER" ] && export SANITIZER='none'
cd $SRC

#apt-get update && apt-get install -y make autoconf automake libtool \
#  pkg-config zlib1g-dev libpci-dev
#git clone --depth 1 https://github.com/liblouis/liblouis

cp -r /opt/fuzz-targets/liblouis /src/liblouis

cp /opt/oss-fuzz/projects/$PROJECT_NAME/build.sh $SRC/

cd $SRC/$PROJECT_NAME

sudo --preserve-env compile
drivers
