#!/bin/sh
. /usr/local/sbin/e
export PROJECT_NAME=speex
[ -z "$SANITIZER" ] && export SANITIZER='none'
cd $SRC

apt-get update && apt-get install -y make autoconf libtool pkg-config wget
git clone --depth 1 https://gitlab.xiph.org/xiph/ogg.git
git clone --depth 1 https://gitlab.xiph.org/xiph/speex.git speex

cp /opt/oss-fuzz/projects/$PROJECT_NAME/build.sh $SRC/

cd $SRC/$PROJECT_NAME
compile