#!/bin/bash
export PROJECT_NAME=speex
INITIAL=35
TARGET=50
/usr/local/sbin/loc_count $PROJECT_NAME
/usr/local/sbin/announce $INITIAL $? 
if [ "$?" -gt "$TARGET" ]; then
    echo
    echo Congratulations!  But make sure you also submit your improvements to Google!
    cat /flag
fi
