#!/opt/pwn.college/bash
. /usr/local/sbin/e
export LABEL=$1
export PROJECT_NAME=boost
export SANITIZER=$1
if [ -z "$SANITIZER" ]; then
    export SANITIZER='none'
    export LABEL='none'$LABEL
fi

if [ ! -d "/src-orig" ]; then
    rm -rf $SRC/$PROJECT_NAME

    #apt-get update && apt-get install -y g++ python
    #git clone --recursive https://github.com/boostorg/boost.git
    cp -r /downloads/boost $SRC
    # This is to fix Fuzz Introspector build by using LLVM old pass manager
    # re https://github.com/ossf/fuzz-introspector/issues/305
    export OLD_LLVMPASS=1

    cp /opt/oss-fuzz-new/projects/$PROJECT_NAME/*.cc $SRC/
    cp /opt/oss-fuzz-new/projects/$PROJECT_NAME/build.sh $SRC/

    cp $SRC/boost_regex_fuzzer.cc $SRC/boost_new_fuzzer.cc
    patch -tuN $SRC/build.sh -i /challenge/.build.patch -r -

    echo Please wait, creating /src-orig
    find $SRC -not -user hacker -print | xargs -n 100 -P 8 chown hacker:hacker
    mv /src /src-orig
fi
if [ ! -d "/src-$LABEL" ]; then
    echo Please wait, creating /src-$LABEL
    cp -r /src-orig /src-$LABEL
fi
mv /src-$LABEL /src

cd $SRC/$PROJECT_NAME
if [ ! -d "/home/hacker/fuzz-dojo/$PROJECT_NAME" ]; then
   mkdir -p /home/hacker/fuzz-dojo/$PROJECT_NAME
   cp $SRC/*.cc /home/hacker/fuzz-dojo/$PROJECT_NAME
   #cp $SRC/$PROJECT_NAME/tests/fuzz/CMakeLists.txt /home/hacker/fuzz-dojo/$PROJECT_NAME
   cp $SRC/build.sh /home/hacker/fuzz-dojo/$PROJECT_NAME
   chown -R hacker /home/hacker/fuzz-dojo/$PROJECT_NAME
else
   cp /home/hacker/fuzz-dojo/$PROJECT_NAME/*.cc $SRC
   #cp /home/hacker/fuzz-dojo/$PROJECT_NAME/CMakeLists.txt $SRC/$PROJECT_NAME/tests/fuzz
   cp /home/hacker/fuzz-dojo/$PROJECT_NAME/build.sh $SRC
fi
fuzzlog
compile
drivers
mv /src /src-$LABEL
