#!/opt/pwn.college/bash
. /usr/local/sbin/e
cp /home/hacker/fuzz-dojo/bounded_resource.h /usr/local/include/
if [ "$?" -gt 0 ]; then
    exit 1
fi
export LABEL=$1
export PROJECT_NAME=lcms
export SANITIZER=$1
if [ -z "$SANITIZER" ]; then
    export SANITIZER='none'
    export LABEL='none'$LABEL
fi

if [ ! -d "/src-orig" ]; then
#----------------------------------------------------------------------

apt-get update && apt-get install -y make autoconf automake libtool
cp -r /downloads/lcms $SRC
#git clone --depth 1 https://github.com/mm2/Little-CMS.git /src/lcms
mkdir $SRC/seeds && \
    cd $SRC/seeds && \
    cp $SRC/lcms/testbed/bad.icc . && \
    cp $SRC/lcms/testbed/toosmall.icc . && \
    cp $SRC/lcms/testbed/test1.icc . && \
    cp $SRC/lcms/testbed/crayons.icc . && \
    cp $SRC/lcms/testbed/ibm-t61.icc . && \
    #add more seeds from the testbed dir
    cp $SRC/lcms/testbed/bad_mpe.icc . && \
    cp $SRC/lcms/testbed/test2.icc . && \
    cp $SRC/lcms/testbed/test3.icc . && \
    cp $SRC/lcms/testbed/test4.icc . && \
    cp $SRC/lcms/testbed/test5.icc . && \
    zip -rj $SRC/seed_corpus.zip $SRC/seeds/*

    cp /opt/oss-fuzz/projects/$PROJECT_NAME/build.sh $SRC/
    cp /opt/oss-fuzz/projects/$PROJECT_NAME/run_tests.sh $SRC/
    cp /opt/oss-fuzz/projects/$PROJECT_NAME/*.c $SRC/
    cp /opt/oss-fuzz/projects/$PROJECT_NAME/*.options $SRC/
    cp /opt/oss-fuzz/projects/$PROJECT_NAME/*.dict $SRC/
    cd /
    #patch -tuN $SRC/$PROJECT_NAME/fuzzing/ossfuzz.sh -i /challenge/.ossfuzz.patch -r -
    #cp $SRC/$PROJECT_NAME/fuzzing/cjson_read_fuzzer.c $SRC/$PROJECT_NAME/fuzzing/ewfuzzer.c
#----------------------------------------------------------------------
    build-cleanup
fi
build-srcfolders
mv /src-$LABEL /src

cd $SRC/$PROJECT_NAME


#----------------------------------------------------------------------
if [ ! -d "/home/hacker/fuzz-dojo/$PROJECT_NAME" ]; then
   mkdir -p /home/hacker/fuzz-dojo/$PROJECT_NAME
   cp -r $SRC/*.c /home/hacker/fuzz-dojo/$PROJECT_NAME
   cp $SRC/build.sh /home/hacker/fuzz-dojo/$PROJECT_NAME
else
   cp -r /home/hacker/fuzz-dojo/$PROJECT_NAME/* $SRC
   cp /home/hacker/fuzz-dojo/$PROJECT_NAME/build.sh $SRC
fi
#----------------------------------------------------------------------
if [ "$4" = "understanding" ]; then
    understanding $2 $3
elif [ "$4" = "planning" ]; then
    planning $2 $3
else
    fuzzlog
    compile
    drivers
fi
mv /src /src-$LABEL
