#!/opt/pwn.college/bash
. /usr/local/sbin/e
export PROJECT_NAME=libarchive
export SANITIZER=$1
[ -z "$SANITIZER" ] && export SANITIZER='none'
cd $SRC

apt-get update && apt-get install -y make autoconf libtool pkg-config \
        libbz2-dev liblzo2-dev liblzma-dev liblz4-dev libz-dev \
        libssl-dev libacl1-dev libattr1-dev lrzip liblzo2-dev \
	      liblz4-tool lzop zstd lcab genisoimage jlha-utils rar default-jdk sharutils
curl -LO http://mirrors.kernel.org/ubuntu/pool/main/a/automake-1.16/automake_1.16.5-1.3_all.deb && \
    apt install ./automake_1.16.5-1.3_all.deb
git clone --depth 1 https://github.com/libarchive/libarchive.git
git clone --depth 1 https://gitlab.gnome.org/GNOME/libxml2.git
# compile libxml2 from source so we can statically link
mkdir /deps && \
  cd $SRC/libxml2 && \
  ./autogen.sh \
      --without-debug \
      --without-ftp \
      --without-http \
      --without-legacy \
      --without-python \
      --enable-static && \
  make -j$(nproc) && \
  make install && \
  cp .libs/libxml2.a /deps/

cp /opt/oss-fuzz/projects/$PROJECT_NAME/build.sh $SRC/
cp /opt/oss-fuzz/projects/$PROJECT_NAME/libarchive_fuzzer.cc $SRC/

#patch -tuN /src/build.sh -i /challenge/.build.patch -r -
cd $SRC/
sudo --preserve-env compile
drivers
