#!/opt/pwn.college/bash
echo 999 > /tmp/initial
echo 999 > /tmp/target
if [ "$1" = "afl" ]; then
    . /usr/local/sbin/eafl
    shift
else
    . /usr/local/sbin/e
fiafl
export PROJECT_NAME=gdk-pixbuf
export SANITIZER=$1
[ -z "$SANITIZER" ] && export SANITIZER='none'
cd $SRC

apt-get update && apt-get install -y ffmpeg python3-pip gtk-doc-tools libffi-dev

pip3 install meson==0.55.3 ninja

git clone --depth 1 https://gitlab.gnome.org/GNOME/gdk-pixbuf.git
wget https://ftp.gnome.org/pub/gnome/sources/glib/2.64/glib-2.64.2.tar.xz
tar xvJf $SRC/glib-2.64.2.tar.xz

pip3 install corpus-replicator
corpus-replicator -o corpus image_gif_gif_ffmpeg.yml image_jpg_jpg_ffmpeg.yml image_png_png_ffmpeg.yml image
git clone --depth 1 https://github.com/glennrp/libpng.git && \
    find $SRC/gdk-pixbuf/tests/ \( -name '*.jpeg' -o -name '*.jpg' -o -name '*.png' \) -exec cp -v '{}' corpus/ ';' && \
    find $SRC/libpng -name "*.png" | grep -v crashers | xargs cp -t corpus/ && \
    zip -q $SRC/gdk-pixbuf_seed_corpus.zip corpus/* && \
    rm -rf libpng corpus

wget https://raw.githubusercontent.com/google/fuzzing/master/dictionaries/png.dict
wget https://raw.githubusercontent.com/google/fuzzing/master/dictionaries/jpeg.dict
wget https://raw.githubusercontent.com/google/fuzzing/master/dictionaries/gif.dict

awk 1 $SRC/*.dict > $SRC/gdk-pixbuf.dict && \
    rm -f $SRC/png.dict $SRC/jpeg.dict $SRC/gif.dict

cp /opt/oss-fuzz/projects/$PROJECT_NAME/build.sh $SRC/
cp /opt/oss-fuzz/projects/$PROJECT_NAME/targets $SRC/fuzz

cd $SRC/gdk-pixbuf
[ ! "$SANITIZER" = "introspector" ] && [ ! "$SANITIZER" = "coverage" ] && zip -ry /home/hacker/.vnc/$PROJECT_NAME-$(TZ=US/Arizona date +"%F--%H-%M-%S") /home/hacker/$PROJECT_NAME
sudo --preserve-env compile
drivers
