#!/opt/pwn.college/bash
. /usr/local/sbin/e
export PROJECT_NAME=woff2
export SANITIZER=$1
[ -z "$SANITIZER" ] && export SANITIZER='none'
cd $SRC

#apt-get update && apt-get install -y make autoconf automake libtool

rm -rf $SRC/$PROJECT_NAME
#git clone --depth 1 --recursive https://github.com/google/woff2
cp -r /opt/fuzz-targets/woff2 /src

cp /opt/oss-fuzz/projects/$PROJECT_NAME/*.options $SRC
cp /opt/oss-fuzz/projects/$PROJECT_NAME/build.sh $SRC
cp -r /opt/oss-fuzz/projects/$PROJECT_NAME/corpus $SRC

patch -tuN /src/build.sh -i /challenge/.build.patch -r -
cd $SRC/woff2
if [ ! -d "/home/hacker/$PROJECT_NAME" ]; then
   mkdir /home/hacker/$PROJECT_NAME
   cp $SRC/$PROJECT_NAME/src/*.cc /home/hacker/$PROJECT_NAME
   chown -R hacker /home/hacker/$PROJECT_NAME
else
   cp /home/hacker/$PROJECT_NAME/*.cc $SRC/$PROJECT_NAME/src
fi

sudo --preserve-env compile
drivers
