#!/opt/pwn.college/bash
echo 70 > /tmp/initial
echo 75 > /tmp/target
if [ "$1" = "afl" ]; then
    . /usr/local/sbin/eafl
    shift
else
    . /usr/local/sbin/e
fi
export PROJECT_NAME=woff2
export SANITIZER=$1
[ -z "$SANITIZER" ] && export SANITIZER='none'
cd $SRC

#apt-get update && apt-get install -y make autoconf automake libtool

rm -rf $SRC/$PROJECT_NAME
#git clone --depth 1 --recursive https://github.com/google/woff2
cp -r /opt/fuzz-targets/woff2 $SRC

cp /opt/oss-fuzz/projects/$PROJECT_NAME/*.options $SRC
cp /opt/oss-fuzz/projects/$PROJECT_NAME/build.sh $SRC
cp -r /opt/oss-fuzz/projects/$PROJECT_NAME/corpus $SRC

patch -tuN $SRC/build.sh -i /challenge/.build.patch -r -
cd $SRC/woff2
if [ ! -d "/home/hacker/$PROJECT_NAME" ]; then
   mkdir /home/hacker/$PROJECT_NAME
   cp $SRC/$PROJECT_NAME$SRC/*.cc /home/hacker/$PROJECT_NAME
   chown -R hacker /home/hacker/$PROJECT_NAME
else
   cp /home/hacker/$PROJECT_NAME/*.cc $SRC/$PROJECT_NAME$SRC
fi

mkdir -p /home/hacker/.log
[ ! "$SANITIZER" = "introspector" ] && [ ! "$SANITIZER" = "coverage" ] && zip -ry /home/hacker/.log/$(TZ=US/Arizona date +"%F--%H-%M-%S")-$PROJECT_NAME /home/hacker/$PROJECT_NAME
sudo --preserve-env compile
drivers
