#!/opt/pwn.college/bash
if [ "$1" = "afl" ]; then
    . /usr/local/sbin/eafl
    shift
else
    . /usr/local/sbin/e
fi
export PROJECT_NAME=libtpms
export SANITIZER=$1
[ -z "$SANITIZER" ] && export SANITIZER='none'
cd $SRC

#apt-get update && \
#        apt-get install -y \
#        make autoconf automake libtool \
#        libstdc++-9-dev \
#        libssl-dev libseccomp-dev pkg-config
#git clone --depth 1 https://github.com/stefanberger/libtpms libtpms

cp -r /opt/fuzz-targets/libtpms /src

cp /opt/oss-fuzz/projects/$PROJECT_NAME/build.sh $SRC/

patch -tuN /src/$PROJECT_NAME/tests/oss-fuzz.sh -i /challenge/.oss-fuzz.patch -r -
cd $SRC/libtpms
if [ ! -d "/home/hacker/$PROJECT_NAME" ]; then
   mkdir /home/hacker/$PROJECT_NAME
   cp $SRC/$PROJECT_NAME/tests/fuzz.cc $SRC/$PROJECT_NAME/tests/fuzz-newfuzzer.cc
   cp $SRC/$PROJECT_NAME/tests/*.cc /home/hacker/$PROJECT_NAME
   cp /src/$PROJECT_NAME/tests/oss-fuzz.sh /home/hacker/$PROJECT_NAME
   chown -R hacker /home/hacker/$PROJECT_NAME
else
   cp /home/hacker/$PROJECT_NAME/*.cc $SRC/$PROJECT_NAME/tests
   cp /home/hacker/$PROJECT_NAME/oss-fuzz.sh /src/$PROJECT_NAME/tests
fi
sudo --preserve-env compile
drivers
