#!/opt/pwn.college/bash
if [ "$1" = "afl" ]; then
    . /usr/local/sbin/eafl
    shift
else
    . /usr/local/sbin/e
fi
export PROJECT_NAME=libtpms
export SANITIZER=$1
[ -z "$SANITIZER" ] && export SANITIZER='none'
cd $SRC

#apt-get update && \
#        apt-get install -y \
#        make autoconf automake libtool \
#        libstdc++-9-dev \
#        libssl-dev libseccomp-dev pkg-config
#git clone --depth 1 https://github.com/stefanberger/libtpms libtpms

cp -r /opt/fuzz-targets/libtpms /src

cp /opt/oss-fuzz/projects/$PROJECT_NAME/build.sh $SRC/

cd $SRC/libtpms

sudo --preserve-env compile
drivers
