#!/opt/pwn.college/bash
export PROJECT_NAME=libtpms
/challenge/.loc_count
cd /src

#apt-get update && \
#        apt-get install -y \
#        make autoconf automake libtool \
#        libstdc++-9-dev \
#        libssl-dev libseccomp-dev pkg-config
#git clone --depth 1 https://github.com/stefanberger/libtpms libtpms

cp -r /opt/fuzz-targets/libtpms /src

cp /opt/oss-fuzz/projects/$PROJECT_NAME/build.sh /src/

patch -tuN /src/$PROJECT_NAME/tests/oss-fuzz.sh -i /challenge/.oss-fuzz.patch -r -
cd /src/libtpms

cp /home/hacker/$PROJECT_NAME/*.cc /src/$PROJECT_NAME/tests
cp /home/hacker/$PROJECT_NAME/build.sh /src
/challenge/.fi $PROJECT_NAME
