#!/opt/pwn.college/bash
echo 13 > /tmp/initial
echo 18 > /tmp/target
if [ "$1" = "afl" ]; then
    . /usr/local/sbin/eafl
    shift
else
    . /usr/local/sbin/e
fi
export PROJECT_NAME=nginx
export SANITIZER=$1
[ -z "$SANITIZER" ] && export SANITIZER='none'
cd $SRC

rm -rf nginx
#apt-get update && apt-get install -y libpcre3-dev zlib1g-dev mercurial ninja-build cmake liblzma-dev libz-dev binutils libtool
#hg clone http://hg.nginx.org/nginx/
#git clone --depth 1 https://github.com/google/libprotobuf-mutator.git
#git clone --depth 1 https://github.com/google/fuzzer-test-suite

cp -r /opt/fuzz-targets/nginx $SRC/
cp -r /opt/fuzz-targets/libprotobuf-mutator $SRC/
cp -r /opt/fuzz-targets/fuzzer-test-suite $SRC/


cp -r /opt/fuzz-targets/LPM $SRC/

mkdir LPM && cd LPM && cmake ../libprotobuf-mutator -GNinja -DLIB_PROTO_MUTATOR_DOWNLOAD_PROTOBUF=ON -DLIB_PROTO_MUTATOR_TESTING=OFF -DCMAKE_BUILD_TYPE=Release && ninja && cd $SRC


cp -r /opt/oss-fuzz/projects/$PROJECT_NAME/fuzz $SRC

cp /opt/oss-fuzz/projects/$PROJECT_NAME/add_fuzzers.diff $SRC/
cp /opt/oss-fuzz/projects/$PROJECT_NAME/make_fuzzers $SRC/
cp /opt/oss-fuzz/projects/$PROJECT_NAME/build.sh $SRC/

patch -tuN $SRC/make_fuzzers -i /challenge/.make_fuzzers.patch -r -
cd $SRC/$PROJECT_NAME
if [ ! -d "/home/hacker/$PROJECT_NAME" ]; then
   mkdir /home/hacker/$PROJECT_NAME
   cp $SRC/fuzz/http_request_fuzzer.cc $SRC/fuzz/new_fuzzer.cc
   cp $SRC/fuzz/http_request_fuzzer.dict $SRC/fuzz/new_fuzzer.dict
   cp $SRC/fuzz/*.dict /home/hacker/$PROJECT_NAME
   cp $SRC/fuzz/*.c /home/hacker/$PROJECT_NAME
   cp $SRC/fuzz/*.cc /home/hacker/$PROJECT_NAME
   cp $SRC/build.sh /home/hacker/$PROJECT_NAME
   chown -R hacker /home/hacker/$PROJECT_NAME
else
   cp /home/hacker/$PROJECT_NAME/*.dict $SRC/fuzz
   cp /home/hacker/$PROJECT_NAME/*.c $SRC/fuzz
   cp /home/hacker/$PROJECT_NAME/*.cc $SRC/fuzz
   cp /home/hacker/$PROJECT_NAME/build.sh $SRC
fi
mkdir -p /home/hacker/.log
[ ! "$SANITIZER" = "introspector" ] && [ ! "$SANITIZER" = "coverage" ] && zip -ry /home/hacker/.log/$(TZ=US/Arizona date +"%F--%H-%M-%S")-$PROJECT_NAME /home/hacker/$PROJECT_NAME
compile
drivers
