#!/opt/pwn.college/bash
. /usr/local/sbin/e
if [ "$?" -gt 0 ]; then
    exit 1
fi
export LABEL=$1
export PROJECT_NAME=liblouis
export SANITIZER=$1
if [ -z "$SANITIZER" ]; then
    export SANITIZER='none'
    export LABEL='none'$LABEL
fi

if [ ! -d "/src-orig" ]; then
#----------------------------------------------------------------------
    #apt-get update && apt-get install -y make autoconf automake libtool \
    #  pkg-config zlib1g-dev libpci-dev
    #git clone --depth 1 https://github.com/liblouis/liblouis

    cp -r /downloads/liblouis $SRC

    cp /opt/oss-fuzz/projects/$PROJECT_NAME/build.sh $SRC/
    patch -tuN $SRC/liblouis/tests/fuzzing/build.sh -i /challenge/.build.patch -r -

    cp $SRC/$PROJECT_NAME/tests/fuzzing/fuzz_backtranslate.c $SRC/$PROJECT_NAME/tests/fuzzing/fuzz_newfuzzer.c
#----------------------------------------------------------------------
    build-cleanup
fi
build-srcfolders
mv /src-$LABEL /src

cd $SRC/$PROJECT_NAME
#----------------------------------------------------------------------
if [ ! -d "/home/hacker/fuzz-dojo/$PROJECT_NAME" ]; then
   mkdir -p /home/hacker/fuzz-dojo/$PROJECT_NAME
   cp $SRC/$PROJECT_NAME/tests/fuzzing/*.c /home/hacker/fuzz-dojo/$PROJECT_NAME
   cp $SRC/liblouis/tests/fuzzing/build.sh /home/hacker/fuzz-dojo/$PROJECT_NAME
else
   cp /home/hacker/fuzz-dojo/$PROJECT_NAME/*.c $SRC/$PROJECT_NAME/tests/fuzzing
   cp /home/hacker/fuzz-dojo/$PROJECT_NAME/build.sh $SRC/liblouis/tests/fuzzing
fi
#----------------------------------------------------------------------
if [ "$4" = "understanding" ]; then
    understanding $2 $3
elif [ "$4" = "planning" ]; then
    planning $2 $3
else
    fuzzlog
    compile
    drivers
fi
mv /src /src-$LABEL
