#!/opt/pwn.college/bash
. /usr/local/sbin/eafl
export PROJECT_NAME=guetzli
export SANITIZER=$1
[ -z "$SANITIZER" ] && export SANITIZER='none'
cd $SRC

#apt-get update && apt-get install -y make autoconf automake libtool libpng-dev pkg-config curl

#mkdir afl-testcases
#cd afl-testcases/ && curl https://lcamtuf.coredump.cx/afl/demo/afl_testcases.tgz | tar -xz
#cd $SRC
cp -r /opt/fuzz-targets/afl-testcases /src

zip guetzli_fuzzer_seed_corpus.zip afl-testcases/jpeg/full/images/* afl-testcases/jpeg_turbo/full/images/* $SRC/libjpeg-turbo/testimages/

#git clone --depth=1 https://github.com/google/guetzli 
cp -r /opt/fuzz-targets/guetzli /src

cp /opt/oss-fuzz/projects/$PROJECT_NAME/build.sh $SRC/

#patch -tuN /src/build.sh -i /challenge/.build.patch -r -
cd $SRC/$PROJECT_NAME

sudo --preserve-env compile
drivers
