#!/opt/pwn.college/bash
export PROJECT_NAME=guetzli
/challenge/.loc_count
cd /src

cp -r /opt/fuzz-targets/afl-testcases /src

zip guetzli_fuzzer_seed_corpus.zip afl-testcases/jpeg/full/images/* afl-testcases/jpeg_turbo/full/images/* /src/libjpeg-turbo/testimages/

#git clone --depth=1 https://github.com/google/guetzli 
cp -r /opt/fuzz-targets/guetzli /src

cd /src/$PROJECT_NAME
cp /home/hacker/$PROJECT_NAME/*.cc /src/$PROJECT_NAME

/challenge/.fi $PROJECT_NAME
