#!/bin/sh
. /usr/local/sbin/e
export PROJECT_NAME=json
export SANITIZER=$1
[ -z "$SANITIZER" ] && export SANITIZER='none'
cd $SRC

#apt-get update && apt-get install -y binutils make
rm -rf $PROJECT_NAME
git clone --depth 1 -b develop https://github.com/nlohmann/json.git

# This is to fix Fuzz Introspector build by using LLVM old pass manager
# re https://github.com/ossf/fuzz-introspector/issues/305
export OLD_LLVMPASS=1

cp /opt/oss-fuzz/projects/$PROJECT_NAME/parse_afl_fuzzer.dict $SRC/
cp /opt/oss-fuzz/projects/$PROJECT_NAME/*.options $SRC/
cp /opt/oss-fuzz/projects/$PROJECT_NAME/build.sh $SRC/

patch -tuN $SRC/$PROJECT_NAME/tests/Makefile -i /challenge/Makefile.patch -r -
cd $SRC/$PROJECT_NAME
if [ ! -d "/home/hacker/$PROJECT_NAME" ]; then
   mkdir /home/hacker/$PROJECT_NAME
   cp $SRC/$PROJECT_NAME/tests/src/fuzzer-parse_ubjson.cpp $SRC/$PROJECT_NAME/tests/src/fuzzer-parse_new.cpp
   cp $SRC/$PROJECT_NAME/tests/src/fuzzer*.cpp /home/hacker/$PROJECT_NAME
   cp $SRC/$PROJECT_NAME/tests/Makefile /home/hacker/$PROJECT_NAME
   cp /opt/oss-fuzz/projects/$PROJECT_NAME/build.sh /home/hacker/$PROJECT_NAME
else
   cp /home/hacker/$PROJECT_NAME/*.cpp $SRC/$PROJECT_NAME/tests/src
   cp /home/hacker/$PROJECT_NAME/Makefile $SRC/$PROJECT_NAME/tests
fi
compile
