#!/bin/bash
export PROJECT_NAME=json
/usr/local/sbin/loc_count
cd /src
rm -rf $PROJECT_NAME
git clone --depth 1 -b develop https://github.com/nlohmann/json.git
# This is to fix Fuzz Introspector build by using LLVM old pass manager
# re https://github.com/ossf/fuzz-introspector/issues/305
export OLD_LLVMPASS=1

cd /src/$PROJECT_NAME
/usr/local/sbin/fi $PROJECT_NAME
