#!/bin/sh
. /usr/local/sbin/e
export PROJECT_NAME=argo
[ -z "$SANITIZER" ] && export SANITIZER='none'
cd $SRC

apt-get update && apt-get install -y wget zip
git clone --depth 1 https://github.com/argoproj/argo-cd
git clone --depth 1 https://github.com/argoproj/argo-workflows
git clone --depth 1 https://github.com/argoproj/argo-events
git clone --depth 1 https://github.com/argoproj/gitops-engine
git clone --depth 1 https://github.com/argoproj/argo-rollouts
git clone --depth 1 https://github.com/cncf/cncf-fuzzing
wget https://github.com/facebook/zstd/releases/download/v1.4.2/zstd-1.4.2.tar.gz && \
    tar xzf zstd-1.4.2.tar.gz && \
    cd zstd-1.4.2 && \
    export CC=clang && \
    export CXX=clang++ && \
    export CXXFLAGS="-stdlib=libc++" && \
    make -j$(nproc)

cp /opt/oss-fuzz/projects/$PROJECT_NAME/build.sh $SRC/
cd $SRC/$PROJECT_NAME
compile
