#!/bin/sh
. /usr/local/sbin/e
export PROJECT_NAME=vlc
export SANITIZER=$1
[ -z "$SANITIZER" ] && export SANITIZER='none'
cd $SRC

#apt-get update && apt-get install -y make autoconf automake libtool \
  pkg-config cmake flex bison gettext libglu1-mesa-dev 
git clone --depth 1 https://github.com/videolan/vlc vlc

cp /opt/oss-fuzz/projects/$PROJECT_NAME/build.sh $SRC/

cd $SRC/$PROJECT_NAME
if [ ! -d "/home/hacker/$PROJECT_NAME" ]; then
   mkdir /home/hacker/$PROJECT_NAME
   cp $SRC/vlc/test/vlc-demux-libfuzzer.c $SRC/vlc/test/newfuzzer.c
   cp $SRC/vlc/test/Makefile /home/hacker/$PROJECT_NAME
   cp /opt/oss-fuzz/projects/$PROJECT_NAME/build.sh /home/hacker/$PROJECT_NAME
else
   cp /home/hacker/$PROJECT_NAME/* $SRC
fi
#patch -tuN /src/build.sh -i /challenge/build.patch -r -
compile