#!/opt/pwn.college/bash
export PROJECT_NAME=mpg123
/challenge/.loc_count
cd /src
rm -rf /src/$PROJECT_NAME
wget https://www.mpg123.de/snapshot
tar -xvf snapshot
mv mpg123* mpg123

cd /src
/challenge/.fi $PROJECT_NAME
