#!/opt/pwn.college/bash
export PROJECT_NAME=tmux
/challenge/.loc_count
cd /src
rm -rf libevent
rm -rf tmux
rm -rf /work
mkdir -p /work && chmod a+rwx /work

#git clone https://github.com/libevent/libevent.git
cp -r /opt/fuzz-targets/libevent /src
    cd libevent && \
    mkdir build && \
    cd build && \
    cmake -DEVENT__DISABLE_MBEDTLS=ON -DEVENT__DISABLE_OPENSSL=ON -DEVENT__LIBRARY_TYPE=STATIC ../ && \
    make && make install
    
cd /src
#git clone --depth 1 https://github.com/tmux/tmux.git
cp -r /opt/fuzz-targets/tmux /src

cp -r /src /out

cd /src/$PROJECT_NAME
cp /home/hacker/$PROJECT_NAME/*.c /src/$PROJECT_NAME/fuzz
cp /home/hacker/$PROJECT_NAME/*.dict /src/$PROJECT_NAME/fuzz
cp /home/hacker/$PROJECT_NAME/Makefile.am /src/$PROJECT_NAME
/challenge/.fi $PROJECT_NAME
