#!/opt/pwn.college/bash
if [ "$1" = "afl" ]; then
    . /usr/local/sbin/eafl
    shift
else
    . /usr/local/sbin/e
fi
export PROJECT_NAME=haproxy
export SANITIZER=$1
[ -z "$SANITIZER" ] && export SANITIZER='none'

if [ ! -d "/src-orig" ]; then
    cd $SRC
    #rm -rf $SRC/$PROJECT_NAME
    #git clone https://github.com/haproxy/haproxy
    cp -r /opt/fuzz-targets/haproxy $SRC
    
    cp /opt/oss-fuzz-new/projects/$PROJECT_NAME/fuzz* $SRC
    cp /opt/oss-fuzz-new/projects/$PROJECT_NAME/build.sh $SRC

    cp $SRC/fuzz_cfg_parser.c $SRC/fuzz_newfuzzer.c
    patch -tuN $SRC/build.sh -i /challenge/.build.patch -r -

    echo Please wait, creating /src-orig
    chown -hR hacker:hacker $SRC/$PROJECT_NAME
    mv /src /src-orig
fi
#if [ ! -d "/src-$SANITIZER" ]; then
#    echo Please wait, initial setup
rm -rf /src-$SANITIZER
cp -r /src-orig /src-$SANITIZER
#fi

mv /src-$SANITIZER /src

cd $SRC
if [ ! -d "/home/hacker/fuzz-dojo/$PROJECT_NAME" ]; then
   mkdir -p /home/hacker/fuzz-dojo/$PROJECT_NAME
   cp $SRC/*.c /home/hacker/fuzz-dojo/$PROJECT_NAME
   cp $SRC/build.sh /home/hacker/fuzz-dojo/$PROJECT_NAME
   chown -R hacker /home/hacker/fuzz-dojo/$PROJECT_NAME
else
   cp /home/hacker/fuzz-dojo/$PROJECT_NAME/*.c $SRC
   cp /home/hacker/fuzz-dojo/$PROJECT_NAME/build.sh $SRC
fi
mkdir -p /home/hacker/.log
[ ! "$SANITIZER" = "introspector" ] && [ ! "$SANITIZER" = "coverage" ] && zip -ry /home/hacker/.log/$(TZ=US/Arizona date +"%F--%H-%M-%S")-$PROJECT_NAME /home/hacker/fuzz-dojo/$PROJECT_NAME
sudo --preserve-env compile
drivers
chown -hR hacker:hacker /home/hacker/fuzz-dojo
chown -hR hacker:hacker $SRC/$PROJECT_NAME
mv /src /src-$SANITIZER
