#!/bin/sh
. /usr/local/sbin/e
export PROJECT_NAME=sudoers
export SANITIZER=$1
[ -z "$SANITIZER" ] && export SANITIZER='none'
cd $SRC

git clone https://github.com/sudo-project/sudo

cp /opt/oss-fuzz/projects/$PROJECT_NAME/build.sh $SRC/

cd $SRC/$PROJECT_NAME
if [ ! -d "/home/hacker/$PROJECT_NAME" ]; then
   mkdir /home/hacker/$PROJECT_NAME
   cp $SRC/$PROJECT_NAME/plugins/sudoers/regress/fuzz/fuzz_sudoers.c $SRC/$PROJECT_NAME/plugins/sudoers/regress/fuzz/fuzz_new.c
   cp $SRC/$PROJECT_NAME/plugins/sudoers/regress/fuzz/*.c /home/hacker/$PROJECT_NAME
   cp $SRC/$PROJECT_NAME/plugins/sudoers/regress/fuzz/*.dict /home/hacker/$PROJECT_NAME
   cp /opt/oss-fuzz/projects/$PROJECT_NAME/build.sh /home/hacker/$PROJECT_NAME
else
   cp /home/hacker/$PROJECT_NAME/* $SRC
   cp /home/hacker/$PROJECT_NAME/build.sh $SRC
fi
#patch -tuN /src/build.sh -i /challenge/build.patch -r -
compile