homepage: "https://ccache.dev/"
language: c++
primary_contact: "swirsz@asu.edu" 
main_repo: "https://github.com/ccache/ccache"


sanitizers:
  - address
  - undefined

architectures:
  - x86_64

fuzzing_engines:
  - libfuzzer
