#!/opt/pwn.college/bash
. /usr/local/sbin/e
cp /home/hacker/fuzz-dojo/bounded_resource.h /usr/local/include/
if [ "$?" -gt 0 ]; then
    exit 1
fi
export LABEL=$1
export PROJECT_NAME=ccache
export SANITIZER=$1
if [ -z "$SANITIZER" ]; then
    export SANITIZER='none'
    export LABEL='none'$LABEL
fi

if [ ! -d "/src-orig" ]; then
#----------------------------------------------------------------------
# Use the official OSS-Fuzz C/C++ base builder
#FROM gcr.io/oss-fuzz-base/base-builder-c
# Install build dependencies required by ccache
#RUN apt-get update && apt-get install -y \
#    cmake \
#    zlib1g-dev \
#    liblz4-dev \
#    libzstd-dev \
#    && rm -rf /var/lib/apt/lists/*
# Set compiler to clang (required by OSS-Fuzz)
#ENV CC=clang CXX=clang++
# ccache uses CMake. Ensure we use the system CMake, not a bundled one.
#ENV CMAKE_PREFIX_PATH=/usr/local:/usr

    cp -r /downloads/ccache $SRC


    mkdir -p /opt/oss-fuzz/projects/ccache
    cp /challenge/.build.sh /opt/oss-fuzz/projects/ccache/build.sh
    cp /challenge/.ccache_fuzzer.cc /opt/oss-fuzz/projects/ccache/ccache_fuzzer.cc
    cp /challenge/.project.yaml /opt/oss-fuzz/projects/ccache/project.yaml

    cp /challenge/.build.sh $SRC/build.sh
    mkdir -p $SRC/$PROJECT_NAME/fuzz
    cp /challenge/.ccache_fuzzer.cc  $SRC/$PROJECT_NAME/fuzz/ccache_fuzzer.cc

#----------------------------------------------------------------------
    build-cleanup
fi
build-srcfolders
mv /src-$LABEL /src

cd $SRC/$PROJECT_NAME
rm -rf $SRC/$PROJECT_NAME/build

#----------------------------------------------------------------------
if [ ! -d "/home/hacker/fuzz-dojo/$PROJECT_NAME" ]; then
   mkdir -p /home/hacker/fuzz-dojo/$PROJECT_NAME
   cp -r $SRC/$PROJECT_NAME/fuzz/*.cc /home/hacker/fuzz-dojo/$PROJECT_NAME
   cp $SRC/build.sh /home/hacker/fuzz-dojo/$PROJECT_NAME
else
   cp -r /home/hacker/fuzz-dojo/$PROJECT_NAME/* $SRC/$PROJECT_NAME/fuzz
   cp /home/hacker/fuzz-dojo/$PROJECT_NAME/build.sh $SRC
fi
#----------------------------------------------------------------------
if [ "$4" = "understanding" ]; then
    understanding $2 $3
elif [ "$4" = "planning" ]; then
    planning $2 $3
else
    fuzzlog
    compile
    drivers
fi
mv /src /src-$LABEL
