#!/bin/sh
. /usr/local/sbin/e
export PROJECT_NAME=arduinojson
export SANITIZER=$1
[ -z "$SANITIZER" ] && export SANITIZER='none'
cd $SRC

#apt-get update && apt-get install -y make zip git
rm -rf $SRC/$PROJECT_NAME
git clone --depth 1 https://github.com/bblanchon/ArduinoJson.git arduinojson

cp /opt/oss-fuzz/projects/$PROJECT_NAME/build.sh $SRC/

patch -tuN $SRC/build.sh -i /challenge/build.patch -r -
patch -tuN $SRC/$PROJECT_NAME/extras/fuzzing/CMakeLists.txt -i /challenge/build.patch -r -
cp -r $SRC/$PROJECT_NAME/extras/fuzzing/json_corpus $SRC/$PROJECT_NAME/extras/fuzzing/new_corpus
cp -r $SRC/$PROJECT_NAME/extras/fuzzing/json_seed_corpus $SRC/$PROJECT_NAME/extras/fuzzing/new_seed_corpus
cd $SRC/$PROJECT_NAME
if [ ! -d "/home/hacker/$PROJECT_NAME" ]; then
   mkdir /home/hacker/$PROJECT_NAME
   cp $SRC/$PROJECT_NAME/extras/fuzzing/json_fuzzer.cpp $SRC/$PROJECT_NAME/extras/fuzzing/new_fuzzer.cpp
   cp $SRC/$PROJECT_NAME/extras/fuzzing/CMakeLists.txt /home/hacker/$PROJECT_NAME/CMakeLists.txt
   cp $SRC/$PROJECT_NAME/extras/fuzzing/Makefile /home/hacker/$PROJECT_NAME/Makefile
   cp $SRC/$PROJECT_NAME/extras/fuzzing/*.cpp /home/hacker/$PROJECT_NAME
   cp $SRC/build.sh /home/hacker/$PROJECT_NAME
else
   cp /home/hacker/$PROJECT_NAME/*.cpp $SRC/$PROJECT_NAME/extras/fuzzing
   cp /home/hacker/$PROJECT_NAME/CMakeLists.txt $SRC/$PROJECT_NAME/extras/fuzzing
   cp /home/hacker/$PROJECT_NAME/Makefile $SRC/$PROJECT_NAME/extras/fuzzing
   cp /home/hacker/$PROJECT_NAME/build.sh $SRC
fi
compile