#!/opt/pwn.college/bash
export PROJECT_NAME=arduinojson
sudo cp /usr/local/sbin/loc_count /usr/local/sbin/fi /challenge
sudo chmod 4755 /challenge/loc_count /challenge/fi
/challenge/loc_count
cd /src
rm -rf /src/$PROJECT_NAME
git clone --depth 1 https://github.com/bblanchon/ArduinoJson.git arduinojson
cd /src/$PROJECT_NAME
/challenge/fi $PROJECT_NAME
