#!/opt/pwn.college/bash
. /usr/local/sbin/e
export PROJECT_NAME=libpng
export SANITIZER=$1
[ -z "$SANITIZER" ] && export SANITIZER='none'
cd $SRC

apt-get update && \
    apt-get install -y make autoconf automake libtool zlib1g-dev

git clone --depth 1 https://github.com/madler/zlib.git
git clone --depth 1 https://github.com/pnggroup/libpng.git
cp libpng/contrib/oss-fuzz/build.sh $SRC

#patch -tuN /src/build.sh -i /challenge/.build.patch -r -
cd $SRC/libpng

sudo --preserve-env compile
drivers
