#!/bin/sh
. /usr/local/sbin/e
export PROJECT_NAME=tmux
export SANITIZER=$1
[ -z "$SANITIZER" ] && export SANITIZER='none'
cd $SRC

#apt-get update && apt-get install -y autoconf automake bison pkg-config ncurses-dev libtool
rm -rf libevent
rm -rf tmux
rm -rf /work

git clone https://github.com/libevent/libevent.git && \
    cd libevent && \
    mkdir build && \
    cd build && \
    cmake -DEVENT__DISABLE_MBEDTLS=ON -DEVENT__DISABLE_OPENSSL=ON -DEVENT__LIBRARY_TYPE=STATIC ../ && \
    make && make install
    
cd $SRC
git clone --depth 1 https://github.com/tmux/tmux.git
git clone --depth 1 https://github.com/tmux/tmux-fuzzing-corpus.git

cp -r /src /out/src 
cp /opt/oss-fuzz/projects/$PROJECT_NAME/build.sh $SRC/

#patch -tuN /src/build.sh -i /challenge/build.patch -r -
cd $SRC/$PROJECT_NAME
if [ ! -d "/home/hacker/$PROJECT_NAME" ]; then
   mkdir /home/hacker/$PROJECT_NAME
   cp $SRC/tmux/fuzz/input-fuzzer.c $SRC/tmux/fuzz/new-fuzzer.c
   cp $SRC/tmux/fuzz/*.c /home/hacker/$PROJECT_NAME
   cp $SRC/tmux/fuzz/*.dict /home/hacker/$PROJECT_NAME
   cp $SRC/tmux/Makefile.am /home/hacker/$PROJECT_NAME
   cp /src/build.sh /home/hacker/$PROJECT_NAME
else
   cp /home/hacker/$PROJECT_NAME/*.c $SRC/tmux/fuzz
   cp /home/hacker/$PROJECT_NAME/*.dict $SRC/tmux/fuzz
   cp /home/hacker/$PROJECT_NAME/Makefile.am $SRC/tmux
   cp /home/hacker/$PROJECT_NAME/build.sh $SRC
fi
compile