#!/bin/bash
export PROJECT_NAME=tmux
/usr/local/sbin/loc_count
cd /src
rm -rf libevent
rm -rf tmux
rm -rf /work

git clone https://github.com/libevent/libevent.git && \
    cd libevent && \
    mkdir build && \
    cd build && \
    cmake -DEVENT__DISABLE_MBEDTLS=ON -DEVENT__DISABLE_OPENSSL=ON -DEVENT__LIBRARY_TYPE=STATIC ../ && \
    make && make install
    
cd /src
git clone --depth 1 https://github.com/tmux/tmux.git

cp -r /src /out/src 

cd /src/$PROJECT_NAME
/usr/local/sbin/fi $PROJECT_NAME
