#!/opt/pwn.college/bash
. /usr/local/sbin/e
if [ "$?" -gt 0 ]; then
    exit 1
fi
export LABEL=$1
export PROJECT_NAME=astc-encoder
export SANITIZER=$1
if [ -z "$SANITIZER" ]; then
    export SANITIZER='none'
    export LABEL='none'$LABEL
fi

if [ ! -d "/src-orig" ]; then
#----------------------------------------------------------------------
    #RUN apt-get update && apt-get install -y make autoconf automake libtool
    #RUN git clone --depth 1 https://github.com/ARM-software/astc-encoder
    #WORKDIR astc-encoder/Source
    #COPY build.sh $SRC/

    cp -r /downloads/astc-encoder $SRC

    cp /opt/oss-fuzz/projects/$PROJECT_NAME/build.sh $SRC
    patch -tuN $SRC/$PROJECT_NAME/Source/Fuzzers/build.sh -i /challenge/.build.patch -r -
    cp $SRC/$PROJECT_NAME/Source/Fuzzers/fuzz_astc_physical_to_symbolic.cpp $SRC/$PROJECT_NAME/Source/Fuzzers/fuzz_newfuzzer.cpp
#----------------------------------------------------------------------
    build-cleanup
fi
build-srcfolders
mv /src-$LABEL /src

cd $SRC/$PROJECT_NAME/Source
#----------------------------------------------------------------------
if [ ! -d "/home/hacker/fuzz-dojo/$PROJECT_NAME" ]; then
   mkdir -p /home/hacker/fuzz-dojo/$PROJECT_NAME
   cp $SRC/$PROJECT_NAME/Source/Fuzzers/*.cpp /home/hacker/fuzz-dojo/$PROJECT_NAME
   cp $SRC/build.sh /home/hacker/fuzz-dojo/$PROJECT_NAME
else
   cp /home/hacker/fuzz-dojo/$PROJECT_NAME/*.cpp $SRC/$PROJECT_NAME/Source/Fuzzers
   cp /home/hacker/fuzz-dojo/$PROJECT_NAME/build.sh $SRC
fi
#----------------------------------------------------------------------
if [ "$4" = "understanding" ]; then
    understanding $2 $3
elif [ "$4" = "planning" ]; then
    planning $2 $3
else
    fuzzlog
    compile
    drivers
fi
mv /src /src-$LABEL
