#!/opt/pwn.college/bash
echo 39 > /tmp/initial
echo 44 > /tmp/target
if [ "$1" = "afl" ]; then
    . /usr/local/sbin/eafl
    shift
else
    . /usr/local/sbin/e
fi
export PROJECT_NAME=file
export SANITIZER=$1
[ -z "$SANITIZER" ] && export SANITIZER='none'
cd $SRC

#apt-get update && apt install -y make autoconf automake libtool shtool
#apt-get update && apt install -y libbz2-dev      liblzma-dev      zlib1g-dev      libzstd-dev      liblz4-dev
#apt-get update && apt install -y libbz2-dev:i386 liblzma-dev:i386 zlib1g-dev:i386 libzstd-dev:i386 liblz4-dev:i386 

rm -rf $PROJECT_NAME
rm -rf binary-samples
rm -rf pocs
#git clone --depth 1 https://github.com/file/file.git

# Supplement file's existing test files
#git clone --depth 1 https://github.com/DavidKorczynski/binary-samples.git
#git clone --depth 1 https://github.com/corkami/pocs

cp -r /downloads/file $SRC
cp -r /downloads/binary-samples $SRC
cp -r /downloads/pocs $SRC

cp /opt/oss-fuzz/projects/$PROJECT_NAME/fuzzer_temp_file.h $SRC/
cp /opt/oss-fuzz/projects/$PROJECT_NAME/magic_fuzzer.cc $SRC/
cp /opt/oss-fuzz/projects/$PROJECT_NAME/magic_fuzzer_loaddb.cc $SRC/
cp /opt/oss-fuzz/projects/$PROJECT_NAME/magic_fuzzer_fd.cc $SRC/

cp /opt/oss-fuzz/projects/$PROJECT_NAME/build.sh $SRC/

#patch -tuN $SRC/build.sh -i /challenge/.build.patch -r -
cd $SRC/$PROJECT_NAME
mkdir -p /home/hacker/.log
[ ! "$SANITIZER" = "introspector" ] && [ ! "$SANITIZER" = "coverage" ] && zip -ry /home/hacker/.log/$(TZ=US/Arizona date +"%F--%H-%M-%S")-$PROJECT_NAME /home/hacker/$PROJECT_NAME
compile
drivers
