#!/opt/pwn.college/bash
export PROJECT_NAME=openssl
/challenge/.loc_count

mkdir /src/fuzz
mv /src/$PROJECT_NAME/fuzz/*.c /src/fuzz
rm -rf /src/$PROJECT_NAME

#apt-get install -y make
git clone --depth 1 https://github.com/openssl/openssl.git /src/openssl
cd /src/openssl/ && git submodule update --init fuzz/corpora
cd /src
git clone --depth 1 --branch OpenSSL_1_1_1-stable https://github.com/openssl/openssl.git openssl111
git clone --depth 1 --branch openssl-3.0 https://github.com/openssl/openssl.git openssl30
export AFL_SKIP_OSSFUZZ=1
export AFL_LLVM_MODE_WORKAROUND=0
cp /opt/oss-fuzz/projects/openssl/build.sh /src/
cp /opt/oss-fuzz/projects/openssl/*.options /src/

cp -f /src/fuzz/* /src/$PROJECT_NAME/fuzz 
rm -rf /src/fuzz/
cd /src/$PROJECT_NAME

/challenge/.fi $PROJECT_NAME
