#!/opt/pwn.college/bash
if [ "$?" -gt 0 ]; then
    exit 1
fi
export LABEL=$1
export PROJECT_NAME=aspell-fuzz
export SANITIZER=$1
. /usr/local/sbin/e
if [ -z "$SANITIZER" ]; then
    export SANITIZER='none'
    export LABEL='none'$LABEL
fi

if [ ! -d "/src-orig" ]; then
#----------------------------------------------------------------------
    #RUN git clone --depth 1 https://github.com/gnuaspell/aspell.git $SRC/aspell
    #RUN git clone --depth 1 -b master https://github.com/gnuaspell/aspell-fuzz.git $SRC/aspell-fuzz

    #WORKDIR $SRC/aspell-fuzz
    #COPY build.sh $SRC/

    cp -r /downloads/aspell $SRC
    cp -r /downloads/aspell-fuzz $SRC

    cp /downloads/aspell*.bz2 /tmp

    cp /opt/oss-fuzz/projects/aspell/build.sh $SRC/
    patch -tuN $SRC/$PROJECT_NAME/ossfuzz.sh -i /challenge/.ossfuzz.patch -r -
#----------------------------------------------------------------------
    build-cleanup-oss
fi
build-srcfolders
if [ "$4" == "skip" ]; then
    chown -hR hacker:hacker /src-$LABEL /out
    rm -rf /tmp/build.lck
else
    mv /src-$LABEL /src

    cd $SRC/$PROJECT_NAME
    if [ "$4" = "understanding" ]; then
        understanding_oss $2 $3
    elif [ "$4" = "planning" ]; then
        planning $2 $3
    else
        if [ $(echo -n "$2" | sha256sum | cut -d' ' -f1) != "2ed73ee0d7ad2fd8b8e57fc154cfc26f3948ed32b2844b34479333e5b07712a5" ]; then
            oss_help
            rm -rf /tmp/build.lck
            mv /src /src-$LABEL
            exit 1
        elif [ "$3" != "aspell" ]; then
            echo "[ERROR] Project $3 not available in this challenge"
            rm -rf /tmp/build.lck
            mv /src /src-$LABEL
            exit 1
        fi
        fuzzlog_oss $SRC/$PROJECT_NAME/*.cpp
        compile
        drivers > /dev/null
    fi
    mv /src /src-$LABEL
fi
