#!/opt/pwn.college/bash
export PROJECT_NAME=lighttpd1.4
sudo cp /usr/local/sbin/loc_count /usr/local/sbin/fi /challenge
sudo chmod 4755 /challenge/loc_count /challenge/fi
/challenge/loc_count
cd /src
rm -rf /src/$PROJECT_NAME
git clone https://github.com/lighttpd/lighttpd1.4
cd /src/$PROJECT_NAME
/challenge/fi $PROJECT_NAME
