#!/bin/sh
. /usr/local/sbin/e
export PROJECT_NAME=git
export SANITIZER=$1
[ -z "$SANITIZER" ] && export SANITIZER='none'
cd $SRC

#apt-get update && apt-get install -y zzzzzzzzzz
RUN apt-get update && \
    apt-get install --no-install-recommends -y \
        cvs cvsps gettext libcgi-pm-perl libcurl4-gnutls-dev \
        libdbd-sqlite3-perl liberror-perl libexpat1-dev libhttp-date-perl \
        libio-pty-perl libmailtools-perl libpcre2-dev libpcre3-dev libsvn-perl \
        perl-modules libyaml-perl libz-dev python subversion tcl unzip \
        asciidoc docbook-xsl xmlto libssl-dev zip
RUN git clone https://github.com/git/git git
WORKDIR git
RUN git checkout origin/next
RUN git pull origin next
RUN mkdir -p oss-fuzz
COPY fuzz-* ./oss-fuzz/
COPY Makefile.diff ./
RUN git apply Makefile.diff
COPY build.sh $SRC/
# This is to fix Fuzz Introspector build by using LLVM old pass manager
# re https://github.com/ossf/fuzz-introspector/issues/305
ENV OLD_LLVMPASS 1

cp /opt/oss-fuzz/projects/$PROJECT_NAME/*.c $SRC/
cp /opt/oss-fuzz/projects/$PROJECT_NAME/*.cc $SRC/
zzzzzzzzzz


cp /opt/oss-fuzz/projects/$PROJECT_NAME/build.sh $SRC/

cd $SRC/
if [ ! -d "/home/hacker/$PROJECT_NAME" ]; then
   mkdir /home/hacker/$PROJECT_NAME
   cp $SRC/zzzzzzzzzz.c $SRC/newfuzzer.c
   cp $SRC/*.c /home/hacker/$PROJECT_NAME
   cp $SRC/*.cc /home/hacker/$PROJECT_NAME
   cp /opt/oss-fuzz/projects/$PROJECT_NAME/build.sh /home/hacker/$PROJECT_NAME
else
   cp /home/hacker/$PROJECT_NAME/*.c $SRC
   cp /home/hacker/$PROJECT_NAME/*.cc $SRC
   cp /home/hacker/$PROJECT_NAME/build.sh $SRC
fi
#patch -tuN /src/build.sh -i /challenge/build.patch -r -
compile