#!/bin/bash
export PROJECT_NAME=git
/usr/local/sbin/loc_count
cd /src
rm -rf $PROJECT_NAME

git clone https://github.com/git/git git
cd /src/$PROJECT_NAME
git checkout origin/next
git pull origin next
mkdir -p /src/$PROJECT_NAME/oss-fuzz
cp /opt/oss-fuzz/projects/$PROJECT_NAME/fuzz-* /src/$PROJECT_NAME/oss-fuzz
cp /opt/oss-fuzz/projects/$PROJECT_NAME/Makefile.diff /src/$PROJECT_NAME

cd /src/$PROJECT_NAME
git apply Makefile.diff
# This is to fix Fuzz Introspector build by using LLVM old pass manager
# re https://github.com/ossf/fuzz-introspector/issues/305
export OLD_LLVMPASS=1

cp /opt/oss-fuzz/projects/$PROJECT_NAME/build.sh /src/

patch -tuN /src/build.sh -i /challenge/build.patch -r -
patch -tuN /src/git/Makefile -i /challenge/Makefile.patch -r -

cd /src/$PROJECT_NAME

/usr/local/sbin/fi $PROJECT_NAME
