--- Makefile	2023-09-17 19:42:49.188209698 +0000
+++ Makefile	2023-09-17 19:42:06.520006649 +0000
@@ -752,6 +752,12 @@
 FUZZ_OBJS += oss-fuzz/fuzz-commit-graph.o
 FUZZ_OBJS += oss-fuzz/fuzz-pack-headers.o
 FUZZ_OBJS += oss-fuzz/fuzz-pack-idx.o
+FUZZ_OBJS += oss-fuzz/fuzz-command.o
+FUZZ_OBJS += oss-fuzz/fuzz-cmd-status.o
+FUZZ_OBJS += oss-fuzz/fuzz-cmd-version.o
+FUZZ_OBJS += oss-fuzz/fuzz-cmd-diff.o
+FUZZ_OBJS += oss-fuzz/fuzz-new.o
