#!/opt/pwn.college/bash
. /usr/local/sbin/eafl
export PROJECT_NAME=cmark
export SANITIZER=$1
[ -z "$SANITIZER" ] && export SANITIZER='none'
cd $SRC

#apt-get update && apt-get install -y make cmake python3
#git clone --depth 1 https://github.com/commonmark/cmark.git cmark
cp -r /opt/fuzz-targets/cmark /src/cmark

cp /opt/oss-fuzz/projects/$PROJECT_NAME/build.sh $SRC/
cp /opt/oss-fuzz/projects/$PROJECT_NAME/*.dict $SRC/
cp /opt/oss-fuzz/projects/$PROJECT_NAME/*.options $SRC/

cd $SRC/$PROJECT_NAME
sudo --preserve-env compile
drivers
