#!/bin/sh
. /usr/local/sbin/e
export PROJECT_NAME=zlib
[ -z "$SANITIZER" ] && export SANITIZER='none'
cd $SRC

apt-get update && apt-get install -y make autoconf automake libtool
git clone --depth 1 -b develop https://github.com/madler/zlib.git

cp /opt/oss-fuzz/projects/$PROJECT_NAME/*_fuzzer.c* $SRC/

cp /opt/oss-fuzz/projects/$PROJECT_NAME/build.sh $SRC/
cd $SRC/$PROJECT_NAME
compile
