#!/opt/pwn.college/bash
. /usr/local/sbin/e
if [ "$?" -gt 0 ]; then
    exit 1
fi
export LABEL=$1
export PROJECT_NAME=libyaml
export SANITIZER=$1
if [ -z "$SANITIZER" ]; then
    export SANITIZER='none'
    export LABEL='none'$LABEL
fi

if [ ! -d "/src-orig" ]; then
#----------------------------------------------------------------------
#RUN apt-get update && apt-get install -y make autoconf automake libtool

#RUN git clone --depth=1 https://github.com/yaml/libyaml
#RUN zip $SRC/libyaml_seed_corpus.zip libyaml/examples/*

#WORKDIR libyaml
#COPY run_tests.sh build.sh *.h *_fuzzer.c libyaml_fuzzer.options yaml.dict $SRC/


    cp -r /downloads/libyaml $SRC
    zip $SRC/libyaml_seed_corpus.zip $SRC/libyaml/examples/*
    #cp /downloads/aspell*.bz2 $SRC

    cp /opt/oss-fuzz/projects/libyaml/run_tests.sh $SRC
    cp /opt/oss-fuzz/projects/libyaml/build.sh $SRC
    cp /opt/oss-fuzz/projects/libyaml/*.h $SRC
    cp /opt/oss-fuzz/projects/libyaml/*_fuzzer.c $SRC
    cp /opt/oss-fuzz/projects/libyaml/libyaml_fuzzer.options $SRC
    cp /opt/oss-fuzz/projects/libyaml/yaml.dict $SRC
    #cp /challenge/.fuzz-packet_seed_corpus.zip $OUT/fuzz-packet_seed_corpus.zip
    #patch -tuN $SRC/$PROJECT_NAME/ossfuzz.sh -i /challenge/.ossfuzz.patch -r -
    #patch -tuN $SRC/$PROJECT_NAME/Makefile.am -i /challenge/.Makefile.patch -r -
        
    #cp $SRC/$PROJECT_NAME/aspell_fuzzer.cpp $SRC/$PROJECT_NAME/new_fuzzer.cpp
#----------------------------------------------------------------------
    build-cleanup
fi
build-srcfolders
mv /src-$LABEL /src

cd $SRC/$PROJECT_NAME
#----------------------------------------------------------------------
if [ ! -d "/home/hacker/fuzz-dojo/$PROJECT_NAME" ]; then
   mkdir -p /home/hacker/fuzz-dojo/$PROJECT_NAME
   cp $SRC/*.c /home/hacker/fuzz-dojo/$PROJECT_NAME
   cp $SRC/build.sh /home/hacker/fuzz-dojo/$PROJECT_NAME
else
   cp /home/hacker/fuzz-dojo/$PROJECT_NAME/*.c $SRC
   cp /home/hacker/fuzz-dojo/$PROJECT_NAME/build.sh $SRC
fi
#----------------------------------------------------------------------
if [ "$4" = "understanding" ]; then
    understanding $2 $3
elif [ "$4" = "planning" ]; then
    planning $2 $3
else
    fuzzlog
    compile
    drivers
fi
mv /src /src-$LABEL
