#!/bin/sh
. /usr/local/sbin/e
export PROJECT_NAME=kamailio
[ -z "$SANITIZER" ] && export SANITIZER='none'
cd $SRC

#apt-get update && apt-get install -y bison flex
git clone https://github.com/kamailio/kamailio

cp /opt/oss-fuzz/projects/$PROJECT_NAME/build.sh $SRC/
cd $SRC
compile
