#!/bin/sh
. /usr/local/sbin/e
export PROJECT_NAME=kamailio
[ -z "$SANITIZER" ] && export SANITIZER='none'
cd $SRC

rm -rf $SRC/$PROJECT_NAME
#apt-get update && apt-get install -y bison flex
git clone https://github.com/kamailio/kamailio

cp /opt/oss-fuzz/projects/$PROJECT_NAME/build.sh $SRC/
cd $SRC
if [ ! -d "/home/hacker/$PROJECT_NAME" ]; then
   mkdir /home/hacker/$PROJECT_NAME
   cp $SRC/$PROJECT_NAME/misc/fuzz/fuzz_uri.c $SRC/$PROJECT_NAME/misc/fuzz/newfuzzer.c
   cp $SRC/$PROJECT_NAME/misc/fuzz/*.c /home/hacker/$PROJECT_NAME
   cp /opt/oss-fuzz/projects/$PROJECT_NAME/build.sh /home/hacker/$PROJECT_NAME
else
   cp /home/hacker/$PROJECT_NAME/*.c $SRC/$PROJECT_NAME/misc/fuzz
   cp /home/hacker/$PROJECT_NAME/build.sh $SRC
fi
patch -tuN /src/build.sh -i /challenge/build.patch -r -
compile
