#!/bin/bash
export PROJECT_NAME=kamailio
sudo cp /usr/local/sbin/loc_count /usr/local/sbin/fi /challenge
sudo chmod 4755 /challenge/loc_count /challenge/fi
/challenge/loc_count
cd /src
/challenge/fi $PROJECT_NAME
