#!/opt/pwn.college/bash
export PROJECT_NAME=w3m
/challenge/.loc_count
cd /src

#apt-get update && apt-get install -y libgc-dev
#git clone https://github.com/tats/w3m
cp -r /opt/fuzz-targets/w3m /src

cp /opt/oss-fuzz/projects/$PROJECT_NAME/build.sh /src/

patch -tuN /src/build.sh -i /challenge/.build.patch -r -

cp /home/hacker/$PROJECT_NAME/*.c /src/$PROJECT_NAME/fuzz
cp /home/hacker/$PROJECT_NAME/build.sh /src

/challenge/.fi $PROJECT_NAME
