#!/opt/pwn.college/bash
. /usr/local/sbin/e
if [ "$?" -gt 0 ]; then
    exit 1
fi
export LABEL=$1
export PROJECT_NAME=haproxy
export SANITIZER=$1
if [ -z "$SANITIZER" ]; then
    export SANITIZER='none'
    export LABEL='none'$LABEL
fi

if [ ! -d "/src-orig" ]; then
#----------------------------------------------------------------------
    cd $SRC
    #rm -rf $SRC/$PROJECT_NAME
    #git clone https://github.com/haproxy/haproxy
    cp -r /downloads/haproxy $SRC
    
    cp /opt/oss-fuzz/projects/$PROJECT_NAME/fuzz* $SRC
    cp /opt/oss-fuzz/projects/$PROJECT_NAME/build.sh $SRC

    cp $SRC/fuzz_cfg_parser.c $SRC/fuzz_newfuzzer.c
    patch -tuN $SRC/build.sh -i /challenge/.build.patch -r -

#----------------------------------------------------------------------
    build-cleanup
fi
#if [ ! -d "/src-$LABEL" ]; then
#    echo Please wait, initial setup
rm -rf /src-$LABEL
cp -r /src-orig /src-$LABEL
#fi

mv /src-$LABEL /src

cd $SRC
#----------------------------------------------------------------------
if [ ! -d "/home/hacker/fuzz-dojo/$PROJECT_NAME" ]; then
   mkdir -p /home/hacker/fuzz-dojo/$PROJECT_NAME
   cp $SRC/*.c /home/hacker/fuzz-dojo/$PROJECT_NAME
   cp $SRC/build.sh /home/hacker/fuzz-dojo/$PROJECT_NAME
else
   cp /home/hacker/fuzz-dojo/$PROJECT_NAME/*.c $SRC
   cp /home/hacker/fuzz-dojo/$PROJECT_NAME/build.sh $SRC
fi
#----------------------------------------------------------------------
if [ "$4" = "understanding" ]; then
    understanding $2 $3
elif [ "$4" = "planning" ]; then
    planning $2 $3
else
    fuzzlog
    compile
    drivers
fi
mv /src /src-$LABEL
